### ISSUE TITLE
🧩 Browser extention

### ISSUE THREAD

**Issue by daniel31x13** [linkwarden/linkwarden#100]

**Comment by cuken** [comment]
For an MVP to iron out any Browser Extensions -> LinkWarden API calls, could something like: https://chrome.google.com/webstore/detail/linkding-extension/beakmhbijpdhipnjhnclmhgjlddhidpe be used as a starting point?

A swap of the linkding API to LinkWarden and a few adjustments to the html/css would give a jump start before an entirely new extension was written.

**Comment by daniel31x13** [comment]
Yeah that's fine, can we also make it compatible with Safari?

**Comment by crkos** [comment]
Hello, I'd like to work on this, I've working on this for these past days, here the link to it: https://github.com/crkos/linkwarden-extension/tree/dev

You can check it out, and if y'all like it, it just lacks the api keys implementation and its propers queries to the site

**Comment by daniel31x13** [comment]
Thank you, checking it out...

**Comment by daniel31x13** [comment]
Closing this issue, will be released in the next version.

**Comment by sammcj** [comment]
That's exciting! A lack of Firefox extension is the only thing stopping me really trying out LW properly. Can't wait!

**Comment by thibaultmol** [comment]
Since the actual extension repo isn't linked in this issue. Just going to put this here real quick:
https://github.com/linkwarden/browser-extension
