### ISSUE TITLE
Moving bookmark to another collection break download links

### ISSUE THREAD

**Issue by GrinGrin** [linkwarden/linkwarden#122]
Hi,

If you save a link to a collection and decide later to move it to another collection, png/pdf files are note moved to the new collection's folder leading to broken links as they are dynamically generated for the current bookmark's collection.

If you save a new bookmark to the default "unnamed collection", move it after to another collection and then delete the "unnamed collection", you lose the files and need to delete and recreate the bookmark to generate again the files.

Expected behavior:

- Move files accordingly when changing the collection
- Offer option to regenerate png/pdf files

**Comment by daniel31x13** [comment]
Thanks for pointing this out, fixing it...

**Comment by daniel31x13** [comment]
This is now fixed.
