### ISSUE TITLE
Ability to disable signups

### ISSUE THREAD

**Issue by ItsNoted** [linkwarden/linkwarden#125]
If we use this for personal use, we may want to disable signups. An option to do so would be great!

**Comment by daniel31x13** [comment]
This is already part of the Todo and is linked to issue #116.

**Comment by MortRainey** [comment]
Is there a workaround? I don't feel comfortable with a server online where everyone could register.

**Comment by SoCuul** [comment]
Even just an environment variable that disallows user adding would be sufficient!

**Comment by daniel31x13** [comment]
You can now disable registration by including the following line inside your environment variables (.env file):

```env
NEXT_PUBLIC_DISABLE_REGISTRATION=true
```

**Comment by MortRainey** [comment]
works! Thank you!

**Comment by daniel31x13** [comment]
No problem!
