### ISSUE TITLE
Compact List View

### ISSUE THREAD

**Issue by Snuupy** [linkwarden/linkwarden#134]
**Is your feature request related to a problem? Please describe.**

Is it possible to have a more compact view (say, a list view) with less padding? maybe this is covered by https://github.com/orgs/linkwarden/projects/1/views/1?pane=issue&itemId=34807308 .

https://discord.com/channels/1117993124669702164/1123628004145369149/1138270774231306251

https://media.discordapp.net/attachments/1123628004145369149/1138270774034182155/image.png?width=1440&height=666

**Additional context**

like raindrop.io

**Comment by daniel31x13** [comment]
Hello, thanks for the suggestion.
Added to Todo...

**Comment by YeeJiaWei** [comment]
Hi there, is that anyone working on this?

**Comment by daniel31x13** [comment]
@YeeJiaWei Sorry for the late reply, I was busy releasing Linkwarden v2.0.0, are you still available?

**Comment by YeeJiaWei** [comment]
@daniel31x13 yea, im still available

**Comment by daniel31x13** [comment]
@YeeJiaWei Thanks, that'd be great if you could handle this task.
Just make sure you format your code with the "prettier" extension in vscode to keep the code consistent.
DM me on Discord or Twitter for a more synchronous communication.

**Comment by YeeJiaWei** [comment]
@daniel31x13 Sure, will start it as soon as possible

**Comment by daniel31x13** [comment]
@YeeJiaWei, quick check: any progress on this? 
No worries if you're busy – just give me a heads-up so I can take over if needed. Thanks.

**Comment by daniel31x13** [comment]
Added in [v2.4.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.0).
