### ISSUE TITLE
Archive.org snapshot option

### ISSUE THREAD

**Issue by kcoderhtml** [linkwarden/linkwarden#143]
Having the ability to trigger an archive.org snapshot and a link to that snapshot would be a helpful enhancement. To avoid triggering multiple builds from lots of people, a feature could also be added to check if a snapshot has been created for that page within a certain time frame.

**Comment by daniel31x13** [comment]
This was actually something I had in mind earlier.

One thing that we should note is that there may be some people who don’t like their data to be scanned by archive.org (for any reasons) so because of this, we need to make it a optional for each link.

**Comment by kcoderhtml** [comment]
Maybe have it be an optional config value that will enable or disable archive.org as the default for each link, but still have it be an option for each link.

**Comment by daniel31x13** [comment]
Oh that’s exactly what I said, edited my comment for clarity.

**Comment by kcoderhtml** [comment]
This is a really cool project! Thanks for working on this, slightly off-topic, but do you have an API documentation somewhere?

**Comment by daniel31x13** [comment]
Not yet.

**Comment by daniel31x13** [comment]
Glad you like it!
Not yet.

**Comment by kcoderhtml** [comment]
Okay, thanks. I was trying to see if I could create a plugin for logseq to automatically archive links.

**Comment by crkos** [comment]
You could, but you will have to dive into the api routes and figure out what data is being sent out

**Comment by daniel31x13** [comment]
Added this feature in [v1.2.0](https://github.com/linkwarden/linkwarden/releases/tag/v1.2.0).
