### ISSUE TITLE
I hope to optimize the performance of loading list data, currently only 30 pieces of data are so slow

### ISSUE THREAD

**Issue by Nicolasking007** [linkwarden/linkwarden#149]
![image](https://github.com/linkwarden/linkwarden/assets/45583166/0c5f3b25-dec4-4e1a-ae17-84767de408d4)

The server is configured with 8 cores and 16GB of memory

**Comment by Nicolasking007** [comment]
![image](https://github.com/linkwarden/linkwarden/assets/45583166/a758aa9c-9be9-4888-b645-7970e158e61f)

After the list data exceeds 20, the page loaded data keeps repeating

**Comment by daniel31x13** [comment]
Hello @Nicolasking007, could you please elaborate on what exactly is the issue?
Also can you send me the translated version of the first image?
Thanks!

**Comment by Nicolasking007** [comment]
> Hello @Nicolasking007, could you please elaborate on what exactly is the issue? Also can you send me the translated version of the first image? Thanks!


When the page data exceeds 20, pull up to refresh. Interface` {baseURL}/API/routes/links? body= `The body parameter in body=`{"sort": 0, "collectionId": 2}` is duplicated by URL encoding

For example, the parameters for the first request are `{"sort": 0, "collectionId": 2}`, and the parameters for the second request are`%257B%2522sort%2522%253A0%252C%2522collectionId%2522%253A2%257D`

**Comment by Nicolasking007** [comment]
Sorry, the description of URL encoding above may be misleading 
-
For example, the first request parameter `{"sort": 0, "collectionId": 2} `has an OK status and returns 20 pieces of data. The second request parameter` {"cursor": 44, "sort": 0, "collectionId": 2}` has an OK status and returns 2 pieces of data. The third request parameter `{"cursor": 41, "sort": 0, "collectionId": 2}` has an empty data return

![image](https://github.com/linkwarden/linkwarden/assets/45583166/a4ca81ac-202d-4bff-ade4-c9e3d177a51b)

**Comment by Nicolasking007** [comment]
by checking the relevant code of `getCollections.ts` and`getLinks.ts`, `ChatGPT` told me that it seems to be caused by `N+1 query` issues

**Comment by daniel31x13** [comment]
This it irrelevant as of now.
It already runs pretty smooth on multiple instances I deployed.
