### ISSUE TITLE
It would be nice to be able to visit the target page by clicking somewhere on the link card.

### ISSUE THREAD

**Issue by aurora** [linkwarden/linkwarden#169]
A possibility to access the website directly via the "card" of the link would be super. I would expect to be able to access the target page either by clicking on the link title or by clicking on the text that appears next to the "link icon". At the moment it looks like I have to call up the edit dialogue first to get to the clickable page URL. Thanks & keep up the good work :-)

![Screenshot 2023-09-20 140344](https://github.com/linkwarden/linkwarden/assets/304837/2fcd4591-5700-4e05-8cb5-0cd4fb14152a)

**Comment by zarevskaya** [comment]
I agree with you, at first I didn't understand where to click. This is not necessarily intuitive.

**Comment by zarevskaya** [comment]
> I'm getting to this...

Cool! Thanks for your work!

This application has very interesting potential.

**Comment by daniel31x13** [comment]
No problem!
It’s out!

**Comment by zarevskaya** [comment]
Do you mean the card is clickable?

**Comment by daniel31x13** [comment]
Yes, the links are clickable.
And if you click outside the link it’ll open up the link details.

**Comment by zarevskaya** [comment]
Thank you very much :)

**Comment by aurora** [comment]
Cool! Thanks a lot :-)
