### ISSUE TITLE
Provide docker image for m1 mac

### ISSUE THREAD

**Issue by peschmae** [linkwarden/linkwarden#175]
**Describe the bug**
Currently the docker image only works on amd64 platforms, mostly due to the fact that generating the website snapshots crashes.

There are a few issues at playwright about similar issues, for example [playwright#11150](https://github.com/microsoft/playwright/issues/11150), which hint at chrome beeing a possible culprit.

Using firefox to create the renderings, might solve this issue.

**To Reproduce**
1. Use macOS M1
2. Build container image (without plattform flag)
3. Start container
4. Try to scrape website

**Expected behavior**
The website should be scrapped properly without the container crashing

**Desktop (please complete the following information):**
 - OS: macOS on Appli silicon

**Comment by peschmae** [comment]
You can assign this ticket to me, I'll work on it and create a PR

**Comment by daniel31x13** [comment]
Thank you @peschmae.

**Comment by daniel31x13** [comment]
@peschmae I think I figured out the problem and here's the solution:
https://docs.docker.com/build/building/multi-platform/

**Comment by peschmae** [comment]
I've already dug into the multi-platform setup a bit.

Initially I didn't add the arm64 build to the github actions, as the docker-compose file forced the paltform to be amd64 (https://github.com/linkwarden/linkwarden/commit/543dfd156c0462800723983e0f471fc19043ea57)

I'm checking today, if I can build it on m1 and force it to use arm64, if that works I'll create a pull request to enable the corresponding flags in the github actions

**Comment by daniel31x13** [comment]
It’s working now, thanks.
