### ISSUE TITLE
Enhancements for Public Collections

### ISSUE THREAD

**Issue by ItsNoted** [linkwarden/linkwarden#185]
Sharing content with the public is fantastic, but it'd be even better if viewers could download PDF files too. Plus, when dealing with larger collections, the current list view and design might feel a bit clunky. Having a grid view option would be a nice addition.

And speaking of improvements, it'd be really helpful to include a search feature for public collections. Additionally, having an offline web archive that functions like SingleFile and Shiori would be a great addition.

Having all these features available for public collections would make this tool absolutely perfect.

**Comment by daniel31x13** [comment]
This was already implemented in [v2.3.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.3.0), forgot to close this issue
