### ISSUE TITLE
FEATURE REQUEST: support for oauth

### ISSUE THREAD

**Issue by mvivaldi** [linkwarden/linkwarden#193]
I am submitting a request to incorporate OAuth support, a feature that I believe would greatly benefit organizations. Linkwarden proves to be exceptionally useful in team settings. However, without the option of Single Sign-On (SSO) and OAuth support, the prospect of recreating all our users within Linkwarden becomes a significant hurdle, potentially discouraging its adoption altogether.

Thank you

**Comment by CatoTheDuck** [comment]
+1

Would be great!

**Comment by daniel31x13** [comment]
Thanks for the suggestion, added to todo.

To serve a broader audience, it'll probably be a _"Sign in with Google"_ option.

**Comment by CallMeTerdFerguson** [comment]
Want to second @mvivaldi's request, please expose the ability to use a custom OAuth provider, not just hardcoded to Google. Lots of self-hosters use self-hosted OAuth solutions like Authentik. NextAuth supports it along-side more well known providers like Google.

**Comment by daniel31x13** [comment]
So is Authentik the most used OAuth solution? For anybody else interested in OAuth, let me know if you guys think there is a better OAuth provider out there.

**Comment by CallMeTerdFerguson** [comment]
[Authentik ](https://goauthentik.io/) is a hostable solution for providing auth (via lots of avenues, not just OAuth) from a single common interface. But the nice thing here is if you provide hooks to the custom OAuth capabilities the NextAuth, just about any OAuth provider could be configured to work, not just Authentik.

**Comment by joestump** [comment]
Authentik, Authelia, and Zitadel are the popular ones in the self-hosted community AFAICS. +1 for having a genetic OAuth2/OIDC option.

**Comment by daniel31x13** [comment]
Added Keycloak integration in [v2.3.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.3.0).

**Comment by samip5** [comment]
> Added Keycloak integration in [v2.3.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.3.0).

I'm sorry to say that due to the paths Keycloack uses, it's not very easy to use that for non-Keycloack so I think it would be best to have a generic OpenID Connect support, with the ability to fully customise the URLs.

**Comment by DirgoSalga** [comment]
@mvivaldi what Launch URL did you use on Authentik?

**Comment by daniel31x13** [comment]
Added in [v2.4.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.0).

**Comment by dlford** [comment]
@daniel31x13 any chance we can get Authelia added?

**Comment by Fede-26** [comment]
Any chance to get custom OICD or at least Pocket-ID?
