### ISSUE TITLE
Local archive and mode "View Readable" for links

### ISSUE THREAD

**Issue by Cousclou** [linkwarden/linkwarden#205]
**Is your feature request related to a problem? Please describe.**

I think it's a good idea to have a screenshot of the page and a PDF format in case you need it. However, I don't think it's very practical or user-friendly. An additional approach would be welcome

**Describe the solution you'd like**
I am currently using Shiori in collaboration, and it has two functions that I consider indispensable for a good link manager.

Since it creates a local archive, we are not required to leave the site to view the content.

It also offers a reading mode that is quite valuable for quick information retrieval.

example : https://zpl.cous.re/u/Y4DmE.gif

I think that would be a highly appreciated addition.

In any case, I will closely follow this project. 😁

**Comment by daniel31x13** [comment]
This feature is added in [v2.0.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.0.0).
