### ISSUE TITLE
Display collection colour on collections page

### ISSUE THREAD

**Issue by SoCuul** [linkwarden/linkwarden#209]
**Is your feature request related to a problem? Please describe.**
It's hard to tell the difference between two similar collections on the "all collections" page, as the cards do not show the selected folder colour.

**Describe the solution you'd like**
The coloured folder icon could be shown on the card, or the background of the card could be tinted the selected colour

**Comment by daniel31x13** [comment]
Will definitely implement this, thanks for this awesome idea!

**Comment by daniel31x13** [comment]
I like it :)

![Screenshot 2023-10-09 at 8 36 39 AM](https://github.com/linkwarden/linkwarden/assets/93432314/37b1eb96-7078-4515-9039-0f2184a69925)

**Comment by SoCuul** [comment]
> I like it :)
> 
> 
> 
> The docker image should be ready in a couple of minutes...
> 
> 
> 
> ![Screenshot 2023-10-09 at 8 36 39 AM](https://github.com/linkwarden/linkwarden/assets/93432314/37b1eb96-7078-4515-9039-0f2184a69925)
> 
> 

Wow, that looks great!
