### ISSUE TITLE
[Feature Request] Authentication

### ISSUE THREAD

**Issue by abonforti** [linkwarden/linkwarden#21]
Hi,
altough it would be possible to run this behind some sort of external authentication provider (.htaccess/authelia/similar), it would be good to have some sort of privacy/login method like many services have.
Like I can choose if sharing the links in a public way or to require a password to unlock the dashboard.

Have you considered anything like this? I am actually considering about deploying this in my self-hosted fleet, but would like to know if anyghing like that might be implemented :)

**Comment by Daniel31x13** [comment]
Hello,
Sorry for late response.
I'm planning to rebuild this project from ground up sooner or later.
Authentication is one of the main features of the next version...

**Comment by toxinliquid** [comment]
any update on this , this is awesome project but without login its unusable

**Comment by Daniel31x13** [comment]
Hi @toxinliquid, thanks for following up. I'm currently in the middle of rebuilding this project from ground up. You can follow the progress from the [ver-3](https://github.com/Daniel31x13/link-warden/tree/ver-3) branch. Thank you for your patience and feedback!

**Comment by toxinliquid** [comment]
> Hi @toxinliquid, thanks for following up. I'm currently in the middle of rebuilding this project from ground up. You can follow the progress from the [ver-3](https://github.com/Daniel31x13/link-warden/tree/ver-3) branch. Thank you for your patience and feedback!

maybe some additional features to look into? 
add 2 different type of users 
a user who can only view links
and a user for adding links 
this is good for a group of people in for example agriculture who share links among each other 
thanks

**Comment by Daniel31x13** [comment]
Collaboration mode! That's indeed one of the main features of the new version which is implemented halfway. 👍
