### ISSUE TITLE
Disable/tweak archiving functionality

### ISSUE THREAD

**Issue by SoCuul** [linkwarden/linkwarden#215]
**Is your feature request related to a problem? Please describe.**
Currently, when a link is added, the page contents are saved as an image and a pdf file.

**Describe the solution you'd like**
It would be great to have a toggle in the settings to either enable:
- Full Archival (Image + PDF)
- PDF Archival
- Image Archival
- No Archival

This is especially important for when I'm trying to run linkwarden on a machine which has very limited storage.

**Comment by daniel31x13** [comment]
Added this feature in [v1.2.0](https://github.com/linkwarden/linkwarden/releases/tag/v1.2.0).

**Comment by SoCuul** [comment]
> Added this feature in [v1.2.0](https://github.com/linkwarden/linkwarden/releases/tag/v1.2.0).

Your guy's development cycle is genuinely insane! I seriously can't believe how amazing you guys are at developing this app haha
