### ISSUE TITLE
Administration page

### ISSUE THREAD

**Issue by julienM77** [linkwarden/linkwarden#217]
Have you planned to implement an administration page to manage users, the site name, the logo (favicon), perhaps an overload of the site theme etc?

**Comment by daniel31x13** [comment]
I believe managing the users is doable by just using something like Supabase as the database.
For the website name/logo, not currently.

**Comment by jcolinger3** [comment]
Thank you.  Was wondering about this as well.

**Comment by PaulMcF1987** [comment]
I like the idea of this.
On a public site, sign up pages etc are fine
But I am hosing the app on docker and I am hosting it for my benefit and also friends and family who what to have an account.
I have a number of other containers which dont allow a random sign up but instead, I need to invite them to join. I can also suspend/delete them from the admin panel.

Is the invite to sign up and user management being considered under this topic?

**Comment by ados8** [comment]
Just installed Linkwarden and this was the first thing I looked for.
Providing my apps to family is only possible if I can manage the accounts.
Looking forward to seeing these features implemented.

**Comment by theAkito** [comment]
Does this mean, there is, as of now, no real Admin user?
Usually, the first user created is the Admin user or it can likewise be set up via environment variables.

**Comment by daniel31x13** [comment]
Added in [v2.6.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.6.0).
