### ISSUE TITLE
Feature request: Buttons for re-archive / update archive

### ISSUE THREAD

**Issue by lo48576** [linkwarden/linkwarden#226]
**Is your feature request related to a problem? Please describe.**

Archiving a webpage can fail for some reasons, or archives can be outdated if the web page is updated, and even in such cases users cannot invoke this function again.

"Some reasons" archiving fails for might be flaky internet connection on the server side or incorrect set up of the server...
In my case, I haven't executed `npx playwright install`. And when I noticed it is necessary, I already had dozens of links and don't want to register and tag them again.

**Describe the solution you'd like**

I'd like the saved link cards to have "re-archive" or "update archive" buttons (to re-create screenshots and PDF captures).

**Describe alternatives you've considered**

Add already-existing links again as new links, and then remove old ones.
This works for small number of links, but very frustrating for large number of links.
Additionally, I think I don't have means to enumerate "links with no PDF and/or screenshots", so it would be hard to find which links to recreate.

**Additional context**

It seems that [Document for Installation](https://docs.linkwarden.app/self-hosting/installation#2-install-the-necessary-dependancies) should have `npx playwright install` (not only install-deps) somewhere, but I'm not familiar to these frameworks and middlewares so I'm not sure it is my mistake at somewhere else or not.

**Comment by derpcfreak** [comment]
Maybe you could implement (at least for the docker version) an option so that  one can use

```
docker exec <containerid-of-linkwarden-container> listarchive  [-all | id ]
docker exec <containerid-of-linkwarden-container> rearchive [archives|screenshots|pdfs]  [-all | id ]
```
or similar. Could be implemented with 2 small scripts `listarchive` and `rearchive` which do whatever is necessary
inside the container to `listarchive`  or `rearchive` on demand.

**Comment by daniel31x13** [comment]
This feature will be available in the next release...

**Comment by daniel31x13** [comment]
This feature is added in [v2.0.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.0.0).
