### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by Technosoft2000** [linkwarden/linkwarden#227]
**Describe the bug**
Adding the link https://phauer.com/2016/testing-restful-services-java-best-practices/ doesn't work completely.

**To Reproduce**
1. Press **New Link**.
2. Insert at **Address (URL)** the link `https://phauer.com/2016/testing-restful-services-java-best-practices/`.
3. Select a **Collection** e.g. `Development`.
4. Press the **+ Add** button.
5. Go to the **Links** page and click on the added link.
6. The error message `Application error: a client-side exception has occurred (see the browser console for more information).` appears.

**Expected behavior**
Like at the other links, a pop-up should come up and show the details :).

**Screenshots**

In the overview I can see the added link:

<img width="435" alt="image" src="https://github.com/linkwarden/linkwarden/assets/1690853/348c09ea-dde3-4ac1-ba17-45f9bd13669a">

After a click on it I get the following:

<img width="518" alt="image" src="https://github.com/linkwarden/linkwarden/assets/1690853/a978ab29-4b84-4468-b226-d4121a10d672">

Here the Google Chrome Dev Tools Console:

<img width="494" alt="image" src="https://github.com/linkwarden/linkwarden/assets/1690853/11985498-9869-4bfa-bebb-94cbc1102de6">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 117.0.5938.152 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 13
 - Browser: Google Chrome
 - Version: 117.0.5938.153

**Additional context**
Issue happens on Desktop and on Smartphone.

**Comment by Technosoft2000** [comment]
The same issue happens with https://thenewstack.io/how-good-is-your-code-review-process/ too.

**Comment by daniel31x13** [comment]
Hello @Technosoft2000,
Thank you for pointing out this bug, I just updated the code right now and this will be fixed in the next release.

**Comment by Technosoft2000** [comment]
Hi @daniel31x13,
I thank you too for this nice project and appreciate that you have already investigated so much time in it :D

**Comment by daniel31x13** [comment]
You're welcome!

**Comment by daniel31x13** [comment]
Fixed in [v1.2.0](https://github.com/linkwarden/linkwarden/releases/tag/v1.2.0).
