### ISSUE TITLE
Import of bookmarks via an external HTML file doesn't generate Screenshot & PDF

### ISSUE THREAD

**Issue by Technosoft2000** [linkwarden/linkwarden#228]
**Describe the bug**
Import of bookmarks via an external HTML file doesn't generate Screenshot & PDF.
No matter how long I wait, no screenshots or PDF files will be generated 😅.
No possibility exists to regenerate for a link the corresponding Screenshot & PDF. 

**To Reproduce**
1. Go to your profile and select **Settings**
2. Select the tab/page **Privacy Settings**
3. Under **Import Data** press the **Import From** button and select **Bookmarks HTML file ...**
4. Select and import a bookmark HTML file - here is an example file in a ZIP archive: [Raspberry_Pi.zip](https://github.com/linkwarden/linkwarden/files/12910094/Raspberry_Pi.zip)
5. Select the **Export** collection which was created through the import
6. Select the first link - e.g. *GitHub - Pi-Hole/Pi-Hole: A Black Hole For Internet Advertisements* of the provided file
7. Click on the "Show" button of **Screenshot** which opens a new tab with the resource URL and an error

The error message is:

> ## File not found
>
> ### It is possible that the file you're looking for either doesn't exist or hasn't been created yet.
>
> **Some possible reasons are**:
> * You are trying to access a file too early, before it has been fully archived. If that's the case, refreshing the page might resolve the issue.
> * The file doesn't exist either because it encountered an error while being archived, or it simply doesn't exist.

**Expected behavior**
Screenshot & PDF should be generated for imported links too.

**Screenshots**

Successful import of the provided `Raspberry_Pi.html` bookmark file:

![image](https://github.com/linkwarden/linkwarden/assets/1690853/eeed4b49-b74b-48c5-a4c1-3dd1bce1ed03)

A new collection `Export` appears:

![image](https://github.com/linkwarden/linkwarden/assets/1690853/419c2d0c-4d10-41ad-9804-ab9512be3732)

Click on a newly imported link to show details:

<img width="780" alt="image" src="https://github.com/linkwarden/linkwarden/assets/1690853/50c50122-03e5-4dad-8cff-4b4010009fe1">

A click on the "Show" button of **Screenshot** which opens a new tab with the resource URL and an error:

<img width="129" alt="image" src="https://github.com/linkwarden/linkwarden/assets/1690853/bb6ebc8b-4734-4516-b9ca-e4a1f83bb6e3">

![image](https://github.com/linkwarden/linkwarden/assets/1690853/a8b6181d-bf2a-47ba-982f-a6a33f192f0b)

**Desktop (please complete the following information)**:

- OS: Windows 11
- Browser: Google Chrome
- Version: 117.0.5938.152 (Official Build) (64-bit)

**Smartphone (please complete the following information)**:

- Device: Google Pixel 6
- OS: Android 13
- Browser: Google Chrome
- Version: 117.0.5938.153

**Additional context**

Issue happens on Desktop and on Smartphone.

**Comment by daniel31x13** [comment]
As of now, imported bookmarks won't be archived. Only new one's will be archived.

**Comment by Technosoft2000** [comment]
Would be great to have this implemented. A background process could go through all links from the import and archive them and if a link is not accessible anymore some icon should appear that the link is broken.

May be for the beginning the **Archived Formats** should be greyed-out & deactivated so that a user doesn't click on it.
And I think some kind of icon should appear on imported link to easily see the difference - e.g. https://fontawesome.com/icons/circle-exclamation?f=classic&s=solid

**Comment by daniel31x13** [comment]
To run a background process to go though all the Links, we need to run another server alongside this NextJS app, which needs some code refactoring... I was more leaning towards another solution that was pointed out in issue #226.
And yes, I will be implementing the archive indicators soon.

**Comment by Nillth** [comment]
in the meantime as a workaround you can have a look at the process I outlined here: https://github.com/linkwarden/linkwarden/issues/306#issuecomment-1827667724

**Comment by daniel31x13** [comment]
Added in [v2.4.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.0).
