### ISSUE TITLE
Redirect when i logout

### ISSUE THREAD

**Issue by maxXx1** [linkwarden/linkwarden#233]
Hi,

i have Linkwarden on Docker (on Synology NAS). When i logout from accont, page redirect me to `http://localhost:3000/`.

**Comment by daniel31x13** [comment]
Hello,

This is most likely because you set the `NEXTAUTH_URL` environment variable incorrectly.

It should be the same as the domain name you are hosting Linkwarden on.

**Comment by modem7** [comment]
> Hello,
> 
> This is most likely because you set the `NEXTAUTH_URL` environment variable incorrectly.
> 
> It should be the same as the domain name you are hosting Linkwarden on.

Had the same issue. Can confirm this resolves.

Thanks!

**Comment by maxXx1** [comment]
I missed it. I can confirm changing this value will fix the problem. Thank u.
