### ISSUE TITLE
[Feature Request] Nested collections

### ISSUE THREAD

**Issue by OncePunchedMan** [linkwarden/linkwarden#239]
It would be nice to have nested collections. 

This is from raindrop:
![image](https://github.com/linkwarden/linkwarden/assets/64155117/482e4d51-a160-4024-90a3-407128858fd1)

**Comment by ser** [comment]
I think it's the most important feature request from currently enlisted in issues.

**Comment by artfer** [comment]
> This is literally the only missing feature that prevents me from switching to Linkwarden

Same for me

**Comment by daniel31x13** [comment]
Nested collections will be released soon.

**Comment by mary-loulou** [comment]
Is there a difference between nested collections and "[subfolders](https://github.com/linkwarden/linkwarden/issues/424)"?

**Comment by daniel31x13** [comment]
@mary-loulou yeah they're the same

**Comment by mary-loulou** [comment]
Shouldn't the two threads be merged then?

**Comment by daniel31x13** [comment]
This feature has been released in [v2.5.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.0).

And @mary-loulou yes, just closed the other one.

**Comment by Alexnoj** [comment]
> This feature has been released in [v2.5.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.0).
> 
> And [@mary-loulou](https://github.com/mary-loulou) yes, just closed the other one.

Thanks for listening the community!
