### ISSUE TITLE
Feature Request: Show which collections are shared

### ISSUE THREAD

**Issue by modem7** [linkwarden/linkwarden#247]
Within the collections section, it would be useful to have an indicator to show which collections are shared publicly. 

This would allow for an easy overview, especially with numerous collections to see which are shared and which are not, which would reduce any potential mistakes from users having shared erroneously/be able to quickly see any that are.

**Comment by daniel31x13** [comment]
This is pretty easy to implement, the "hardest" part is probably going to be the design and UX.
Thanks for the suggestion!

**Comment by modem7** [comment]
I'm by no means a UX designer, but what I had envisioned was a small icon next to the number of links icon:

![image](https://github.com/linkwarden/linkwarden/assets/4349962/44c33a3d-581b-41d3-982e-04d28f5fe179)

That way it's kept nice and minimalistic, with enough of a change that it's obvious to the user.

But as I said, I have no idea about UX, I'm a dirty backend network and scripting guy :D

**Comment by Dhyfer1** [comment]
<summary><b>A bit of a "history"</b></summary>

Tend jaja did night shah us and
