### ISSUE TITLE
Linkwarden Cloud does not save PDF in paid version

### ISSUE THREAD

**Issue by kamenkadmitry** [linkwarden/linkwarden#257]
Browser version. In any browser, when you click on the cloud after which the PDF should download, nothing happens. The file is only downloaded. Which contains technical information. File as an attachment.

This is the content of the file

{"country": "US", "region": "California", "city": "San Francisco", "proxy": "2", "proxy_type": "SES"}

The extension has been renamed because without the extension GitHub does not allow you to download the file. Initially, the file has no extension at all.

[3RiYg379.txt](https://github.com/linkwarden/linkwarden/files/13077778/3RiYg379.txt)

**Comment by daniel31x13** [comment]
Strange, can you share the URL (if it's not sensitive)?
It's probably the target website that's preventing the link from being archived.

**Comment by kamenkadmitry** [comment]
The problem is that all the links that I added do not save or do not give me the pdf file

**Comment by kamenkadmitry** [comment]
https://cloud.linkwarden.app/api/archives/83/229.pdf
https://cloud.linkwarden.app/api/archives/83/198.pdf
https://cloud.linkwarden.app/api/archives/79/239.pdf

Example links that don't work. But not a single link works

**Comment by daniel31x13** [comment]
Oh you mean the links that you imported?

**Comment by daniel31x13** [comment]
As of now, the imported links will not be archived. Only the new links will.

But there is a new upcoming feature that gives the user the ability to re-archive links, that way you will be able to archive them as well.

Let me know if you had any other questions.
