### ISSUE TITLE
linkwarden database

### ISSUE THREAD

**Issue by pocelka** [linkwarden/linkwarden#261]
**Is your question related to a problem or code? Please describe.**
I'm thinking about trying your application in a way of docker image. However I've little bit hard to understand in which database will be created a data. The thing is that in my setup I'm using just one postgres database for more containers. I know I should be probably using more postgres databases, but if I would use one for each container I would soon out of resources. For service "separation" is perfectly fine for me to have one database (cluster) with multiple schemas/databases inside. 

Could you please clarify if linkwarden is creating database or if it inserts everything into "postgres" database (the one which is created by default)? If it is the default would it be possible to add an option to choose database name? i.e. for other containers I'm using for example:
![image](https://github.com/linkwarden/linkwarden/assets/20441822/9a111984-3055-4748-9d6f-18a1fdb177cd)
![image](https://github.com/linkwarden/linkwarden/assets/20441822/1002a2f5-2da0-4338-8f3c-f29eacde5f11)

**Comment by daniel31x13** [comment]
So if you're asking if Linkwarden creates a separate database or uses an existing one, the docker compose file creates a separate, isolated postgres database.

**Comment by pocelka** [comment]
If I understood you correctly; if I change `DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres` to `DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/docker_linkwarden` it should create during container spinup database `docker_linkwarden` where will be placed the data.

Is that correct?

**Comment by HDZC-E** [comment]
Yeah i was wondering too, where does Linkwarden store the database and if i can use an existing one instead.
