### ISSUE TITLE
Custom Icons for Collections & Links

### ISSUE THREAD

**Issue by anon79678** [linkwarden/linkwarden#264]
Hi,

I am a very visual person. I'd love to see custom icons for collections and links, especially since some links do not automatically grab an icon.

Allowing a user to upload a PNG or SVG would be awesome.

**Comment by SirHazza** [comment]
+1 
I also work very visually, so having icons especially for my collections would be a huge help.

Can recommend the following for icons:
[Tabler](https://github.com/tabler/tabler-icons), [Feather](https://github.com/feathericons/feather), [Heroicons](https://github.com/refactoringui/heroicons).

If those aren't suitable then a more broad set of options [here](https://freesets.vercel.app/icons).

**Comment by phampyk** [comment]
I'm absolutely behind this one!! I would love to choose the icons. 
I know of [iconify](https://icon-sets.iconify.design/) for a massive array of icons to choose from.

**Comment by Ge0rg3** [comment]
This feature would be huge, for me its actually the deciding factor between linkwarden and raindrop - both are very similar otherwise, but icons allow for much easier collection finding at a glance.

**Comment by daniel31x13** [comment]
Soon :)

**Comment by romu70** [comment]
Huge Icons has a great collection set, more than 28k icons.
Getting a life time license is not so expensive. We can even thinking of donations to acquire it 😉.

**Comment by beancaper** [comment]
Agreed re: allowing users to upload an image file! The blurry screenshot is just not visually appealing.

**Comment by daniel31x13** [comment]
[Done!](https://github.com/linkwarden/linkwarden/releases/tag/v2.8.0) :)
