### ISSUE TITLE
Clear icons instead blurred

### ISSUE THREAD

**Issue by Just4Link** [linkwarden/linkwarden#267]
Is it possible to get a option to set the icons to a clear visible look instead the blurry one?

greetings

**Comment by daniel31x13** [comment]
This will be implemented soon.

**Comment by daniel31x13** [comment]
Added in [v2.1.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.1.0).

**Comment by Just4Link** [comment]
Thank you for adding the option, but when i enable it, the icons disappear complete. When i switch back to blurred, they show up again.

**Comment by daniel31x13** [comment]
Added an extra setting in [v2.2.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.2.0).

**Comment by diskape** [comment]
Was this feature removed? I'm on 2.5.2 and cannot find it..
