### ISSUE TITLE
Build / Starting Linkwarden

### ISSUE THREAD

**Issue by Aetherinox** [linkwarden/linkwarden#268]
**Is your question related to a problem or code? Please describe.**
Problem: Cannot build, throws errors every time I attempt to execute
- `yarn build`
- `yarn start`

Attempting `Manual Installation` via [this guide](https://docs.linkwarden.app/self-hosting/installation#manual-installation).

<br />

---

<br />

**Describe what you've tried to solve this question**
Attempted to use different versions of Node, checked for other package updates, started instructions back from start.

<br />

---

<br />

**Include any code or screenshots (if applicable)**

Followed the instructions in the documentation to try a self-hosted instance.
Upon executing
```
yarn build
```
I receive the error

```shell
yarn run v1.22.19
$ next build
- info Loaded env from /home/aetherx/LinkWarden/.env

Failed to compile.

./pages/collections/index.tsx
157:41  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities

./pages/settings/delete.tsx
122:72  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
```

The command `yarn prisma migrate deploy` executes without any issues.
However, `yarn start` also throws errors

```
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /home/aetherx/LinkWarden/.env
Error: Could not find a production build in the '/home/aetherx/LinkWarden/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/home/aetherx/LinkWarden/node_modules/next/dist/server/next-server.js:348:23)
    at new Server (/home/aetherx/LinkWarden/node_modules/next/dist/server/base-server.js:153:29)
    at new NextNodeServer (/home/aetherx/LinkWarden/node_modules/next/dist/server/next-server.js:175:9)
    at NextServer.createServer (/home/aetherx/LinkWarden/node_modules/next/dist/server/next.js:179:24)
    at async /home/aetherx/LinkWarden/node_modules/next/dist/server/next.js:200:31
    at async NextServer.prepare (/home/aetherx/LinkWarden/node_modules/next/dist/server/next.js:161:24)
    at async Server.<anonymous> (/home/aetherx/LinkWarden/node_modules/next/dist/server/lib/render-server.js:136:17) {
  type: 'Error'
}

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

<br />

---

<br />

**Additional context**
- Yarn v1.22.19
- NodeJS v16.20.2 / v18
- Postgres v14.9
- Git v2.34.1
- NPM v10.2.1

**Comment by daniel31x13** [comment]
Oh this is because there are some major changes happening on the main branch for manual installation, for now the latest stable release is https://github.com/linkwarden/linkwarden/releases/tag/v1.2.5

Please download the source from there instead.

**Comment by Aetherinox** [comment]
Ah ok. I utilized the git command available in the docs. I'll download the release and try that out. Thanks

**Comment by Aetherinox** [comment]
Install works good.

I guess my only other question is that I installed the browser extension which allows me to add websites. But how do I view existing bookmarks to visit? Do I have to keep the self-hosted linkwarden website open and access the links from there?

**Comment by daniel31x13** [comment]
Yes, for now the browser extension can only add links, but we do plan on extending the functionalities.

**Comment by Aetherinox** [comment]
Nice. Can't wait. Appreciate the help. Thus far it has ran smooth.
