### ISSUE TITLE
Log out redirecting to localhost:3000

### ISSUE THREAD

**Issue by JKB0DY** [linkwarden/linkwarden#272]
Im working on a fresh install of debian 12 with a clean docker instalation and the only service is linkwarden. When signing out of a  account you get redirected to 'http://localhost:3000/' 

**To Reproduce**
1. Go to 'profile'
2. Click on 'logout'
4. See 'http://localhost:3000'

**Expected behavior**
i'd expect that the redirect would go to 'domain/login' or 'Ip:3000/login'

**Desktop (please complete the following information):**
 - OS: windows, linux
 - Browser: chrome, firefox

**Smartphone (please complete the following information):**
 - Device: samsung galaxy
 - OS: android 13
 - Browser: firefox

**Comment by imloic** [comment]
What is your `NEXTAUTH_URL` in .env? 
have you try to change it ?
