### ISSUE TITLE
Version number installed

### ISSUE THREAD

**Issue by mdlaat** [linkwarden/linkwarden#279]
Is there an easy way to get the version number that is installed, perhaps by making a web request?
I would like to run a script that detects if a newer version is available.
Thank you

**Comment by daniel31x13** [comment]
This will be implemented soon.

But other than that, since Linkwarden v2.0.0, we made an announcement banner which pops up when there's a new noticeable change.
The banner works by fetching the following url:
https://blog.linkwarden.app/latest-announcement.json

**Comment by daniel31x13** [comment]
Added in [v2.1.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.1.0).
