### ISSUE TITLE
Registration link still displayed while disabled

### ISSUE THREAD

**Issue by ro78** [linkwarden/linkwarden#280]
**Describe the bug**
According to the documentation, setting NEXT_PUBLIC_DISABLE_REGISTRATION=true in the .env conf allows to disable any new registration. Once defined and stack stopped & started again, I still see the registration link on the login page.

**To Reproduce**
1. Install linkwarden (self hosted)
2. Edit .env file and add NEXT_PUBLIC_DISABLE_REGISTRATION=true
3. Start the stack
4. Still have the registration link

**Expected behavior**
I think registration link should not be visible, and if accessed, should return a message saying registration is disabled.

**Screenshots**
![1](https://github.com/linkwarden/linkwarden/assets/3236640/8608804f-befe-4127-ade9-bab458318d0f)
![2](https://github.com/linkwarden/linkwarden/assets/3236640/3eef1775-593b-4830-9a7a-b29f0de9ca2d)

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Browser: Brave
 - Version: 1.60.110 (Chomium 119.0.6045.105)

**Smartphone (please complete the following information):**

**Comment by daniel31x13** [comment]
The registration endpoint is _fully_ protected and there's no way _anyone_ could register when `NEXT_PUBLIC_DISABLE_REGISTRATION` is set to `true`.

That's only a view-only page right now.
If you test it by filling the registration form and signing up, you'll notice it says "Registration is disabled." which means... well, registration is disabled.
