### ISSUE TITLE
Display version number in settings page

### ISSUE THREAD

**Issue by SoCuul** [linkwarden/linkwarden#282]
**Is your feature request related to a problem? Please describe.**
Currently, trying to figure out which version of linkwarden is actively being used requires either looking at the docker image or possibly api requests.

**Describe the solution you'd like**
It would be super nice to have the current version (maybe along with which deployment method was used) displayed in the corner of the settings menu, for example.

**Mockup**

<img width="1438" alt="mockup" src="https://github.com/linkwarden/linkwarden/assets/63339559/9b908c95-9fd1-4036-a82b-1eb027a9a8fe">

**Comment by m4teh** [comment]
Got done installing the app just now and popped in to Issues to see if somebody had mentioned the exact same thing.
Got some error during pulling that it couldn't find the ghcr.io/linkwarden/linkwarden:latest image and that it was pulling linkwarden/linkwarden instead, and then logging in was displayed with a banner saying v2 was out. Leading me to believe something was up. Couldn't even verify what version it was running.

**Comment by modem7** [comment]
Related to #279

**Comment by daniel31x13** [comment]
Added in https://github.com/linkwarden/linkwarden/releases/tag/v2.1.0
