### ISSUE TITLE
Allow for custom/no icons on saved links.

### ISSUE THREAD

**Issue by SoCuul** [linkwarden/linkwarden#283]
**Is your feature request related to a problem? Please describe.**
Whenever I try to recognize my links by their icon, the image provided is either very low quality and blurry or not related to the contents of the page. This makes sense, as the icon is generated from the page's favicon.

**Describe the solution you'd like**
It would be very nice to have an option to display no icon, along with providing your own icon (via image upload or url). Another cool feature could be an icon creator, with the colour picker and a list of material design icons.

**Comment by daniel31x13** [comment]
Added in [v2.1.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.1.0).

**Comment by SoCuul** [comment]
Would it be possible to upload your own icons in the future?

**Comment by daniel31x13** [comment]
Not really, for collections tho, maybe...

**Comment by SoCuul** [comment]
> Not really, for collections tho, maybe...

In that case, would you think about implementing a system to select a material design icon to represent a link? And the colour could just match the global theme colour.

**Comment by daniel31x13** [comment]
How do you think that would benefit individual users?
I feel like nobody would go through +1000 links and assign an icon to each.
And if they’re trying to find a specific link easily, they could just pin it.

**Comment by daniel31x13** [comment]
I feel that my tone was a bit harsh over here. But it was really a question for me, if it's really necessary I'll definitely implement this feature.

**Comment by SoCuul** [comment]
> I feel that my tone was a bit harsh over here. But it was really a question for me, if it's really necessary I'll definitely implement this feature.

No worries about the tone! But in response, I primarily recognize items by visual indicators. In this way, I'm able to instantly find which thing I need from a large list, without having to read over the title.

It really just allows another way to visually find notes, which personally I very much like.
