### ISSUE TITLE
Merge or Delete Duplicate Entries

### ISSUE THREAD

**Issue by jkubala4454** [linkwarden/linkwarden#286]
**Is your feature request related to a problem? Please describe.**
When importing bookmarks from different computers, the same bookmark is imported, but in a different collection and sometimes with a different tag.

**Describe the solution you'd like**
It would be awesome if there was a way to automatically search for and then merge the two entries, choosing what information to keep.

**Describe alternatives you've considered**
Searching for bookmarks manually and then manually deleting the unwanted one.  This is very time-consuming, and may miss some.

**Comment by GoodM4ven** [comment]
Yeah, I was surprised that duplicate links are allowed, even in the same collection!

**Comment by GoodM4ven** [comment]
[links.ts](./store/links.ts)
```
setLinks: async (data, isInitialCall) => {
  // ...
  set((state) => ({
    links: [...state.links, ...data].reduce((links, item) => {
      if (!links.some((link) => link.url === item.url)) {
        links.push(item);
      }
      return links;
    }, []),
  }));
},

// ...

addLink: async (body) => {
  const existingLink = useLinkStore.getState().links.find(link => link.url === body.url);
  if (existingLink) {
    // Handle the duplicate URL case...
  }

  // ...
},
```

**Comment by GoodM4ven** [comment]
So the link is still not a unique identifier! Is it because searching them is problematic or what? I just wonder **what the current issue is with regard to filtering them**, and therefore ensuring that there are no duplicates.

I believe that this feature is so essential and cannot be done without; especially within the same collection!

**Comment by GoodM4ven** [comment]
Thanks to the maintainers, the "prevent duplicate links" feature is now in action! And it does prevent even if they're put in different collections, which in intuitive, in my opinion.

This issue can be closed now, I believe. Don't you think, @jkubala4454 ?

**Comment by jkubala4454** [comment]
Awesome! Thank you

**Comment by itguy327** [comment]
If I export my links and the reimport, does it stopped duplicate creation on import?

**Comment by petersandor** [comment]
@itguy327 reimport still creates duplicates (tested in v2.5.2).

**Comment by jhol** [comment]
Jut got bitten by this. A second import still causes duplication. Is there a way I can run some kind of script to clear out the duplicates?
