### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by bestruirui** [linkwarden/linkwarden#288]
**Is your feature request related to a problem? Please describe.**
Multi-language support

**Describe the solution you'd like**
i18n?

**Describe alternatives you've considered**

**Additional context**

**Comment by huhexian** [comment]
I would like to take part in Chinese translation.

**Comment by h3n3b0sch** [comment]
Is this a thing allready?

**Comment by daniel31x13** [comment]
Related to #216.
