### ISSUE TITLE
Rearchive functionality for multiple links at once

### ISSUE THREAD

**Issue by hawithme** [linkwarden/linkwarden#290]
**Is your feature request related to a problem? Please describe.**
I am triying to import from a browser but now even with the new feature of v2 i have to refresh formats for every link manually.

**Describe the solution you'd like**
A way to select multiples links and then refresh formats. It can be by collection too. Maybe always automatically when impoting.

**Describe alternatives you've considered**
Manually refresh every link.

**Additional context**

**Comment by Nillth** [comment]
in the meantime as a workaround you can have a look at the process I outlined here: https://github.com/linkwarden/linkwarden/issues/306#issuecomment-1827667724

**Comment by daniel31x13** [comment]
Added an archive background worker in [v2.4.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.0).
