### ISSUE TITLE
Full rebuild of your project.

### ISSUE THREAD

**Issue by KalyaSc** [linkwarden/linkwarden#30]
I know this isn't the right place to do it, but I just wanna **thank you** for your project and happy to hear you're rebuilding it !
The GUI could be a bit more shiny, but who am I to judge? I'm incapable to do even 5% of what you did, so... screw me !

Having a self-hosted book marker and PDF archive is probably the best feature ! I really don't like depending on WayBack to store it on a third party.

So keep it strong, good luck and thank you :)

**Comment by Daniel31x13** [comment]
Thank you so much for your kind words and support! I truly appreciate your gratitude for the project and I'm glad to hear that you find the archive feature valuable.

P.S. here's a small "sneak peek"; Hope you'd like it!

![Screenshot1](https://github.com/linkwarden/linkwarden/assets/93432314/b8ff39cb-2683-4437-87c6-d8949eb64edd)
![Screenshot2](https://github.com/linkwarden/linkwarden/assets/93432314/293e146b-4170-406c-8980-cd6fef409b56)
