### ISSUE TITLE
Confirmation dialog for delete button in links

### ISSUE THREAD

**Issue by kgnfth** [linkwarden/linkwarden#313]
**Is your feature request related to a problem? Please describe.**
I accidentally clicked on the delete icon when i actually wanted to click on the preserve icon, and it just got deleted

**Describe the solution you'd like**
When clicking on delete icon, ask the user for a confirmation before deleting.
Something like this 
<img width="292" alt="image" src="https://github.com/linkwarden/linkwarden/assets/73314940/4218519d-e826-4e9e-a585-42a7cfeb2ba5">

**Comment by daniel31x13** [comment]
Added in [v2.4.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.0)
