### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by edersong** [linkwarden/linkwarden#323]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A PWA support to be able to install it on a Android phone like an App and availability to send links to Linkwarden directly from Share menu

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by itguy327** [comment]
Love this project. Thank you for your work.

Definitely agree with this. I bookmark a shortcut on my home screen and then just copy link from browser and then go to my shortcut.

Just would love a shorter route

**Comment by BadCo-NZ** [comment]
Yup, PWA would be a great feature. It is how I access most of my selfhosted services and I assume it would be easier to develop then an app as well?

**Comment by daniel31x13** [comment]
This feature has been released in [v2.5.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.0).

**Comment by jlssmt** [comment]
PWA is possible now. But it's not possible to share a link via Android share menu to PWA.

**Comment by deafmute1** [comment]
Could we maybe have support for[web share target](https://developer.chrome.com/docs/capabilities/web-apis/web-share-target)? Seems like very little effort and would provide share menu access via the PWA.

**Comment by alexkutsan** [comment]
I am also waiting for this feature of ability to add links from my Android phone with "share".

**Comment by phunky-tech** [comment]
> Could we maybe have support for[web share target](https://developer.chrome.com/docs/capabilities/web-apis/web-share-target)? Seems like low effort and would provide share menu access via the PWA. At the moment, it does not seem to work.

I'd like to tackle this issue, as it's the main thing stopping me from using the project more. Guide says to wait for confirmation before beginning, so I will wait for the moment.

**Comment by daniel31x13** [comment]
@phunky-tech sure go for it!

**Comment by phunky-tech** [comment]
@daniel31x13 PR submitted! #612

**Comment by daniel31x13** [comment]
Closing this issue since it's is already implemented.

**Comment by jlssmt** [comment]
> Closing this issue since it's is already implemented.

So should we create a new issue for the android share menu?
This is preventing me so hard from using linkwarden 😅😭

**Comment by daniel31x13** [comment]
@jlssmt there is one already: #206

It should be easy for someone who has some experience in android pwa development, I just haven’t got to it yet since I don’t own any android devices, yet.

**Comment by BadCo-NZ** [comment]
@jlssmt check out HTTP Shortcuts on F-Droid, it fills the hole for sharing to PWAs. I don't use it with LinkedIn specifically, but another PWA app.

https://github.com/Waboodoo/HTTP-Shortcuts

**Comment by jlssmt** [comment]
@BadCo-NZ
Thanks for the idea. But I think the API doesn't support to push a new link to linkwarden.
https://docs.linkwarden.app/api/overview

**Comment by BadCo-NZ** [comment]
> @BadCo-NZ thanks. it's working.
> 
> To whom it may concern, the shortcut settings: POST https://linkwarden.domain.de/api/v1/links
> 
> Create a variable that can be filled from share menu.
> 
> BODY: application/json
> 
> ```json
> {
>   "url": "{share variable here}"
>   "tags": []
> }
> ```
> 
> Authentication: Generate Token in linkwarden and use here as Bearer Token.

Nice one!

**Comment by Danie10** [comment]
This looks very promising in the interim as I really need it to work from Android. Can someone assist with the syntax etc a bit further as I got a few errors?

I'm assuming there must be a comma delimiter in the json code as this only worked after I added it?
```
{
  "url": "{share variable here}",
  "tags": []
}
```
After that it seemed to work as it posed a new link but the URL did not come through. So I'm thinking this was an issue with my variable? My share variable is inserted where the {share variable here} appears above.

![Variable edit](https://github.com/user-attachments/assets/d8400a91-8d70-4da3-9b33-b3a4a219088f)

**Comment by jlssmt** [comment]
![Screenshot_20240815-203948](https://github.com/user-attachments/assets/b8f5f75f-be14-4746-bc3c-2d2800457acb)

![Screenshot_20240815-204023](https://github.com/user-attachments/assets/5a1874c1-6e0f-4053-9742-00b3ae02d75b)

**Comment by Danie10** [comment]
@jlssmt thanks for your quick response. OK made the change in the variable and everything seems to be identical. When I do the share now I get an error:

Linkwarden failed with status code 400 (bad request)
{"response":"Please enter a valid address for the link. (It should start with http/https)"}

I'm sure that is the variable (not the post to Linkwarden). I have the variable as text only from share. I'm sharing a news item with Android share and choosing the named shortcut that I saved to the home screen.

**Comment by Danie10** [comment]
Yep something to do with the variable. I hardcoded the link into the request body, and that posts fine through to Linkwarden. So somehow the Share To is not passing the link properly or some setting is not quite right. I found an archive of another post about it at [here](https://web.archive.org/web/20240510054126/https://cool-as-heck.blog/post/2024-01-21-ehgnmqz1) but the only difference is ticking on the JSON encode option for the variable. Tried that and still no difference.

**Comment by Danie10** [comment]
OK working perfectly now...  In the app under troubleshooting, I deleted cookies. Thanks once again @jlssmt

**Comment by Dacid99** [comment]
Hey guys,
over the last few weeks I have developed an android app companion for Linkwarden that allows uploading links via the share context menu.
It's on [f-droid](https://f-droid.org/en/packages/com.sbv.linkdroid/) as of today.
I hope this helps you using Linkwarden on android.

If you have feedback please let me know in the [repository](https://github.com/Dacid99/LinkDroid-for-Linkwarden) (and leave a star if you like)!

**Comment by itguy327** [comment]
Thank you
Best Regards,
Jason Quackenbush
