### ISSUE TITLE
env BUCKET_NAME is required when using s3 archive

### ISSUE THREAD

**Issue by ycwu314** [linkwarden/linkwarden#333]
**Describe the bug**

Install with docker compose, with s3 setting in .env config :
https://github.com/linkwarden/linkwarden/blob/0f40578ca990f5a45f0298945619becb33037e6d/.env.sample

```
# AWS S3 Settings
SPACES_KEY=xxx
SPACES_SECRET=xxx
SPACES_ENDPOINT=xxx
SPACES_BUCKET_NAME=linkwarden
SPACES_REGION=xxx
SPACES_FORCE_PATH_STYLE=
```

Then add a link in the web, it failed.

**To Reproduce**

1. Config s3 in .env
2. docker-compose up
3. add a link in the web
4. failed to archive

**Expected behavior**

It should archive successfully in the s3 bucket.

**Screenshots**

Here is the log from docker-compose
```
linkwarden_1  | Error Error: No value provided for input HTTP label: Bucket.
linkwarden_1  |     at resolvedPath (/data/node_modules/@smithy/smithy-client/dist-cjs/resolve-path.js:19:15)
linkwarden_1  |     at se_PutObjectCommand (/data/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:2452:53)
linkwarden_1  |     at runNextTicks (node:internal/process/task_queues:60:5)
linkwarden_1  |     at process.processImmediate (node:internal/timers:447:9)
linkwarden_1  |     at async /data/node_modules/@smithy/middleware-serde/dist-cjs/serializerMiddleware.js:12:21
```

Looks like related to 
https://github.com/linkwarden/linkwarden/blob/0f40578ca990f5a45f0298945619becb33037e6d/lib/api/migration/migrateToV2.js#L29

![image](https://github.com/linkwarden/linkwarden/assets/15355020/bbfbf29c-6785-491e-a655-fd7760fe83e6)

**How to fix

1. Add BUCKET_NAME in `.env` file solves the problem (which is NOT specified in the sample file)

2. It would be nice to change to SPACES_BUCKET_NAME as well in 
 https://github.com/linkwarden/linkwarden/blob/0f40578ca990f5a45f0298945619becb33037e6d/lib/api/migration/migrateToV2.js#L29

**Desktop (please complete the following information):**
Ubuntu 20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daniel31x13** [comment]
Thanks for pointing this out, I'll update this.
