### ISSUE TITLE
Import from LinkAce

### ISSUE THREAD

**Issue by alexdelprete** [linkwarden/linkwarden#335]
Following up on Daniel's [comment](https://github.com/linkwarden/linkwarden/issues/99#issuecomment-1762886906) in #99.

I really like this project, but I have used LinkAce for 2y and in order to try it I'd really need to migrate data from it.

I exported data as html, but CSV format is available too, if needed.

[LinkAce_export.zip](https://github.com/linkwarden/linkwarden/files/13624087/LinkAce_export.zip)

**Comment by bryanhunwardsen** [comment]
This is why LinkAce import does not work: https://github.com/linkwarden/linkwarden/issues/301#issuecomment-1842730385

**Comment by alexdelprete** [comment]
Thank you Bryan, but I prefer to wait for a proper import. I'll continue with LinkAce until I will be able to properly migrate with all metadata.

**Comment by alexdelprete** [comment]
Hi @daniel31x13,

is this something that is on the radar? I understand it's not a priority, but I'd like to know if there's any hope to be able to import all my current bookmarks. Otherwise I'll move on and look for alternatives.

Please let me know, thank you.

**Comment by daniel31x13** [comment]
@alexdelprete Hey sorry yeah it's on the radar.

This is linked to #271 and one requirement for a proper import is the support for nested collections, which is on the way (#239).

Anyway that being said, this issue be fixed in the upcoming (or next) release.

**Comment by alexdelprete** [comment]
> this issue be fixed in the upcoming (or next) release.

This is AWESOME! I almost lost hope. :)

If needed, for testing, I attached my LinkAce export in OP. 

Thank you so much Daniel.

**Comment by fethomm** [comment]
I am also waiting for this feature, already subscribed the other day. Keep up the good work!

**Comment by daniel31x13** [comment]
getting to this, and I already found the bug...

**Comment by mztiq** [comment]
Any updates or ETA on this?

**Comment by mztiq** [comment]
Doesn't work for me sadly

**Comment by alexdelprete** [comment]
> @mztiq yes this is already fixed. It's strange that you say that it's not fixed for you yet, are you sure you're on the latest version?

I confirm it's working for me. Imported 170 bookmarks exported from Linkace. Now the server is at 100% cpu since the start of the import, I guess it's downloading the images of the links etc. I'll let it work for a while, hoping there's no issues. 

Thanks a lot @daniel31x13, I can finally switch to Linkwarden. :)

**Comment by daniel31x13** [comment]
@alexdelprete I was hoping so since I used the exact file you uploaded as a reference.

**Comment by alexdelprete** [comment]
> @alexdelprete I was hoping so since I used the exact file you uploaded as a reference.

So I'm not a good test-case. :)

Am I correct that linkwarden is now downloading things and updating the db with all screenshots, etc.? The server fans are still spinning...I don't know how long it will take...can I check anywhere what it's doing?

**Comment by mztiq** [comment]
> @mztiq yes this is already fixed. It's strange that you say that it's not fixed for you yet, are you sure you're on the latest version?

My `docker-compose.yml` was still using `image: ghcr.io/linkwarden/linkwarden:main` instead of `image: ghcr.io/linkwarden/linkwarden:latest` for whatever reason.

Sorry for the confusion and **yes, it's working**, thanks for that! :-)

**Comment by daniel31x13** [comment]
@alexdelprete 170 links will be finished in around 60 to 90 minutes depending on your internet connection, basically what's happening is it takes 10 links (by default), uses Playwrights headless browser and opens up the links and waits till they're are all loaded, captures them and saves them to the /data folder.

**Comment by daniel31x13** [comment]
@mztiq happy to hear! Yeah the high CPU usage is normal and only for whenever you import a chunk of bookmarks.

**Comment by alexdelprete** [comment]
I have a symmetric 1Gbit FTTH connection. I see low traffic right now, and I don't know why it's using all 8 cores at 100% since it finished importing. :(

Didn't think it was so cpu intensive...

**Comment by mztiq** [comment]
CPU usage is back to normal after peaking at 100% for around 15 minutes (133 Bookmarks).

**Comment by daniel31x13** [comment]
The closest thing we currently got is you can use the bulk actions feature to send links in batch.

**Comment by alexdelprete** [comment]
@daniel31x13 my server is still using 4 cores at 100%, after almost 2h. :(

Should I restart the server or docker service or should I wait? it would be useful to know what actually linkwarden is doing.

**Comment by daniel31x13** [comment]
> it would be useful to know what actually linkwarden is doing.

You can check out the logs and it'll say which links are currently in the queue, no need to restart.

**Comment by alexdelprete** [comment]
> You can check out the logs and it'll say which links are currently in the queue, no need to restart.

It took hours: I went to bed and in the morning I found it completed, but in the log there were no timestamps so I don't know how long it actually took, but after 3h it was still working when I decided to stop waiting.

Anyway, it's all good now. Thanks for the help Daniel.

**Comment by bryanhunwardsen** [comment]
@daniel31x13 I think this item can be closed, 2.5.2/2.5.3 supports all features from the current LinkAce html export.
