### ISSUE TITLE
PDF URIs do not save

### ISSUE THREAD

**Issue by tinyn** [linkwarden/linkwarden#336]
- using docker with version Linkwarden 2.3.0
- Attempt to save this URL to my repo: https://eprint.iacr.org/2023/1711.pdf
- Error 
linkwarden-linkwarden-1  | page.goto: net::ERR_ABORTED at https://eprint.iacr.org/2023/1711.pdf
linkwarden-linkwarden-1  | =========================== logs ===========================
linkwarden-linkwarden-1  | navigating to "https://eprint.iacr.org/2023/1711.pdf", waiting until "domcontentloaded"
linkwarden-linkwarden-1  | ============================================================
linkwarden-linkwarden-1  |     at archive (/data/.next/server/chunks/1919.js:56:24) {
linkwarden-linkwarden-1  |   name: 'Error'
linkwarden-linkwarden-1  | }
linkwarden-linkwarden-1  | node:internal/process/promises:288
linkwarden-linkwarden-1  |             triggerUncaughtException(err, true /* fromPromise */);
linkwarden-linkwarden-1  |             ^
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | page.goto: net::ERR_ABORTED at https://eprint.iacr.org/2023/1711.pdf
linkwarden-linkwarden-1  | =========================== logs ===========================
linkwarden-linkwarden-1  | navigating to "https://eprint.iacr.org/2023/1711.pdf", waiting until "domcontentloaded"
linkwarden-linkwarden-1  | ============================================================
linkwarden-linkwarden-1  |     at archive (/data/.next/server/chunks/1919.js:56:24) {
linkwarden-linkwarden-1  |   name: 'Error'
linkwarden-linkwarden-1  | }
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | Node.js v18.18.2

Thoughts?

**Comment by daniel31x13** [comment]
Hello @tinyn,

This is something that we already fixed and it will be ready in the next release soon.

**Comment by tinyn** [comment]
Thank you for your response.
