### ISSUE TITLE
Failed to create png or pdf

### ISSUE THREAD

**Issue by tinyn** [linkwarden/linkwarden#337]
Using docker with version Linkwarden 2.3.0

- Attempt to save the URL: https://itehax.com/blog/portable-executable-explained-throught-rust-code
- The readability version is created
- The PDF and the PNG versions fail
- No errors in the log I can see
- The only preserved format is the readability one

**Comment by daniel31x13** [comment]
Hello @tinyn,

> The PDF and the PNG versions fail

This is something that we already fixed and it will be ready in the next release soon.

> Attempt to save the URL: https://itehax.com/blog/portable-executable-explained-throught-rust-code

When archiving a webpage with Linkwarden, it automatically scrolls through the page. If this scrolling process exceeds 30 seconds, Linkwarden will cancel the operation. You can modify this time limit by adjusting the `AUTOSCROLL_TIMEOUT` environment variable, which is set in seconds.

**Comment by tinyn** [comment]
Thank you for the response. I have upped the AUTOSCROLL_TIMEOUT to 120 seconds and it seems to have worked just fine.
