### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Peter-Go** [linkwarden/linkwarden#341]
I understand that there is no 'admin' user so password resets have to be completed on the database, however I can't seem to see how to accomplish this? 

I have postgres running in a seperate docker container and can access the console however I'm not sure on how to go about resetting passwords etc.

Is there a guide for this?

**Comment by daniel31x13** [comment]
We’ll be adding an admin panel soon.

**Comment by Peter-Go** [comment]
Great, thanks
