### ISSUE TITLE
Middleware need

### ISSUE THREAD

**Issue by YeeJiaWei** [linkwarden/linkwarden#343]
**Describe the bug**
When i develop with this repo, I found out that when user are not found in the database, application will throw error, instead of redirecting to login page.

**To Reproduce**
1. Logged in with any user
2. Refresh database
3. Refresh application 

**Expected behavior**
Should be auto redirect to auth page (login) when not authenticated

**Comment by daniel31x13** [comment]
I think this mainly affects the dev environment since actual users can't refresh the database.

**Comment by YeeJiaWei** [comment]
Hmm, but why is that redirect not working. It just keep showing errors message in dashboard

**Comment by daniel31x13** [comment]
I can't reproduce the bug...
