### ISSUE TITLE
STORAGE_FOLDER ENV variable seems to do nothing

### ISSUE THREAD

**Issue by samip5** [linkwarden/linkwarden#354]
**Describe the bug**
I want to store my things in /config or any other folder than /data but the app still tries to create things in /data/.next as an example.

**To Reproduce**
1. Deploy container with env variable `STORAGE_FOLDER: "/config"`
2. Mount /config to somewhere
3. See that it will still try to save in /data and error out

**Expected behavior**
I would have expected the /config path to be used.

**Additional context**
There also doesn't appear to be logging level settings at all.

**Comment by daniel31x13** [comment]
Instead of setting the `STORAGE_FOLDER` to "/config", set it to "config":
```
STORAGE_FOLDER: "config"
```
You shouldn't be including the slash at the start...

**Comment by samip5** [comment]
The docs seems to be incorrect then, as the https://docs.linkwarden.app/self-hosting/environment-variables shows it with `/`

**Comment by samip5** [comment]
Hey @daniel31x13, it seems that setting it as `STORAGE_FOLDER: "config"` results in it just showing up in the container as:

```
env|grep -i "folder"
STORAGE_FOLDER=config
```

which results in it not using it?

**Comment by samip5** [comment]
It definitely doesn't use it right.

```
[Error: ENOENT: no such file or directory, unlink '/data/"config"/uploads/avatar/1.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/data/"config"/uploads/avatar/1.jpg'
}
```
