### ISSUE TITLE
Prisma SQL queries should not be printed to console

### ISSUE THREAD

**Issue by samip5** [linkwarden/linkwarden#355]
**Describe the bug**
It seems the app prints pretty much all of the prisma SQL queries to console, even if they include passwords.

**To Reproduce**
1. Deploy app from dev branch
2. Create a user
3. Check logs
4. See a lot of prisma SQL queries and even the password used is logged tho console

**Expected behavior**
I would have expected it to at least mask the sensitive details.

**Comment by daniel31x13** [comment]
This isn’t a bug, and the queries aren’t sensitive.
It’s to debug stuff easier.

**Comment by samip5** [comment]
> the queries aren’t sensitive.

They should be considered sensitive if they print out my password which they do.

**Comment by daniel31x13** [comment]
It’s hashed.

**Comment by samip5** [comment]
> It’s hashed. So that isn’t sensitive.

When you create an account, it's printed to console in cleartext among the SQL queries.

**Comment by daniel31x13** [comment]
I’ll check, if that’s true it’s probably because of the initial setup of nextauth which I then forgot to strip it out afterwards.
Thanks for mentioning this.

**Comment by daniel31x13** [comment]
Nope, I already stripped it out so no password is being shown in the logs:

This is *exactly* what's happening behind the scene when a user is created:
https://github.com/linkwarden/linkwarden/blob/main/lib/api/controllers/users/postUser.ts

And this is *exactly* what's happening behind the scene when an existing user is logged in:
https://github.com/linkwarden/linkwarden/blob/main/pages/api/v1/auth/%5B...nextauth%5D.ts

In JS/TS when you want to log something to the console you need to use the `console.log` command, if you look through both files you'll notice the only place I used `console.log` was [over here](https://github.com/linkwarden/linkwarden/blob/0f40578ca990f5a45f0298945619becb33037e6d/pages/api/v1/auth/%5B...nextauth%5D.ts#L28C1-L28C1):
```

**Comment by daniel31x13** [comment]
Nope, I already stripped it out so no password is being shown in the logs:

This is *exactly* what's happening behind the scene when a user is created:
https://github.com/linkwarden/linkwarden/blob/main/lib/api/controllers/users/postUser.ts

And this is *exactly* what's happening behind the scene when an existing user is logged in:
https://github.com/linkwarden/linkwarden/blob/main/pages/api/v1/auth/%5B...nextauth%5D.ts

**Comment by samip5** [comment]
Ah, sorry. It was when you delete an user.

```
prisma:query SELECT "public"."Link"."id", "public"."Link"."name", "public"."Link"."url", "public"."Link"."description", "public"."Link"."collectionId", "public"."Link"."textContent", "public"."Link"."screenshotPath", "public"."Link"."pdfPath", "public"."Link"."readabilityPath", "public"."Link"."lastPreserved", "public"."Link"."createdAt", "public"."Link"."updatedAt" FROM "public"."Link" WHERE ("public"."Link"."id") IN (SELECT "t0"."id" FROM "public"."Link" AS "t0" INNER JOIN "public"."Collection" AS "j0" ON ("j0"."id") = ("t0"."collectionId") WHERE (("j0"."ownerId" = $1 OR ("j0"."id") IN (SELECT "t1"."id" FROM "public"."Collection" AS "t1" INNER JOIN "public"."UsersAndCollections" AS "j1" ON ("j1"."collectionId") = ("t1"."id") WHERE ("j1"."userId" = $2 AND "t1"."id" IS NOT NULL))) AND "t0"."id" IS NOT NULL)) ORDER BY "public"."Link"."createdAt" DESC LIMIT $3 OFFSET $4
{
  password: 'ohl@ah"z1phophi[yuye1Ogh0ohyoh',
  cancellation_details: {}
}
prisma:query SELECT 1
prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."username", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."password", "public"."User"."archiveAsScreenshot", "public"."User"."archiveAsPDF", "public"."User"."archiveAsWaybackMachine", "public"."User"."isPrivate", "public"."User"."displayLinkIcons", "public"."User"."blurredFavicons", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query BEGIN
prisma:query SELECT "public"."WhitelistedUser"."id" FROM "public"."WhitelistedUser" WHERE "public"."WhitelistedUser"."userId" = $1 OFFSET $2
prisma:query SELECT "public"."WhitelistedUser"."id" FROM "public"."WhitelistedUser" WHERE "public"."WhitelistedUser"."userId" = $1
prisma:query SELECT "public"."Link"."id" FROM "public"."Link" WHERE ("public"."Link"."id") IN (SELECT "t0"."id" FROM "public"."Link" AS "t0" INNER JOIN "public"."Collection" AS "j0" ON ("j0"."id") = ("t0"."collectionId") WHERE ("j0"."ownerId" = $1 AND "t0"."id" IS NOT NULL)) OFFSET $2
prisma:query SELECT "public"."Link"."id" FROM "public"."Link" WHERE ("public"."Link"."id") IN (SELECT "t0"."id" FROM "public"."Link" AS "t0" INNER JOIN "public"."Collection" AS "j0" ON ("j0"."id") = ("t0"."collectionId") WHERE ("j0"."ownerId" = $1 AND "t0"."id" IS NOT NULL))
prisma:query SELECT "public"."Tag"."id" FROM "public"."Tag" WHERE "public"."Tag"."ownerId" = $1 OFFSET $2
prisma:query SELECT "public"."Tag"."id" FROM "public"."Tag" WHERE "public"."Tag"."ownerId" = $1
prisma:query SELECT "public"."Collection"."id", "public"."Collection"."name", "public"."Collection"."description", "public"."Collection"."color", "public"."Collection"."isPublic", "public"."Collection"."ownerId", "public"."Collection"."createdAt", "public"."Collection"."updatedAt" FROM "public"."Collection" WHERE "public"."Collection"."ownerId" = $1 OFFSET $2
prisma:query SELECT "public"."Collection"."id" FROM "public"."Collection" WHERE "public"."Collection"."ownerId" = $1 OFFSET $2
prisma:query SELECT "public"."Collection"."id" FROM "public"."Collection" WHERE "public"."Collection"."ownerId" = $1
[Error: ENOENT: no such file or directory, unlink '/data/data/uploads/avatar/1.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/data/data/uploads/avatar/1.jpg'
}
prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."username", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."password", "public"."User"."archiveAsScreenshot", "public"."User"."archiveAsPDF", "public"."User"."archiveAsWaybackMachine", "public"."User"."isPrivate", "public"."User"."displayLinkIcons", "public"."User"."blurredFavicons", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1)
prisma:query DELETE FROM "public"."User" WHERE ("public"."User"."id" IN ($1) AND ("public"."User"."id" = $2 AND 1=1))
prisma:query COMMIT

```

**Comment by daniel31x13** [comment]
Oh forgot to strip the logging over there, gonna be fixed in the next release.

**Comment by verymilan** [comment]
For those landing here in search for less noise, the particular query part is set in https://github.com/linkwarden/linkwarden/blob/main/lib/api/db.ts#L8
I set it to `warn`. More options: https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging#log-to-stdout

You may need to `yarn build` and to directly configure it in the container (did not try without building).
