### ISSUE TITLE
Turn off Auto Capitalization for Link Names

### ISSUE THREAD

**Issue by ItzIte** [linkwarden/linkwarden#359]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem.

**Describe the solution you'd like**
This is a very simple feature request: When creating a link with a custom name, Linkwarden auto capitalizes those links. Sometimes I prefer to use specific capitalization, or none at all.

**Describe alternatives you've considered**
I haven't really thought of any other alternatives, unless I've simply missed a switch to turn this off already.

**Additional context**
No additional context.

**Comment by daniel31x13** [comment]
Added in [v2.4.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.0).
