### ISSUE TITLE
Choose what happens when you click on the Links in settings (Open readable/Open original/...)

### ISSUE THREAD

**Issue by hugalafutro** [linkwarden/linkwarden#367]
**Is your question related to a problem or code? Please describe.**
no

**Describe what you've tried to solve this question**
I'm trying to retain the previous functionality where clicking on saved link opened the archived copy, not the actual link pulling data from internet

**Include any code or screenshots (if applicable)**
no

**Additional context**
I looked through settings, but couldn't see anything related. Previously even if offline I could click on a saved link and get the saved link opened. After 2.4 if I click a saved link it opens the actual link, wasting data again. To retain previous functionality I have to click the 3 dots, archived formats and choose readable.

Any way to return to opening the saved links instead of actual webpages without downgrading?

Thanks for any advice!

**Comment by daniel31x13** [comment]
Adding an option to choose what happens when you click the Links?
That'd be a great alternative, added to todo...

**Comment by stanthewizzard** [comment]
yes and better add little icon next to title to open link / arch/ Pdf / readable

**Comment by daniel31x13** [comment]
This feature has been released in [v2.5.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.0).
