### ISSUE TITLE
Authentik SSO/OAuth callback URL 404

### ISSUE THREAD

**Issue by shis95** [linkwarden/linkwarden#368]
I'm having an issue with the callback URL showing a 404 when configuring Authentik SSO/OAuth authentication.

The callback URL automatically saved through Authentik is `/api/auth/callback/authentik`. Is this callback URL correct?
![11113](https://github.com/linkwarden/linkwarden/assets/34735016/9a92f2a7-fa7f-4ebe-b9ac-160568a17953)

Or do you need to implement the callback address yourself?

**Comment by samip5** [comment]
> I'm having an issue with the callback URL showing a 404 when configuring Authentik SSO/OAuth authentication.

Which issuer URL format did you use? One with ending slash?

**Comment by shis95** [comment]
Found the problem, you need to set `NEXTAUTH_URL=http://localhost:3000/api/v1/auth`，view the correct callback address through the source code: `/api/v1/auth/callback/authentik`.

**Comment by daniel31x13** [comment]
Hey there, so is Authentik's integration working?

**Comment by samip5** [comment]
> Hey there, so is Authentik's integration working?

Yes, it is. However without that NEXTAUTH_URL being correct, it ends with 404. :)

**Comment by daniel31x13** [comment]
Great thanks.

**Comment by metril** [comment]
No, the Authentik integration is not working. After getting redirected back to Linkwarden, no user is created or the SSO user is not logged in.

**Comment by samip5** [comment]
> No, the Authentik integration is not working. After getting redirected back to Linkwarden, no user is created or the SSO user is not logged in.

It's working perfectly fine, you just need to have `NEXTAUTH_URL` and Issuer set correctly (not how Authentik shows it).

**Comment by metril** [comment]
I will open a new issue. I have `NEXTAUTH_URL` set without the trailing slash. I have the `NEXTAUTH_URL` set to "https://linkwardwen.mydomain.com//api/v1/auth". Does not work.

**Comment by samip5** [comment]
> I will open a new issue. I have `AUTHENTIK_ISSUER` set without the trailing slash. I have the `NEXTAUTH_URL` set to "https://linkwardwen.mydomain.com//api/v1/auth". Does not work.

There's an extra `/` in the `NEXTAUTH_URL`.

**Comment by metril** [comment]
That extra `/` was a typo when I was obfuscating my domain name. I double checked and there is no extra `/` in my actual `NEXTAUTH_URL`.
