### ISSUE TITLE
Trying to get Authentik SSO working with Linkwarden

### ISSUE THREAD

**Issue by metril** [linkwarden/linkwarden#373]
I am trying to get Authentik SSO working with Linkwarden. I have the following variables set in my docker compose file for linkwarden.

```
- DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
- NEXT_PUBLIC_AUTHENTIK_ENABLED=true
- NEXTAUTH_URL=https://linkwarden.mydomain.com/api/v1/auth
- AUTHENTIK_CUSTOM_NAME=Authentik
- AUTHENTIK_ISSUER=https://authentik.mydomain.com/application/o/linkwarden
- AUTHENTIK_CLIENT_ID=$CLIENT_ID
- AUTHENTIK_CLIENT_SECRET=$CLIENT_SECRET
```

I watched the network log in my Chrome browser and I am directed to Authentik,  login happens in Authentik, and then I am redirected back to Linkwarden. There is no 404 error throughout all of this. However, Linkwarden does not login. I am instead at the login page again and no login has occured.

**Comment by mvivaldi** [comment]
same problem here.
linkwarden 2.4.1

**Comment by samip5** [comment]
Running 2.4.1 too and no issues.

Please check your container logs for errors, I have a hunch that there might be a permissions errors which is preventing the login like I had with mine at start.

**Comment by mvivaldi** [comment]
> Running 2.4.1 too and no issues.
> 
> Please check your container logs for errors, I have a hunch that there might be a permissions errors which is preventing the login like I had with mine at start.

could you provide your config?
I have this problem in my logs:
```
[0] [next-auth][error][SIGNIN_OAUTH_ERROR] 
[0] https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 301 Moved Permanently {
[0]   error: {
[0]     message: 'expected 200 OK, got: 301 Moved Permanently',
[0]     stack: 'OPError: expected 200 OK, got: 301 Moved Permanently\n' +
[0]       '    at processResponse (/data/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
[0]       '    at Issuer.discover (/data/node_modules/openid-client/lib/issuer.js:152:20)\n' +
[0]       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
[0]       '    at async openidClient (/data/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
[0]       '    at async getAuthorizationUrl (/data/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
[0]       '    at async Object.signin (/data/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
[0]       '    at async AuthHandler (/data/node_modules/next-auth/core/index.js:260:26)\n' +
[0]       '    at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)\n' +
[0]       '    at async NextAuth._args$ (/data/node_modules/next-auth/next/index.js:106:14)',
[0]     name: 'OPError'
[0]   },
[0]   providerId: 'authentik',
[0]   message: 'expected 200 OK, got: 301 Moved Permanently'
[0] }
```

could be because I installed it in a  kubernetes cluster  (but with normal user and password it works without any problem)

**Comment by metril** [comment]
It was not a permission issue. The final puzzle piece was the specifying a singing key for Authentik.

**Comment by metril** [comment]
> > Running 2.4.1 too and no issues.
> > Please check your container logs for errors, I have a hunch that there might be a permissions errors which is preventing the login like I had with mine at start.
> 
> could you provide your config? I have this problem in my logs:
> 
> ```
> [0] [next-auth][error][SIGNIN_OAUTH_ERROR] 
> [0] https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 301 Moved Permanently {
> [0]   error: {
> [0]     message: 'expected 200 OK, got: 301 Moved Permanently',
> [0]     stack: 'OPError: expected 200 OK, got: 301 Moved Permanently\n' +
> [0]       '    at processResponse (/data/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
> [0]       '    at Issuer.discover (/data/node_modules/openid-client/lib/issuer.js:152:20)\n' +
> [0]       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
> [0]       '    at async openidClient (/data/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
> [0]       '    at async getAuthorizationUrl (/data/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
> [0]       '    at async Object.signin (/data/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
> [0]       '    at async AuthHandler (/data/node_modules/next-auth/core/index.js:260:26)\n' +
> [0]       '    at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)\n' +
> [0]       '    at async NextAuth._args$ (/data/node_modules/next-auth/next/index.js:106:14)',
> [0]     name: 'OPError'
> [0]   },
> [0]   providerId: 'authentik',
> [0]   message: 'expected 200 OK, got: 301 Moved Permanently'
> [0] }
> ```
> 
> could be because I installed it in a kubernetes cluster (but with normal user and password it works without any problem)

I've already provided my config. The only thing I have not provided is the Authentik portion. Leave the redirect URI blank in Authentik and let it autofill. Make sure to select a signing key.

**Comment by samip5** [comment]
> > Running 2.4.1 too and no issues.
> > 
> > Please check your container logs for errors, I have a hunch that there might be a permissions errors which is preventing the login like I had with mine at start.
> 
> could you provide your config?
> I have this problem in my logs:
> ```
> [0] [next-auth][error][SIGNIN_OAUTH_ERROR] 
> [0] https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 301 Moved Permanently {
> [0]   error: {
> [0]     message: 'expected 200 OK, got: 301 Moved Permanently',
> [0]     stack: 'OPError: expected 200 OK, got: 301 Moved Permanently\n' +
> [0]       '    at processResponse (/data/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
> [0]       '    at Issuer.discover (/data/node_modules/openid-client/lib/issuer.js:152:20)\n' +
> [0]       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
> [0]       '    at async openidClient (/data/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
> [0]       '    at async getAuthorizationUrl (/data/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
> [0]       '    at async Object.signin (/data/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
> [0]       '    at async AuthHandler (/data/node_modules/next-auth/core/index.js:260:26)\n' +
> [0]       '    at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)\n' +
> [0]       '    at async NextAuth._args$ (/data/node_modules/next-auth/next/index.js:106:14)',
> [0]     name: 'OPError'
> [0]   },
> [0]   providerId: 'authentik',
> [0]   message: 'expected 200 OK, got: 301 Moved Permanently'
> [0] }
> ```
> 
> could be because I installed it in a  kubernetes cluster  (but with normal user and password it works without any problem)
> 

Your Issuer url is incorrect.

**Comment by mvivaldi** [comment]
> > > Running 2.4.1 too and no issues.
> > > Please check your container logs for errors, I have a hunch that there might be a permissions errors which is preventing the login like I had with mine at start.
> > 
> > 
> > could you provide your config?
> > I have this problem in my logs:
> > ```
> > [0] [next-auth][error][SIGNIN_OAUTH_ERROR] 
> > [0] https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 301 Moved Permanently {
> > [0]   error: {
> > [0]     message: 'expected 200 OK, got: 301 Moved Permanently',
> > [0]     stack: 'OPError: expected 200 OK, got: 301 Moved Permanently\n' +
> > [0]       '    at processResponse (/data/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
> > [0]       '    at Issuer.discover (/data/node_modules/openid-client/lib/issuer.js:152:20)\n' +
> > [0]       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
> > [0]       '    at async openidClient (/data/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
> > [0]       '    at async getAuthorizationUrl (/data/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
> > [0]       '    at async Object.signin (/data/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
> > [0]       '    at async AuthHandler (/data/node_modules/next-auth/core/index.js:260:26)\n' +
> > [0]       '    at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)\n' +
> > [0]       '    at async NextAuth._args$ (/data/node_modules/next-auth/next/index.js:106:14)',
> > [0]     name: 'OPError'
> > [0]   },
> > [0]   providerId: 'authentik',
> > [0]   message: 'expected 200 OK, got: 301 Moved Permanently'
> > [0] }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > could be because I installed it in a  kubernetes cluster  (but with normal user and password it works without any problem)
> 
> Your Issuer url is incorrect. Take off the slash from the end of it.

With the correct issuer URL, I don't have any errors in the log, but the login is not working:

    I click on 'Sign In with Authentik.'
    I log in with Authentik.
    I'm redirected to the login page again.

I think I need to read the documentation a little more. I upgraded from 2.3.0 and installed Linkwarden with a generic Helm chart, so the error might be related to something I did.

**Comment by metril** [comment]
@mvivaldi My original issue is resolved. I am going to close this topic. You should open your own issue since you are using helm and that is quite different from my setup.

**Comment by samip5** [comment]
> generic Helm chart

https://kubesearch.dev and search for linkwarden.

**Comment by falkheiland** [comment]
had the same issue in docker compose.

this helped:
> Your Issuer url is incorrect. Take off the slash from the end of it.

authentik shows you the issuer url with an `/` at the end, so i initially used it like that.

>I click on 'Sign In with Authentik.'
I log in with Authentik.
I'm redirected to the login page again.

my next problem was / is, that i tried to login with an existing user, which is not supported according to https://github.com/linkwarden/linkwarden/issues/392#issuecomment-1875326960 - so i will export the data / settings and delete the user (and reimport after oauth user creation)
