### ISSUE TITLE
SSO Users can't choose what to backup

### ISSUE THREAD

**Issue by mpldr** [linkwarden/linkwarden#374]
**Describe the bug**

**To Reproduce**
1. Sign in via SSO
2. Settings > Archive
3. Change the settings
4. get a rather confusing error message

![2023-12-29-23-44-22](https://github.com/linkwarden/linkwarden/assets/33086936/290b0111-a73a-496c-bd9e-204b803f2f4a)

**Expected behavior**
Unavailable options are either disabled, or an appropriate error message.

**Screenshots**
![2023-12-29-23-44-22](https://github.com/linkwarden/linkwarden/assets/33086936/290b0111-a73a-496c-bd9e-204b803f2f4a)

**Desktop:**
 - OS: Linux
 - Browser Librewolf
 - Version 121

**Comment by daniel31x13** [comment]
Fixed in [v2.4.4](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.4).
