### ISSUE TITLE
unable to share collection with other SSO users

### ISSUE THREAD

**Issue by mvivaldi** [linkwarden/linkwarden#377]
I have linkwarden 2.4.3 and the users are from authentik.
In settings under username I have a blank textbox (the display name is filled correctly with the information provided by authentik) and I am unable to change it.
With this problem I'm unable to share any collections with other users.

**Comment by daniel31x13** [comment]
Fixed in [v2.4.4](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.4).

You might also need to manually modify the users in the database and set the name and username with the correct ones from the SSO provider. Sorry for the inconvenience.

**Comment by mvivaldi** [comment]
I backed up my saved links and reinstalled linkwarden with a clean database, and I am unable to see anything (the server doesn't display the login page) and I have this error in the browser console:
404 https://linkwarden.mydomain.com/api/v1/users/1
and if I go there with a browser I receive:
{"response":"User not found or profile is private."}

if you want I open another ticket.

Thank you for your work!

**Comment by mvivaldi** [comment]
maybe is only a problem of browser cache... let me check

**Comment by mvivaldi** [comment]
yes, after clearing all the cookies everything is fine.

Thank you!

**Comment by mvivaldi** [comment]
ok sharing with other SSO users is working.
Now I will open another ticket for a feature request!
