### ISSUE TITLE
File is too large to be stored

### ISSUE THREAD

**Issue by Deiity** [linkwarden/linkwarden#381]
First of all, thank you for this awesome tool! Just a quick question:

Trying to add a specific URL and it throws 400 error File is too large to be stored.

1. Go to collection
2. Click on + Then new link
3. Input an URL, in this case its https://appflowy.io url ( saving for future self-hosting app )
4.  JSON POST

{"name":"","url":"https://appflowy.io/","description":"","type":"url","tags":[],"preview":"","image":"","pdf":"","readable":"","textContent":"","collection":{"id":2,"name":"SelfHost","ownerId":1}}

I tried with both disabling all archive settings ( pdf,screenshot, archive.org)

![image](https://github.com/linkwarden/linkwarden/assets/11446302/cd92041c-c1cd-4e37-b06a-dc4fb40f012c)

**Desktop (please complete the following information):**
- Broswer Firefox
- Platform: Docker on debian 12

Relevant snipper of the code:

https://github.com/linkwarden/linkwarden/blob/dea1e12700ba6d90b35a67fe54554c79de4ca0cc/lib/api/archiveHandler.ts#L46

PS: Other links works normally. Cheers

**Comment by patrickasmus** [comment]
I agree with Deiity's message.
For me, the only difference is:

I insert an internal URL.
In my case, it's 'https://10.0.1.12:8006' and it doesn't matter whether I append the port to the IP address or not.
The same happens if I enter an internal DNS: 'https://vhost02.domain.int:8006'

I tried with both disabling all archive settings too. ( pdf,screenshot, archive.org)

![grafik](https://github.com/linkwarden/linkwarden/assets/49373047/6b186a38-caba-4547-9862-7b6b5007f0e2)

Other links also work for me.

Thank you very much for this really great tool.
I wish you a happy new year.

Patrick

**Comment by daniel31x13** [comment]
Taking a look at the logs in the terminal:

> FetchError: request to https://appflowy.io/ failed, reason: unable to verify the first certificate

Looks more like a certificate problem.

**Comment by Deiity** [comment]
You are right, one of the CA chains is not trusted by the major broswers. Is there any way to bypass this or perhaps add an option to skip that? If it's too much work then you may close this. Cheers

**Comment by patrickasmus** [comment]
I think it's the same issue for me.
The certificate cannot be checked because I cannot install a valid certificate for every service in my Homelab.

Is there a possibility of a bypass here?

Many thanks and best regards
Patrick

**Comment by daniel31x13** [comment]
Added an extra `IGNORE_UNAUTHORIZED_CA` environment variable in [v2.4.7](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.7).

It's worth mentioning that this only affects the `validateUrlSize` function which checks if the url that's about to be archived is less than 30MB, and the `getTitle` function which gets the title tag of the webpages and sets them as the description.

**Comment by patrickasmus** [comment]
Thank you for your great work!

**Comment by NenadQC** [comment]
Cheers brother. Happy New year!
