### ISSUE TITLE
Failed to archive a site

### ISSUE THREAD

**Issue by tinyn** [linkwarden/linkwarden#389]
**Describe the bug**
If you attempt to archive this 

https://www.cell.com/action/showPdf?pii=S2589-0042%2823%2901077-5

site, it will create a new entry but will fail while downloading the content (pdf) of the site. I have attached the logs captured while doing this. I did attempt to delete the entry and try again, same results. If there is more I can capture to help, let me know.

---

**Error Log**
linkwarden-linkwarden-1  | [1] Error processing link https://www.cell.com/action/showPdf?pii=S2589-0042%2823%2901077-5 for user 1: page.goto: net::ERR_ABORTED at https://www.cell.com/action/showPdf?pii=S2589-0042%2823%2901077-5                                                                                                                 linkwarden-linkwarden-1  | [1] =========================== logs ===========================                                                                               linkwarden-linkwarden-1  | [1] navigating to "https://www.cell.com/action/showPdf?pii=S2589-0042%2823%2901077-5", waiting until "domcontentloaded"                        linkwarden-linkwarden-1  | [1] ============================================================
linkwarden-linkwarden-1  | [1]     at /data/lib/api/archiveHandler.ts:96:22
linkwarden-linkwarden-1  | [1]     at async archiveHandler (/data/lib/api/archiveHandler.ts:40:5)
linkwarden-linkwarden-1  | [1]     at async archiveLink (/data/scripts/worker.ts:144:7)
linkwarden-linkwarden-1  | [1]     at async processBatch (/data/scripts/worker.ts:167:3)
linkwarden-linkwarden-1  | [1]     at async init (/data/scripts/worker.ts:180:7) {
linkwarden-linkwarden-1  | [1]   name: 'Error'
linkwarden-linkwarden-1  | [1] }

**Comment by tinyn** [comment]
Found a second example

https://www.annualreviews.org/doi/pdf/10.1146/annurev-conmatphys-031119-050745

**Error Log**
linkwarden-linkwarden-1  | [1] Error processing link https://www.annualreviews.org/doi/pdf/10.1146/annurev-conmatphys-031119-050745 for user 1: page.goto: net::ERR_ABORTED at https://www.annualreviews.org/doi/pdf/10.1146/annurev-conmatphys-031119-050745
linkwarden-linkwarden-1  | [1] =========================== logs ===========================
linkwarden-linkwarden-1  | [1] navigating to "https://www.annualreviews.org/doi/pdf/10.1146/annurev-conmatphys-031119-050745", waiting until "domcontentloaded"
linkwarden-linkwarden-1  | [1] ============================================================
linkwarden-linkwarden-1  | [1]     at /data/lib/api/archiveHandler.ts:96:22
linkwarden-linkwarden-1  | [1]     at async archiveHandler (/data/lib/api/archiveHandler.ts:40:5)
linkwarden-linkwarden-1  | [1]     at async archiveLink (/data/scripts/worker.ts:144:7)
linkwarden-linkwarden-1  | [1]     at async processBatch (/data/scripts/worker.ts:167:3)
linkwarden-linkwarden-1  | [1]     at async init (/data/scripts/worker.ts:180:7) {
linkwarden-linkwarden-1  | [1]   name: 'Error'
linkwarden-linkwarden-1  | [1] }

**Comment by daniel31x13** [comment]
This is because both of the links are behind Cloudflare, and since cloudflare doesn't like bots, it's challenging us and the `content-type` is `text/html; charset=UTF-8` instead of `application/pdf` while making a fetch request to determine the url type:

```js
 Headers {
   [Symbol(map)]: [Object: null prototype] {
    date: [ 'Mon, 01 Jan 2024 15:24:50 GMT' ],
    'content-type': [ 'text/html; charset=UTF-8' ],
    connection: [ 'close' ],
    'cross-origin-embedder-policy': [ 'require-corp' ],
    'cross-origin-opener-policy': [ 'same-origin' ],
    'cross-origin-resource-policy': [ 'same-origin' ],
    'origin-agent-cluster': [ '?1' ],
    'permissions-policy': [
      'accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()'
    ],
    'referrer-policy': [ 'same-origin' ],
    'x-frame-options': [ 'SAMEORIGIN' ],
    'cf-mitigated': [ 'challenge' ],
    'cache-control': [
      'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0'
    ],
    expires: [ 'Thu, 01 Jan 1970 00:00:01 GMT' ],
    'set-cookie': [
      '__cf_bm=V4f5dnNe.z.T.BVFZ9YjKLuaNBfSGkzOQ2U4Osz7Eh0-1704122690-1-AWCzt38ih/AznSIBn8ubJ9x8dD8AIB4D1MshaKZDs4fweaCwUMoIpoa7eXBUe795GOL4ob8E30kZkPYgPGZKHfc=; path=/; expires=Mon, 01-Jan-24 15:54:50 GMT; domain=.annualreviews.org; HttpOnly; Secure; SameSite=None'
    ],
    vary: [ 'Accept-Encoding' ],
    'strict-transport-security': [ 'max-age=15552000' ],
    server: [ 'cloudflare' ],
    'cf-ray': [ '83ebc5811ef6a204-YYZ' ],
    'alt-svc': [ 'h3=":443"; ma=86400' ]
  }
}
```

**Comment by tinyn** [comment]
Thank you for looking into it. This might not be something which can be fixed with a simple code change. If it can't feel free to close it.

**Comment by tinyn** [comment]
Sorry to place this here, but is may just be a one line answer. Is there a know size limit to file dowwnloads? I can archive this

https://arxiv.org/pdf/2106.10165.pdf

but not this

https://arxiv.org/pdf/2104.13478.pdf

**Comment by daniel31x13** [comment]
Yep, `NEXT_PUBLIC_MAX_FILE_SIZE` is by default set to 30MB, the second file you provided is over 45MB.

So if you want to bypass this just add the following line to your .env file:
```
NEXT_PUBLIC_MAX_FILE_SIZE=1000
```

This will set the max file size to 1000MB.

**Comment by tinyn** [comment]
Thanks again for the input.

**Comment by daniel31x13** [comment]
No problem!
