### ISSUE TITLE
Bug: Display of Preserved Formats in Front End

### ISSUE THREAD

**Issue by wiwikuan** [linkwarden/linkwarden#397]
**Describe the bug**
In settings → archive, when only the "Screenshot" option is selected, the front end does not display the preserved formats (screenshot and readability file), even though they are generated and can be verified via SSH.

**To Reproduce**
1. Go to Settings.
2. In the "Preserve Formats" section, select only "Screenshot".
3. Add a new link.
4. Via SSH, verify that both the screenshot and a xxxx_readability.json file are generated for the link.
5. In the front end, click on the added link and select "Preserved Formats".
6. The front end displays a message saying "Link preservation is in the queue" and does not show the screenshot or the readability file.

**Expected behavior**
The front end should display the screenshot and the readability file in the "Preserved Formats" section.

**Additional Information**
- The issue resolves only when the "PDF" option is also selected in the settings. After selecting "PDF," the front end correctly displays the screenshot and readability file.

**Screenshots**
With only "screenshot" option checked:
![With only "screenshot" option checked](https://github.com/linkwarden/linkwarden/assets/4676714/132472cc-fcc3-4ae8-a7f5-839a0a730f71)

Both "screenshot" and "PDF" options checked:
![Both "screenshot" and "PDF" options checked](https://github.com/linkwarden/linkwarden/assets/4676714/35d7a79f-4e53-4469-9d0a-e100c81e0a8d)

**Comment by daniel31x13** [comment]
Oh, gonna get to this. Thanks for pointing it out!

**Comment by daniel31x13** [comment]
Fixed in [v2.4.8](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.8).
