### ISSUE TITLE
Archive link as website

### ISSUE THREAD

**Issue by mmartinortiz** [linkwarden/linkwarden#402]
Links are archived as PDFs, images or plain text JSON. Would be nice to have another archive format, where the link is archived as HTML, with the images, js, etc.

**Describe the solution you'd like**
An extra archive format that saves the link as HTML. When this HTML file is open, all images, JS, etc, are loaded into a web browser.

**Describe alternatives you've considered**
This functionality is mainly the same way [ArchiveBox](https://github.com/ArchiveBox/ArchiveBox) archives websites.

**Additional context**
[Here is an example](https://demo.archivebox.io/archive/1704153652.705492/index.html#singlefile.html) of how ArchiveBox saves a website as HTML

**Comment by d0x360** [comment]
+1
That's actually what I signed up for but will probably stay a paying customer for other benefits though I haven't determined that yet.  To add to this I also wouldn't mind if you could have it follow links (without leaving the specific domain) x# deep that branch off from the main entered link.

That would allow people to more effectively and easily back up an entire site without having to visit 100 different links although a fiction like this should probably be local only for space considerations.  It should also grab common file types like zip and save those in the local directory as well along with non duplicated images the site uses.

I made something that did that in the early 2000s although significantly less complex than link warden and it would be something that's greatly appreciated here.

**Comment by daniel31x13** [comment]
Added in [v2.6.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.6.0).
