### ISSUE TITLE
archive youtube bookmarks with youtube-dl

### ISSUE THREAD

**Issue by snickers2k** [linkwarden/linkwarden#403]
**Is your feature request related to a problem? Please describe.**
- i'm getting more and more frustrated with youtube deleting way to many videos without any reason (pushing the report button became a troll-trend lately)

**Describe the solution you'd like**
- using youtube-dl to archive collected youtube-videos for offline/long-term use
(i feel like linkwarden could be the perfect place for this. similar to the function of archiving webpages)

**Comment by d0x360** [comment]
That's a great idea, especially for help videos where it would be extra beneficial to quickly be able to back it up although that could definitely chew through cloud storage really fast.

**Comment by daniel31x13** [comment]
This is out of the scope of this project, I think it's more appropriate to store your bookmarks and your videos separately.
