### ISSUE TITLE
How can edit a url link?

### ISSUE THREAD

**Issue by nkgiovannivl** [linkwarden/linkwarden#405]
**Is your question related to a problem or code? Please describe.**
Related to a problem in self-hosting installation

**Describe what you've tried to solve this question**
Documentation shows that I can edit URL link after creation, but in use, I can not edit it, if I click the URL in edit mode the link it's open, How can edit the URL after creation?

**Include any code or screenshots (if applicable)**
<img width="1014" alt="image" src="https://github.com/linkwarden/linkwarden/assets/48342344/70b1d583-616f-4db1-bf5c-f0daa2b13efb">

**Additional context**
[v2.4.8](https://github.com/linkwarden/linkwarden/tree/v2.4.8)

**Comment by daniel31x13** [comment]
It's not possible to change the url field.
Since the url is the main field of each link, changing that means changing the archives as well.
It's just much more convenient to just create a new link instead.

**Comment by rickykresslein** [comment]
I have to disagree that it is more convenient to create a new link. If I've already named a link, pinned it, put it in the folder I want, etc. it is much more convenient to click edit and change the URL. I would love to see this feature come to Linkwarden.
