### ISSUE TITLE
No login prompt after creating account

### ISSUE THREAD

**Issue by drittich** [linkwarden/linkwarden#406]
I've installed the latest version and created an account in Linkwarden. I can verify this by trying to recreate the account and getting a 
`"Username already exists."` response from the API.

When I then go to the `/login` page. I see:
![image](https://github.com/linkwarden/linkwarden/assets/1222810/b8f2f91f-ee69-4456-9cf2-1e3a21f780fe)

There is nowhere to put my credentials to login.

**Desktop**
 - OS: Windows 11
 - Browser Edge
 - Version 121.0.2277.4

**Comment by daniel31x13** [comment]
Strange, can you show me what your current environment variables looks like?

**Comment by daniel31x13** [comment]
Change `NEXTAUTH_URL` to `http://localhost:3000/api/v1/auth`.
Forgot to update the docs…

**Comment by drittich** [comment]
I've re-installed with the above change and I'm still not getting a login screen. There are no console or network errors. The auth API request seems correct and is coming back as an empty object:
![image](https://github.com/linkwarden/linkwarden/assets/1222810/b6aaf1e7-dc01-48b6-bf9f-c02943d1ced6)

**Comment by XiaoXuxxxx** [comment]
try set `NEXT_PUBLIC_CREDENTIALS_ENABLED=true`

**Comment by drittich** [comment]
That worked, thanks.

**Comment by ezoNetworks** [comment]
I'm having the same issue as well, even after setting NEXT_PUBLIC_CREDENTIALS_ENABLED=true
