### ISSUE TITLE
SSO with Authentik

### ISSUE THREAD

**Issue by Tealk** [linkwarden/linkwarden#409]
**Is your question related to a problem or code? Please describe.**
Unfortunately, I can't get the Authentik configuration to work.

I currently have the following error:

1) I click on Sign In with Authentik.
2) I log in with Authentik.
3) I'm redirected to the login page again.

In the docker log, I do not find an error message for the login.

**Additional context**
.env
```
NEXT_PUBLIC_AUTHENTIK_ENABLED=true
EXTAUTH_URL=https://linkwarden.rollenspiel.monster/api/v1/auth
AUTHENTIK_CUSTOM_NAME=Authentik
AUTHENTIK_ISSUER=https://auth.rollenspiel.monster/application/o/linkwarden
AUTHENTIK_CLIENT_ID=iYiTMvHun54FvzW5M4IzrXGnObRs1H6g9IHJ2bAY
AUTHENTIK_CLIENT_SECRET=xx
```

**Comment by noja11** [comment]
I'm having the exact same issue, however I can't even get linkwarden to forward auth to Authentik at all.  Generally, my setup mirrors Tealk's above with a .env being present.

**Comment by reivaxm** [comment]
Same for me,
I suppose it's linked to this issue https://github.com/nextauthjs/next-auth/issues/7428

**Comment by Procuria** [comment]
Had the same issue.
Solution for me:
1. Remove the trailing slash in AUTHENTIK_ISSUER like in the issue @reivaxm mentioned above.
2. Setup OAuth2Provider in authentik with certificate. 

![grafik](https://github.com/linkwarden/linkwarden/assets/37988494/8107ad11-c90f-4382-801f-4fd3291176b6)

**Comment by Tealk** [comment]
> Solution for me

I have exactly the same setup but it doesn't work.

**Comment by reivaxm** [comment]
If it's self signed Certificate or a private authority, have you add the certificate like
NODE_EXTRA_CA_CERTS = "/etc/local-ca/ca.crt" ?

**Comment by Tealk** [comment]
It is a certificate that I created via the Authentik web interface. It is therefore a self-signed certificate. So far I have connected 10 services via OAuth and each one has worked right away, only here there are problems.

 i don't even see an error message anywhere why the oauth doesn't work

**Comment by markus-ruderman** [comment]
I tested it locally in my homelab and it works 😄 

In my environment I use:
- Linkwarden v2.5.1  
- Authentik 2024.2.2
- NGINX Proxy Manager 2.11.1

First be sure to define `NEXTAUTH_URL=https://.../api/v1/auth` and not `EXTAUTH_URL=` as described at https://docs.linkwarden.app/self-hosting/sso-oauth#authentik - maybe it is only a copy & paste error in your description @Tealk 

But I've detected that a login doesn't work when the same username which is used via Authentik already exists in Linkwarden (you will see in the browser a redirect URL with the state that OAuth user can't be created, but no error message popup appears), therefore the existing user was created in Linkwarden and not via the OAuth Integration. So I renamed the existing Linkwarden username (appending the string `-lw` to the existing username) and then I logged in with my Authentik user and it worked.

So the bad thing is that there is no possibility to attach/configure an existing Linkwarden user to have different authentication mechanism at the moment. There is also no indicator at the user preferences if it is a user managed directly via Linkwarden or by an external ID Provider. Hope this will be improved soon.

**Comment by Tealk** [comment]
> maybe it is only a copy & paste error in your description

oh my god, that was the mistake and i didn't see it the whole time.
Thank you <3

**Comment by alhazmy13** [comment]
None of the above suggestions works with me, still getting the same error:

```json 
error: {
     message: 'self-signed certificate',
     stack: 'Error: self-signed certificate\n' +
       '    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)\n' +
       '    at TLSSocket.emit (node:events:517:28)\n' +
       '    at TLSSocket._finishInit (node:_tls_wrap:1017:8)\n' +
       '    at ssl.onhandshakedone (node:_tls_wrap:803:12)',
     name: 'Error'
   },
   providerId: 'authentik',
   message: 'self-signed certificate'
 }
```

**Comment by JKL213** [comment]
> Had the same issue. Solution for me:
> 
>     1. Remove the trailing slash in AUTHENTIK_ISSUER like in the issue @reivaxm mentioned above.
> 
>     2. Setup OAuth2Provider in authentik with certificate.
> 
> 
> ![grafik](https://private-user-images.githubusercontent.com/37988494/300229416-8107ad11-c90f-4382-801f-4fd3291176b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjE3ODUsIm5iZiI6MTcxNDMyMTQ4NSwicGF0aCI6Ii8zNzk4ODQ5NC8zMDAyMjk0MTYtODEwN2FkMTEtYzkwZi00MzgyLTgwMWYtNGZkMzI5MTE3NmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE2MjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYWUwMjYwOGQ5OWNjYTRlYzg2YWM5MzQwNzJmMzAzOGVjYjc1YWRkMmFlNDkwYTc4NzEyODVlYmNjNWMyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HuNiViCypzjE3XE6Uxh2PBkE-fpZAHaiXNRNYDq6E8E)

Fixed it for me, thank you very much.

**Comment by Tealk** [comment]
Since I had configured it incorrectly and it now works, I'll close the issue for now.
