### ISSUE TITLE
No way to sign in to Linkwarden

### ISSUE THREAD

**Issue by LionCityGaming** [linkwarden/linkwarden#415]
**Describe the bug**
There seems to be no way to sign in to Linkwarden. User account has been created.

**To Reproduce**
1. Go to Linkwarden sign in page 
2. See error

**Expected behavior**
Login fields should appear. Example from [cloud.linkwarden.com](https://cloud.linkwarden.app/login)
![image](https://github.com/linkwarden/linkwarden/assets/72677307/17dc544a-cc5d-48ed-beab-24f3d06d5309)

**Screenshots**
My instance:
![image](https://github.com/linkwarden/linkwarden/assets/72677307/f00fe977-de28-4a96-b742-6b402836164d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 122.0.2325.0 (Official build) canary (64-bit)

**Additional context**
Linkwarden selfhosted in Docker

**Comment by kzshantonu** [comment]
Same issue here

**Comment by Node815** [comment]
I can confirm also this is happening on my end as well.

**Comment by daniel31x13** [comment]
What does your environment variables look like? Have you taken the steps @Node815 pointed out in the installation?

https://docs.linkwarden.app/self-hosting/installation

**Comment by modem7** [comment]
What is your compose file?

**Comment by kzshantonu** [comment]
This is the solution: 
https://github.com/linkwarden/linkwarden/issues/406#issuecomment-1880006603

**Comment by LionCityGaming** [comment]
> I can confirm also this is happening on my end as well.
> 
> **EDIT** Followed this link and it's working now as expected: https://docs.linkwarden.app/self-hosting/installation
> 
> Perhaps the Readme here could point to them instead?

Installing it using these instructions worked. Not too sure which step I probably missed caused the issue.
