### ISSUE TITLE
Readable format when clicking link icon

### ISSUE THREAD

**Issue by awptechnologies** [linkwarden/linkwarden#417]
I personally believe 100% the Readable format should be the option when clicking icon of link. The way it is now makes me wonder what the difference of this is compared to a bookmark. With the readable format you are still able to scroll inside text boxes and you can rest assured the website is the exact same as the moment you saved it since it is stored locally.

**Comment by curtismchale** [comment]
Even an option to choose your preferred format would be great. Some would want to go back to the bookmark in question, while others would want to choose one of the preserved formats.

**Comment by daniel31x13** [comment]
@curtismchale That option is already available in the `/settings/preference` page:
![image](https://github.com/linkwarden/linkwarden/assets/93432314/02207854-cde6-4fea-b4ff-3abd937aa446)

I just forgot to close this issue as complete.

**Comment by curtismchale** [comment]
@daniel31x13 so it is and I missed it. Thanks.

**Comment by huyz** [comment]
This issue can be closed now.
