### ISSUE TITLE
Addition of Default Sort Order Setting

### ISSUE THREAD

**Issue by ochtum** [linkwarden/linkwarden#419]
Currently, the default sort order is set to date. With over 1000 bookmarks, this makes it difficult to find what I'm looking for. I would like to request the addition of a setting to make the default sort order alphabetical by name.

**Comment by voron69-bit** [comment]
Can we get any movement on this? It's been over a year. Is anyone still working on this project?

**Comment by daniel31x13** [comment]
Sorting links was implemented months ago, just forgot to close it as complete.
