### ISSUE TITLE
Support subfolder

### ISSUE THREAD

**Issue by snickers2k** [linkwarden/linkwarden#424]
Support subfolder in collections

Additional context
"Bookmarks manager in Browser like Chrome support subfolder. When export it from Chrome and try to import it into Linkwarden, it will generate quiet lots of collections. Is that possible to support subfolder (or sub-collections), to make it easier to manager?"

but it's not only about chrome imports. subfolders is a great thing anyway

**Comment by e-p-s** [comment]
we can use tags instead, but yes, i am organizing my notes and bookmarks in folders, too. so why not offer this option.

+1 from me

**Comment by wioch** [comment]
+1 as well, 
I can already see a couple of my collections to be even more organized via subdirectories

**Comment by snickers2k** [comment]
oh, i can for sure see how it's more organized :D
for me, i imported chrome bookmarks, starting from around 20 top-folders , more or less pretty organized .. but in linkwarden?
<img width="1135" alt="Bildschirmfoto 2024-01-15 um 22 22 20" src="https://github.com/linkwarden/linkwarden/assets/5986024/7bed65ba-a366-4f1d-a364-ccad34379997">
:D

**Comment by jcolinger3** [comment]
Very much in favor of this feature request.  Without it, the UI is lacking... and imports create a disorganized mess.

**Comment by MYX-GitHub** [comment]
+1 on nested categories!!!

Include a configuration option when displaying a category to just show links in the selected category, or show links in selected category AND sub-categories.

**Comment by krth8** [comment]
+1 here as well. 

I would love to share a particular collection with sub folders to keep it tidy and cover more. In my case: a collection of tutorials and links for a single software but with lots of different categories.

**Comment by nyrixx** [comment]
+1 
linkhoarder apparently setup for first time and went to import my neatly categorized nested folder bookmark collection (~2600) and now I have signed up for a 2nd job apparently tagging them all to make sense of the mess it imported.

**Comment by daniel31x13** [comment]
This feature has been released in [v2.5.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.0).

Let me know what you guys think!

**Comment by need4swede** [comment]
I created a parent collection, then created two sub-collections.
Is there a way to have the sub-collections appear as 'folders' within the parent collection?
I want to create a 'Public' collection and create sub-collections, but have them all be accessible via the parent 'Public' collection (given all the sub-collections are also shared).

One work-around I can think of would be to create links within the parent collection of each nested sub-collection, but that's very tedious.

**Comment by thumsj138** [comment]
@need4swede +1.

 Is it possible to show sub-collections inside the parent collection (like folders) ?

Thanks for all ;-)
