### ISSUE TITLE
batch editing

### ISSUE THREAD

**Issue by snickers2k** [linkwarden/linkwarden#425]
**Is your feature request related to a problem? Please describe.**
i have imported hundreds of bookmarks via chrome import , but since there is no subfolders, it got messy.
even worse, there is no batch-editing to delete all that mess.

**Describe the solution you'd like**
batch-editing for sorting and deleting

**Comment by jcolinger3** [comment]
+1 for batch editing

**Comment by Chay751** [comment]
+1

**Comment by patienttruth** [comment]
Batch editing would be awesome. This ties to #307, #433, and #466

**Comment by daniel31x13** [comment]
This feature has been released in [v2.5.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.0).
