### ISSUE TITLE
Something went wrong while retrieving the file size.

### ISSUE THREAD

**Issue by e-p-s** [linkwarden/linkwarden#427]
I want to send the page to Linkace from Chrome Extension and got "Something went wrong while retrieving the file size.":

Extension Version 1.2.5
Installed Linkwarden Version not visible. Latest from today available 20240115.

![image](https://github.com/linkwarden/linkwarden/assets/42796829/cd16dae7-9b65-4902-ad11-2d76bac4630f)

Page:
https://xdaforums.com/t/dabdream-dab-player-for-usb-adapters.4638309/

**Comment by bgrejo** [comment]
Same error here...

**Comment by Majoraslayer** [comment]
I'll pitch in and mention I'm having the same problem here with most of the sites I try to add to Linkwarden.  I'm running the Docker install on Ubuntu 23.04.

**Comment by daniel31x13** [comment]
This should help: https://github.com/linkwarden/linkwarden/issues/381#issuecomment-1872982427

**Comment by gladiatormax** [comment]
> This should help: [#381 (comment)](https://github.com/linkwarden/linkwarden/issues/381#issuecomment-1872982427)

Not the same error in that post.
Same issue here -> error retrieving file size.
I am on v2.4.8

**Comment by daniel31x13** [comment]
Added a new release which fully resolves this issue:
https://github.com/linkwarden/linkwarden/releases/tag/v2.4.9
