### ISSUE TITLE
no matching manifest for linux/arm/v8 in the manifest list entries

### ISSUE THREAD

**Issue by MasterChief220** [linkwarden/linkwarden#429]
While trying to install using docker on raspberry pi os (model 3b I get the following error).

For more context I run the command docker compose up -d
[+] Running 0/1
 ? linkwarden Pulling                                                                                                                               3.4s 
no matching manifest for linux/arm in the manifest list entries. 

At first I was getting this error: 
docker compose up -d
[+] Running 1/2
 ? linkwarden Pulling                                                                                               3.0s 
 ? postgres Error                                                                                                   3.0s 
no matching manifest for linux/arm/v7 in the manifest list entries

But i managed to fix it by manually pulling postgres. However Im still getting the first error so how do i fix it.

**Comment by b-onc** [comment]
Hello, I am getting the same error on Raspberry Pi 4b+. How did you fix it?
