### ISSUE TITLE
Request: Customize Link Images

### ISSUE THREAD

**Issue by lwelyk** [linkwarden/linkwarden#432]
I'd like to be able to more visually navigate my collections, but most either have a blank nothing behind the favicon or only sometimes a blurry screenshot of the page. I'd like the ability to override these with custom images if needed or pull in the opengraph image or something, just to help make it look a bit nicer.

**Comment by hermann1514** [comment]
Yes, I would like that too. Just like homarr - so that the dashboard is clearer

**Comment by mayberts** [comment]
I too would like to see custom images and favicons

**Comment by Aetherinox** [comment]
This is the one and only reason I don't use Linkwarden on a regular basis. Some of the stuff is not visually appealing, and it drives me crazy.

**Comment by beancaper** [comment]
It looks like standardized icons are in the roadmap but I much prefer being able to upload an image file!

**Comment by daniel31x13** [comment]
[Done!](https://github.com/linkwarden/linkwarden/releases/tag/v2.8.0) :)

**Comment by Aetherinox** [comment]
@daniel31x13 Thanks a bunch for this.

Also, please check:
- https://github.com/linkwarden/linkwarden/issues/844

Docker image is outdated.
