### ISSUE TITLE
Something went wrong while retrieving the file size

### ISSUE THREAD

**Issue by Peter-Go** [linkwarden/linkwarden#446]
**Describe the bug**
When adding a URL that has multiple sub domains to a collection causes an error "Something went wrong while retrieving the file size"

Example of the URL:
https://alpha.bravo.charlie.domain.net/

**To Reproduce**
1. Go to +
2. Click on New Link
3. Enter Link
4. Click Create Link
5. Error 

**Expected behavior**
Add link to collection

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Edge
 - Version 120.0.2210.144

Linkwarden version: v2.4.8

**Comment by daniel31x13** [comment]
This was fixed in [v2.4.9](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.9)
