### ISSUE TITLE
Reddit Links not Archiving

### ISSUE THREAD

**Issue by mfeuhrer** [linkwarden/linkwarden#447]
**Describe the bug**
When scraping reddit links, the preview returns an error due to a "network policy". This is likely due to Reddit closing their API. 

**To Reproduce**
1. Add any website from reddit (for instance: https://www.reddit.com/r/BlueIris/comments/fz79fo/high_cpu_usage/)
2. Allow archiving process to complete
3. Observe an output that beings "whoa there, pardner!"

**Expected behavior**
I would expect to see an accurate archive of the thread that was stored.

**Screenshots**
![Screenshot 2024-01-29 095916](https://github.com/linkwarden/linkwarden/assets/6989367/bdfc11e1-94c1-4e5c-9a93-1e54f9c1996c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 120.0.6099.227

**Comment by daniel31x13** [comment]
Not a bug, Reddit is forcing users to login first since it's detecting the the request was made by a bot...
