### ISSUE TITLE
Is saving websites as WARC files supported?

### ISSUE THREAD

**Issue by Victor239** [linkwarden/linkwarden#449]
**Is your question related to a problem or code? Please describe.**
Saw an old closed issue regarding this but no answer so far https://github.com/linkwarden/linkwarden/issues/1

**Describe what you've tried to solve this question**
WARC isn't mentioned anywhere else as far as I can see.

**Include any code or screenshots (if applicable)**
N/A

**Additional context**
I'd like to use this file format to export archived websites as it's the most widely used archive format.

**Comment by daniel31x13** [comment]
That issue was for the old version of linkwarden, it's not in the scope of this project since it's already preserving links in 4 different format (alongside the archive.org copy):

<img width="740" alt="image" src="https://github.com/user-attachments/assets/f692e9fc-a3e6-4986-a72c-07807ed8ef58">
