### ISSUE TITLE
Login via REST API

### ISSUE THREAD

**Issue by JGeek00** [linkwarden/linkwarden#450]
I want to log in to my self hosted Linkwarden using the REST API, but I don't find how to do it. On the [API documentation](https://docs.linkwarden.app/api/overview) it mentions how to register an user, but not how to log in to an existing user.

**Comment by crkos** [comment]
It is possible, This is basically what i had to do to make it work with Extension, You can take a look at my implementation in the extension in the actions and what calls that, or if you want to go and read the documentation of next-auth (or see what is called when you log in into Linkwarden) [https://next-auth.js.org/getting-started/rest-api](url)

https://github.com/linkwarden/browser-extension/blob/main/src/%40/lib/auth/auth.ts

**Comment by JGeek00** [comment]
@crkos i have checked your implementation and I have done the same:
1. Get the csrf token with the ``/auth/csrf`` endpoint
2. Call to ``/auth/callback/credentials`` with the following form data, being callbackUrl ``"$baseUrl/login"``:
```dart
{
        "username": Uri.encodeFull(username),
        "password": Uri.encodeFull(password),
        "redirect": false,
        "csrfToken": Uri.encodeFull(csrfToken),
        "callbackUrl": Uri.encodeFull(callbackUrl),
        "json": true,
      }
```

But I receive a 302 from the second endpoint. Do you know why this can happen?

**Comment by crkos** [comment]
Mmm not really, did you send it as 'Content-Type': 'application/x-www-form-urlencoded'?, I think this is the only way to make it work, other thing is that you may already have a cookie set

**Comment by JGeek00** [comment]
Yes, I am adding the content type. I'm working on a Flutter mobile application but I cannot make to work the follow redirect after the response of that second endpoint. It appears that flutter's http package doesn't support follow redirect for post requests, so I'm getting a 302.

**Comment by JGeek00** [comment]
Now that the API token section is available this is no longer necessary

**Comment by Madh93** [comment]
@JGeek00 Did you solve it with the API Token? Could you share an example? :pray:

**Comment by Sabin-DC** [comment]
I'm still getting "You must be logged in" in spite of using an API key
