### ISSUE TITLE
Failed login viv Linkwarden browser extension

### ISSUE THREAD

**Issue by Milamber07** [linkwarden/linkwarden#462]
Hi,

I've installed LinkWarden via docker-compose on a port different to 3000. It is operating as intended via WEB.
Using browser extension LinkWarden gives an error during the login stage:
```
Error
Something went wrong, try again please.
```

<img width="406" alt="Screenshot 2024-02-09 at 23 46 15 copy" src="https://github.com/linkwarden/linkwarden/assets/25886632/346ef415-c312-422e-8aeb-684751e13fb2">

 - OS: MacOS 14.3
 - Browser: Brave
 - Version: 2.4.9

Expected result: successful login via browser extension.

**Comment by daniel31x13** [comment]
You need to set the port back to 3000, we currently don't support ports other than 3000.
(But it's definitely something were considering to fix in the future...)

**Comment by Milamber07** [comment]
> You need to set the port back to 3000, we currently don't support ports other than 3000. (But it's definitely something were considering to fix in the future...)

@daniel31x13 Hi,
Do you mean browser extension won't work with port different to 3000?
P.S. Linkwarden itself is working as intended and reachable on 7461.

**Comment by daniel31x13** [comment]
Sorry for the late reply, yes it shouldn't be working on other ports.
You can see the browser extension will work fine by running the instance on port 3000.

**Comment by Milamber07** [comment]
@daniel31x13 
I see. Port 3000 it is :)
Thanks for the reply!

**Comment by alexdelprete** [comment]
Hi @daniel31x13, has this been fixed?

I'm having the same issue.

**Comment by alexbelgium** [comment]
Hi, it doesn't work for me even with port 3000

**Comment by alexdelprete** [comment]
Unfortunately I have to confirm that it happens even when port 3000 is used.

**Comment by b52src** [comment]
same not working with port 3000 either

**Comment by daniel31x13** [comment]
Hey could you make sure you have the latest version of the extension and the app?
```
App: v2.5.1
Extension: v1.2.6
```
Because things are working fine on my end...

**Comment by alexdelprete** [comment]
v2.5.1 and 1.2.6 checked. Same issue, I also tried the new SSO option, same thing:

![image](https://github.com/linkwarden/linkwarden/assets/7027842/ea38615c-0df2-42e8-8eb7-9529052fbb39)

**Comment by DomenicF** [comment]
@alexdelprete I am getting these errors only when I choose a tag. Try just saving the link without anything optional entered and see if it works.

**Comment by locodwr** [comment]
> For me I'm getting a 404 here is the error, using the HA addon to self host for deployment by @alexbelgium, version being used is 2.5.1 [alexbelgium/hassio-addons#1302 (comment)](https://github.com/alexbelgium/hassio-addons/issues/1302#issuecomment-2025024452)
> 
> DNS being used is Cloudflare I've tried with and without the record being proxied. with nginx as the proxy manager onprem.
> 
> ![image](https://private-user-images.githubusercontent.com/12497632/317738529-b8845384-22ff-4148-a422-dde3008ab684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTU1MjEsIm5iZiI6MTcxMTY5NTIyMSwicGF0aCI6Ii8xMjQ5NzYzMi8zMTc3Mzg1MjktYjg4NDUzODQtMjJmZi00MTQ4LWE0MjItZGRlMzAwOGFiNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA2NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NjgwYzI4M2VjODI2NjlkNWQxNTczZjI0OTY4M2RiYzZmYzg3MmUxMjdlMTU3ZjNhZDM4YmU1ODhkNjg5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SzldYFeGX5I2K6PziunDsyyi1TSisn_rgRDM6_mS-mo)

I have exactly the same situation

**Comment by FabienNaslin** [comment]
Same problem with cloudflare & npm onprem :)

thanks

**Comment by kWAYTV** [comment]
Any updates on port changes?

**Comment by Bobo-amg** [comment]
What is happening with this? I cannot enter the local url. Get the same error message as above.

**Comment by simonmcnair** [comment]
it cannot be hard to get the extension to add a custom port.  All it needs to do is default to 3000 and change the url to , for example http://thisisatest:3675 if the port is 3675.  It cannot be that hard surely ?

**Comment by simonmcnair** [comment]
MY apologies, my issue is with floccus not supporting alternate ports rather than linkwarden
