### ISSUE TITLE
Login window is not there

### ISSUE THREAD

**Issue by whazza1983** [linkwarden/linkwarden#473]
Hello, I installed linkwarden successfully!
But the login window doesn't appear.
The registration window is available and you can also enter data.
I use Debian 12 and I only have Docker and Portainer installed, nothing more.
![linkwarden](https://github.com/linkwarden/linkwarden/assets/51747568/20361e6b-1808-4e19-bd3f-acc38ee33320)

**Comment by daniel31x13** [comment]
Add this to your environment variables:
```
NEXT_PUBLIC_CREDENTIALS_ENABLED=true
```

**Comment by whazza1983** [comment]
Thanks so much
