### ISSUE TITLE
Will the snapshot be automatically saved when I enter the link?

### ISSUE THREAD

**Issue by klsdfjo** [linkwarden/linkwarden#475]
I found that it seems that I have to manually click the "Refresh Preserved Formats" button.I wish it could be saved automatically

**Comment by daniel31x13** [comment]
> Will the snapshot be automatically saved when I enter the link?

Yes, the “Refresh Preserved Formats” button is a for when the archived formats were tampered, otherwise there is a background script which archives each links 10 by 10 until every link is archived.
