### ISSUE TITLE
Epub archive support

### ISSUE THREAD

**Issue by rutkai** [linkwarden/linkwarden#496]
**Is your feature request related to a problem? Please describe.**
It'd be great to have the possibility to create epub archives of saved links. Epub is compatible with all e-book readers and is optimized for reading, it is the best format for storing news, blog posts, articles, etc.

**Describe the solution you'd like**
A similar solution to PDF archiving:
![image](https://github.com/linkwarden/linkwarden/assets/1587720/e4916dc7-2743-42b2-930d-3a234452804d)

**Additional context**
Reference implementation: #487

**Comment by shaked8634** [comment]
This is a great feature for me along with OPDS to sync into [Koreader](https://github.com/koreader/koreader) on an eBook reader.

**Comment by daniel31x13** [comment]
This is out of this project's scope, but thanks for bringing it up!
