### ISSUE TITLE
Scrolling down to display more links when link count exceeds 20 does not work

### ISSUE THREAD

**Issue by nyrixx** [linkwarden/linkwarden#501]
**Describe the bug**
Self hosted installation, ubuntu 22.04. repeatable in both v2.4.9 and v2.5.0. Going to any collection or the All links section when viewing in the tiled and list views usually gets stuck showing only 20 links. some outliers will show a few more but never the total amount within the collection or when all links is selected.

**To Reproduce**
1. Go to all links or any collection where link count exceeds 20
2. Scroll to bottom of list
3. no additional links load or display

**Expected behavior**
Either entire quantity of links loads after navigation or link list expands as scrolling down to load additional links until total amount is displayed and scrollable.

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 22H2 19045.4046
 - Browser: Firefox 122.0.1, Chrome 122.0.6261.111

**Comment by daniel31x13** [comment]
I wasn't able to reproduce this, mind if I ask what is the resolution of your monitor?

**Comment by daniel31x13** [comment]
If you have a high resolution display shrink your browser height and let me know if the issue persists.

**Comment by derchr** [comment]
I have the same issue on Firefox, only ever 20 entries are shown for each collection. Even when shrinking the browser window and refreshing, it does not show any more.

Sometimes it does work in Chrome, but even there showing "All links" does not work.

**Comment by sheslily** [comment]
Any update or fix for this? I use Firefox on a high res monitor and it still doesn't show all entries.

**Comment by daniel31x13** [comment]
There is already a fix, just define a environment variable named `PAGINATION_TAKE_COUNT` and set it to a number that exceeds the number of links on your screen, something like 50:
```
PAGINATION_TAKE_COUNT=50
```

**Comment by sheslily** [comment]
I am still running into a similar issue but its with multiples of 50 instead of 20. I have hundreds of links so I think it might struggle with that many links. Is there a way to switch to normal pagination instead?

Also as a side note I tried querying the API to get all my links but I was limited to 50 - where should I look for the query parameters to get all of them since I didn't see it in the API docs.
