### ISSUE TITLE
Wrong version in "See what's new..." banner

### ISSUE THREAD

**Issue by patienttruth** [linkwarden/linkwarden#505]
First off, hats off to the dev team. The new features are great and much appreciated. Batch editing is epic! and I've just got started looking through it. **Thank you!**

**Describe the bug**
V2.4 is shown/linked in banner when logging into Linkwarden

**Expected behavior**
Show current version in banner, if at all.

**Screenshots**
![image](https://github.com/linkwarden/linkwarden/assets/105557996/ac0ba720-d29d-4677-9131-d54c8a9732dc)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Librewolf
 - Version 121.0-1

Also tried with Chrome 122.0.6261.111

**Additional context**

**Comment by patienttruth** [comment]
I tried with a second browser to see if it was cache on my end. Same thing. 

Earlier when I updated I didn't realize the update worked because I was basing it off this banner.

**Comment by daniel31x13** [comment]
I also noticed this right after the docker container was built and forgot to update it, gonna fix it in the next release.

Thanks for pointing it out tho!

**Comment by patienttruth** [comment]
> I also noticed this right after the docker container was built and forgot to update it, gonna fix it in the next release.
> 
> Thanks for pointing it out tho!

You're on it!
