### ISSUE TITLE
Starring of an article

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [linkwarden/linkwarden#506]
**Is your feature request related to a problem? Please describe.**
Some articles/links are so good, one needs to "star" them to easily peruse them when revisiting.

**Describe the solution you'd like**
A feature to star an article that can be used to filter articles and see which ones are starred

**Describe alternatives you've considered**
Maybe another tag based solution, though this again is clunky and not fit for purpose.

**Additional context**
NA

**Comment by daniel31x13** [comment]
That's actually already possible, just instead of "Star" we have "Pinned".
