### ISSUE TITLE
Allow manual uploading of PDF files to the Linkwarden repository

### ISSUE THREAD

**Issue by BlueBull010** [linkwarden/linkwarden#516]
### **Is your feature request related to a problem? Please describe.**
See [here](https://github.com/linkwarden/linkwarden/issues/489) for a problem description. Basically, some PDF files added directly to Linkwarden are not preserved and after discussing it, the most likely cause is protections against automated requests  present on that domain. [This is an example](https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-esxi-vcenter-802-vsphere-with-tanzu-installation-configuration.pdf), it's a VMware PDF file from vmware.com and Linkwarden doesn't want to preserve it. Other PDF files from other domains do work

### **Describe the solution you'd like**
Being able to manually upload a PDF file would enable us to still preserve a PDF when it can't be preserved automatically by Linkwarden, whether that's because of protections against automated requests present on that domain or some other reason. 

For websites that can't be preserved it would also enable us to either use a button "save to PDF", if there is one on that website, and upload that to  Linkwarden or use a "print to PDF" virtual PDF printer to generate a PDF version of the website. Windows has such a virtual PDF printer built-in these days. I haven't yet encountered websites that can't be preserved but if there are PDF files where this is the case, there are likely also websites where it's impossible and being able to upload PDF files would enable us to at least preserve a PDF version of those

### **Describe alternatives you've considered**
I have considered trying to inject the PDF file somewhere into the Linkwarden filesystem manually, or something similar, so that I can perhaps fool it into thinking it is a PDF file that was preserved by Linkwarden itself. However I have not yet tried this and it would only work for the on-premise version of course, not for the cloud version. A cleaner solution would be the above-described

### **Additional context**
This is just a nice-to-have, so of course not a priority or anything. It might also be harder to implement than I suspect (this is usually the case, I know from my friends who are developers) or there might be blockers to this that I haven't considered

In any case, thanks for this fantastic tool. I use it daily and have both (multiple) on-premise instances and a cloud subscription. I just can't believe I didn't find this sooner, it would have saved me so much time and headache

Cheers

Tom

**Comment by daniel31x13** [comment]
Hey this will be implemented soon!

Will also add support for uploading images as well, and the step after that would probably be modifying the browser-extension to have like a web-clipper functionality to be able to store information behind a login/paywall as well.

**Comment by BlueBull010** [comment]
> Hey this will be implemented soon!
> 
> Will also add support for uploading images as well, and the step after that would probably be modifying the browser-extension to have like a web-clipper functionality to be able to store information behind a login/paywall as well.

Oh wow, I didn't expect it to be implemented, let alone soon and with additional functionality even. That is awesome, very glad to hear it. Thanks for that, you guys rock and so does Linkwarden!

**Comment by daniel31x13** [comment]
Added in [v2.6.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.6.0).
