### ISSUE TITLE
Are snapshots overwritten?

### ISSUE THREAD

**Issue by geedmo** [linkwarden/linkwarden#532]
I read in other issue that there is a script which archives each links 10 by 10 until every link is archived .
If a link is already archived, will it be overwritten?  If so, could this be prevented?

**Comment by daniel31x13** [comment]
No overwrites, archived links aren't touched unless you either delete the link, or by clicking on "Refresh Preserved Formats" button in the Preserved Formats modal:
![image](https://github.com/linkwarden/linkwarden/assets/93432314/305c2120-4a3f-444d-9b8a-b649838480b6)
