### ISSUE TITLE
Requesting demo instance (or even screenshots) for Linkwarden

### ISSUE THREAD

**Issue by grand-lotus-iroh** [linkwarden/linkwarden#544]
I recently discovered linkwarden.app, but I'm hesitant to provide my credit card information for a trial and demonstration. Currently, I'm quite satisfied with linkding and espial, and I'm not inclined to pay for pinboard due to its simplicity.

I believe it would be beneficial if there was a demo option setup on a $2/mt VPS to show people linkwarden. This could potentially generate excitement among users and customers.

I understand the strategy of not providing a demo as part of the sales funnel, but it feels a bit inconvenient. Surely, there must be consideration given to hosting a resettable demo. Or provide screenshots or video walk-thru.

**Comment by daniel31x13** [comment]
Demo instance will be released soon, thanks for pointing it out!

**Comment by daniel31x13** [comment]
Closing due to completion.
