### ISSUE TITLE
Feature Request: Indexing / Searching of Link Content

### ISSUE THREAD

**Issue by joeyame** [linkwarden/linkwarden#548]
**Describe the solution you'd like**
In addition to having searchable link names and descriptions, I would like to search the archived text in the link. With the `Readable` archive format, this could be a fairly easy thing to set up, and it would have huge utility.

As a programmer, I am often faced with searching the same task months apart, and some searches require some work to find the right information. It would be nice to archive the link that actually solved the problem, then when I have the problem again I can skip all the work to find that link again.

As it stands, with the current setup, I could see myself collecting a plethora of links such that finding the link I need is impossible or too overwhelming.

**Alternatives**
I could just copy all relevant text into the link description, but then it gets to be too much, and I'm storing the text twice on my server instead of just once.

**Comment by skyrocknroll** [comment]
Looking for the same feature

**Comment by daniel31x13** [comment]
This is already possible, you just need to filter by "Full Content" while searching for a link:
![Screenshot 2024-05-09 at 3 48 28 PM](https://github.com/linkwarden/linkwarden/assets/93432314/9951ccce-00c6-4572-a08f-12140c9f19d7)

**Comment by skojin** [comment]
Since filter params not in URL, I need a way to set this option by default

**Comment by joeyame** [comment]
> This is already possible, you just need to filter by "Full Content" while searching for a link:
> ![Screenshot 2024-05-09 at 3 48 28 PM](https://github.com/linkwarden/linkwarden/assets/93432314/9951ccce-00c6-4572-a08f-12140c9f19d7)
> 

I didn't even think to look there, Daniel! This is a great service, and that full text search worked like a charm!

**Comment by joeyame** [comment]
> Since filter params not in URL, I need a way to set this option by default

@skojin, maybe make a new issue for that? I'm closing mine because the original problem is no longer there

**Comment by orels1** [comment]
My apologies for reviving this thread, but this is the only place I seen anything relevant mnentioned.
Has this changed? Does this only work with AI features enabled?
I do not get the same filter icon when searching like when using linkwarden 2.10 self-hosted

**Comment by QuaCKeReD** [comment]
> My apologies for reviving this thread, but this is the only place I seen anything relevant mentioned. Has this changed? Does this only work with AI features enabled? I do not get the same filter icon when searching like when using linkwarden 2.10 self-hosted

Same here, just setup a 2.10 self-hosted instance, moved all my bookmarks from raindrop.io and now cant search content 😟

**Comment by orels1** [comment]
A-ha! Thank you! I was using the pre-configured "app" in the Unraid app directory.
Set up meili and the relevant variables - and now it works perfectly!
