### ISSUE TITLE
Cant add simple link (!)

### ISSUE THREAD

**Issue by bryanhunwardsen** [linkwarden/linkwarden#549]
**Describe the bug**
Trying to add the following link fails:
`"https://www.costco.com/lauretta-6-piece-leather-power-reclining-sectional-with-power-headrests.product.4000114286.html"`
It appears simply "https://costco.com" cannot be added to linkwarden

**To Reproduce**
1. Click "New Link" button on main page
2. Paste in link provided above
3. Click "Create Link"
4. Creating Toast with spinner appears on top middle of page, never goes away until page refreshed,
5. Link never created, no error displayed (no way to access/dump log files from UI 😣)
6. (Other links are still able to be added without issue, but not this one)

**Expected behavior**

- Link should be created
- Failure to create should display meaningful error
- Ability to review/access/dump/download the log file from (at least admin) UI without needing to access container - in order to provide better bug reports(!) 

**Desktop (please complete the following information):**
-LinkWarden: 2.50 and 2.51
 - OS: Win10x64
 - Chrome
 - All latest

**Comment by daniel31x13** [comment]
Fixed in [v2.5.2](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.2), please note that you'll need to add the following to the env file: `IGNORE_URL_SIZE_LIMIT=true`.

**Comment by bryanhunwardsen** [comment]
@daniel31x13 I just pulled either 2.5.2 or 2.5.3, its hard to tell because you missed updating the version on the 2.5.3 release and it has code specific to this feature. Im just not sure if the fix in 2.5.3 was absolutely necessary for the costco link to add or if the changes in 2.5.2 were fully sufficient.

I notice 2.5.3 does not have the green verified by github checkmark previous releases have. I dont know if either of these have an impact on docker compose pulling the latest release image.

Costco did bookmark! It did take 5-6 seconds, it seems like an opportunity to spawn the data scraping as a background process so that the simple link can be committed immediately freeing the UI for additional action.

Thanks again!

**Comment by daniel31x13** [comment]
> you missed updating the version on the 2.5.3 release and it has code specific to this feature

Yep, my bad.

> It did take 5-6 seconds

The reason to that is some links hate when you `fetch` them programmatically and they just get stuck without displaying any errors...
