### ISSUE TITLE
In Firefox only displays 20 entrys

### ISSUE THREAD

**Issue by swoop124** [linkwarden/linkwarden#552]
**Describe the bug**
I have multiple collections, one of them is over 30 Entries/Bookmarks. There are only 20 of them dispyed in Firefox. In Edge more are loaded when i get to the bottom of the page.

**To Reproduce**
1. log in to linkwarden,
2. goto the collection with more than 30 Entries
3. scroll down to the bottom
4. after 20 Entries (bottom of page) no more Entries are loaded

**Expected behavior**
load all 35 or more Bookmarks to display

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox 124.0.2
 - Linkwarden: v 2.5.1

**Comment by daniel31x13** [comment]
Hey sorry for the late reply, add the following to the env file and let me know how it goes:
```
PAGINATION_TAKE_COUNT=50
```

That's a problem in higher resolution monitors where the overflow is not shown after 20 links since all of them are fitted inside the screen...

**Comment by swoop124** [comment]
hello,

thanks for the answer.
now i see all 37 Entries.

regards
