### ISSUE TITLE
Some websites block archival process.

### ISSUE THREAD

**Issue by luigifcruz** [linkwarden/linkwarden#561]
Some websites are inaccessible to the archival process. Not sure if a solution is feasible.

- https://www.digikey.com/en/products/detail/analog-devices-inc./DC1524A-A/4890577
- https://www.trulia.com/building/caspian-260-brooklyn-basin-way-oakland-ca-94606-2710623398
- https://www.apartments.com/caspian-oakland-ca/pp0w7es (this one never gets added, it just hangs)
- https://indico.fnal.gov/event/46955/contributions/204594/attachments/138539/173497/GPU_Direct_IO_with_HDF5.pdf (can't download the PDF)

**Comment by daniel31x13** [comment]
This is because some websites prevent automated requests from accessing their content. 
There's an upcoming file upload feature which lets users take the screenshot manually.

**Comment by luigifcruz** [comment]
Cool, file uploading is a very welcome feature and will mostly fix this problem.

I'm still a bit curious about how the websites are identifying this as an automated request. It can't be IP flagging because this is using my home IP address. Perhaps User-Agent matching?

**Comment by daniel31x13** [comment]
Oh, if that's the case you can add the following to the env file, it should fix most of the links:
```
AUTOSCROLL_TIMEOUT=1000 # Amount in seconds (default 30)
NEXT_PUBLIC_MAX_FILE_SIZE=1000 # Amount in MB (default 30)
IGNORE_UNAUTHORIZED_CA=true
IGNORE_HTTPS_ERRORS=true
```

**Comment by daniel31x13** [comment]
Also for the third link, just merged a hotfix in [v2.5.2](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.2), please note that you'll need to add the following to the env file as well: `IGNORE_URL_SIZE_LIMIT=true`.

**Comment by luigifcruz** [comment]
The patch for the third like indeed works. The URL is added to the system. But it also breaks the archival of every URL. I noticed a new error popping up:

```
Linkwarden    | [1] Processing link https://hackaday.com/2024/04/14/hackaday-links-april-14-2024/ for user 1
Linkwarden    | [1] Something went wrong while retrieving the file size.
```

**Comment by luigifcruz** [comment]
Regarding the other variables, they unfortunately didn't help in preventing the detection of an automated request. 😕

**Comment by daniel31x13** [comment]
> But it also breaks the archival of every URL.

Forgot to add a single line, fixed in [v2.5.3](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.3).

**Comment by luigifcruz** [comment]
Thanks! I'll test this soon. 

Regarding the bot detection circumvention, looks like you are using the vanilla Playwright which makes it very easy for the website to detect an automated request. I tried the [example](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth#usage) of Puppeteer Stealth plugin for Playwright and was able to successfully circumvent bot detection in 2 of the 3 links. Looking at the archival code, very little modification would be necessary to support plugins.

**Comment by daniel31x13** [comment]
That’s a great news!
If you want, make a PR for this and I’ll be merging it.
Otherwise I’ll be getting to it soon.

**Comment by daniel31x13** [comment]
Hey, just a follow up on this.
Looks like the `playwright-extra` plugin was last updated over a year ago.
At first I thought we can use the `puppeteer-extra-plugin-stealth` plugin without `playwright-extra`. So for that I'm gonna have to close this issue for now.

Let me know if you found any other options.
