### ISSUE TITLE
Add logging level env variable

### ISSUE THREAD

**Issue by hazzuk** [linkwarden/linkwarden#569]
**Is your feature request related to a problem? Please describe.**
Currently linkwarden logs a huge number of Prisma queries, creating unnecessarily massive log files.

**Describe the solution you'd like**
Add an environment variable to control the level of logging (e.g. loglevel=warn, or info, or error)

**Describe alternatives you've considered**
Not logging anything, this can be done when using docker compose with
```
logging:
      driver: none
```
But now I'm not going to have any logs, making things harder to report and fix when errors do occur.

**Additional context**
What is currently logged (and what should remain the default for easier developer support and debugging), would be classed as info. As was previously discussed https://github.com/linkwarden/linkwarden/issues/355.

**Comment by Brock1998** [comment]
Glad I cam here! Atleast now I know there is a workaround!

**Comment by daniel31x13** [comment]
[Done!](https://github.com/linkwarden/linkwarden/releases/tag/v2.8.0) :)
