### ISSUE TITLE
No login screen, just Sing Up over and over

### ISSUE THREAD

**Issue by lockheed** [linkwarden/linkwarden#591]
**Describe the bug**
I just installed Linkwarden on docker and when I get to the url, I can only see Sign Up option. After Signing up, I am back to the same screen. I cannot Sign Up again, because I get a message user already exists. But there is nowhere an option to login. Only  Sign Up. 

![image](https://github.com/linkwarden/linkwarden/assets/3472480/ca8a3a38-3c48-4981-872c-d3145a627c31)

**Desktop (please complete the following information):**
 - OS:  Arch
 - Browser Firefox

**Comment by mathieukergosien** [comment]
You can try to add NEXT_PUBLIC_CREDENTIALS_ENABLED=true to your .env vars, didn't work for me but seems to work with most people.

**Comment by lockheed** [comment]
Thanks, that indeed worked.

**Comment by mathieukergosien** [comment]
I don't know why this isn't the default value...

**Comment by lockheed** [comment]
@daniel31x13 has this been set as a default value?
