### ISSUE TITLE
login form asking me to fill in all fields

### ISSUE THREAD

**Issue by mlause** [linkwarden/linkwarden#593]
**Describe the bug**
When trying to signup I get a please fill out all fields error when all the fields are filled out. I'm sell hosting this.

**To Reproduce**
Happens every time I hit the sign up button.

**Expected behavior**
It should sign me up for an account.

**Screenshots**

**Desktop (please complete the following information):**
MacOS
Latest version of Chromium and Safari on Ventura.

<img width="1048" alt="image" src="https://github.com/linkwarden/linkwarden/assets/103668347/5cf27a80-2bb5-443d-b71b-f8a9259bac30">

**Comment by daniel31x13** [comment]
What does your environment variables look like? Seems you've defined the email variables on the docker image.

The container was built without the email fields.

**Comment by Bene-33** [comment]
i had the same problem first, but i can confirm if you disable the email variables the sign up will work. 
```
NEXT_PUBLIC_EMAIL_PROVIDER 
EMAIL_FROM
EMAIL_SERVER
```

**Comment by nickian** [comment]
So does this mean the self-hosted Docker version just doesn't support email verification or password recovery? Why isn't this even mentioned in the docs?

**Comment by daniel31x13** [comment]
@nickian it is supported, but you just need to build the app manually. Not using Docker.
