### ISSUE TITLE
Save sorting in Collections or Global Sorting order

### ISSUE THREAD

**Issue by skalec** [linkwarden/linkwarden#599]
Can You Please add a global sorting order or save order to Collection. Every Time I must change my Order to A-Z manually.

**Comment by Just4Link** [comment]
+1

**Comment by rom169** [comment]
+1

**Comment by skalec** [comment]
Next update and nor sort option? Really?

**Comment by dohlin** [comment]
Would LOVE to see this...definite +1

**Comment by daniel31x13** [comment]
This is already implemented in the latest release, so sort persists among pages

**Comment by Crush-RY** [comment]
Hello, thank you so much for providing this feature! However, I encountered some issues during use and would appreciate some assistance. It seems that currently the feature can only sort links, but I was hoping to sort entire collections, as well as collections within browser extensions. I’ve named my collections using a hierarchical structure like "1-XXX, 2-XXX, 2-1-XXX, 3-XXX," but when I try to save content through the browser extension, the collections aren’t displayed well enough, making it difficult to quickly find the location I want to save to.

I'm not sure if I'm using it incorrectly or if the feature doesn’t yet support this kind of hierarchical sorting. I would greatly appreciate any suggestions or support for optimizing this. Thanks again!
