### ISSUE TITLE
Fix & Improve Bookmark Import

### ISSUE THREAD

**Issue by theAkito** [linkwarden/linkwarden#623]
Due to #271 I'm stuck importing a HTML bookmarks file, which is roughly 25MB.

As a quickfix, the limit could be increased to some 50MB or something, however a long-term fix is desperately needed.

1. The allowed size needs to be configurable via an environment variable.
2. If there is an error like this, the Web UI should display a proper error message, instead of letting the wheel spin forever.
3. All this needs to be documented well.

**Comment by daniel31x13** [comment]
I’ll get to this soon, the reason that it’s hardcoded is because I really didn’t think anyone would really exceed the limit, if I recall correctly a 10mb file is literally tens of thousands of links :D

**Comment by theAkito** [comment]
> if I recall correctly a 10mb file is literally tens of thousands of links :D

Hmmm, not sure then if there are differences in the format. I sure have lots of links, but I'm pretty sure it's not even remotely close to 2x tens of thousands.

Any quick way to check the amount of links in the HTML? I don't trust the content, before it is put inside the HTML.

**Comment by theAkito** [comment]
I just checked the amount of items, which shows up, when viewing a selection menu for which backup to restore. The backup has about ~15k items.
Maybe the HTML is bloated with something?

**Comment by theAkito** [comment]
@daniel31x13

Could you tell me where to change the limit? Maybe I could offer a Pull Request, depending on the workload.

**Comment by theAkito** [comment]
Hey @daniel31x13

**Comment by wlofman021** [comment]
you can help me?


Sent from Yahoo Mail for iPhone


On Thursday, July 4, 2024, 2:36 AM, Akito ***@***.***> wrote:




Hey @daniel31x13

**Comment by daniel31x13** [comment]
@theAkito to change the limit on your side, you'll need to change the [following](https://github.com/linkwarden/linkwarden/blob/4640c1c966d37b7fc22e4ebfcb244d03da1d6d82/pages/api/v1/migration/index.ts#L11) line.
I just updated the dev branch and a new `IMPORT_LIMIT` environment variable will be available in the next release.

**Comment by a20eac1d** [comment]
I would like to mention another issue to @daniel31x13 that may be related to this issue.

Exporting my bookmarks from Pocket gets me an HTML file that includes metadata such as the timestamp of when the link was saved.

Linkwarden seems to ignore this metadata and instead sets the "Save date" to today. Is this a bug or does the Import Feature simply not work with this yet?

Please let me know what you think. Thanks!

**Comment by daniel31x13** [comment]
@a20eac1d I think there was a release which this was fixed, which version are on?

**Comment by a20eac1d** [comment]
@daniel31x13 v2.5.2 in a Docker container

**Comment by daniel31x13** [comment]
Fixed in [v2.6.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.6.0).

**Comment by a20eac1d** [comment]
@daniel31x13 It is **NOT** fixed in v.2.6.2. The issue still occurs and Linkwarden does NOT import the timestamp. All imported items are dated to the day of import.

**Comment by theAkito** [comment]
@a20eac1d

Chill out...



> @theAkito to change the limit on your side, you'll need to change the [following](https://github.com/linkwarden/linkwarden/blob/4640c1c966d37b7fc22e4ebfcb244d03da1d6d82/pages/api/v1/migration/index.ts#L11) line. I just updated the dev branch and a new `IMPORT_LIMIT` environment variable will be available in the next release.

As you see, you need to set the `IMPORT_LIMIT` environment variable, for example, to `50`.

@daniel31x13

That said, this needs to be properly documented and accounted for in the setup. For example, just raising this limit is not enough in a real world use case, as the default timeout limit for NGINX is lower than the time needed for the import to finish. This remark has to be documented, as well.

Additionally, it would help, if imports had proper error handling and ideally a progress bar. The only way I know, what's happening, is by opening the developer console inside the browser. For any non-developer end-user there, the `Importing bookmarks...` thing just stays there forever and is "stuck", even though it already failed in the background.
This UX issue needs to be fixed.

**Comment by theAkito** [comment]
> having the same issue importing a linkwarden html backup into linkwarden itself only 2400 links tho

Did you set the `IMPORT_LIMIT` environment variable?
