### ISSUE TITLE
Docker image is seriously oversized

### ISSUE THREAD

**Issue by romu70** [linkwarden/linkwarden#629]
**Describe the bug**
The 2.5.3 docker image size is 2.6 GB. There is a serious oversize problem.

I run several web services on my nas, through Docker containers, and none is so heavy.

**Comment by theAkito** [comment]
I can take over this one!

**Comment by daniel31x13** [comment]
@theAkito sure, go for it!
Just note that the target branch is the `dev` branch…

**Comment by stumpylog** [comment]
Does linkwarden only use Chromium from Playwright?

Based on this line: https://github.com/linkwarden/linkwarden/blob/9a287d1aef44b5e842b25bae8a56c9bcf0fd4927/lib/api/archiveHandler.ts#L1

I believe that is correct, so you could also reduce the image size with `playwright install --with-deps chromium` instead of installing all browsers.  Happy to add that to #688 if correct

**Comment by daniel31x13** [comment]
@stumpylog Oh sure! I didn't know playwright had that flag

**Comment by vordenken** [comment]
Is there any progress on this? The docker file is now 4.4 GB in size...

**Comment by jspn-creative** [comment]
I understand that considerable time and energy has already been put into this and I'm not familiar enough with this codebase to be making suggestions, but if only for my own enlightenment I had a few questions & wanted to reiterate @theAkito's findings regarding what I think could be the real culprit behind the image size.

1. If Alpine is still presenting issues that prevent Playwright from functioning, have we considered keeping Debian for the build stage as before, and using a [distroless](https://github.com/GoogleContainerTools/distroless) image for the runtime stage? A shell can be added along with whatever else is necessary to execute the chromium binary, etc.

2. As far as dependencies, there also appear to be some low-hanging fruit in the `package.json`. Are there legitimate reasons why tailwind-merge, eslint & eslint-config-next, all of the @types packages, and csstype aren't included under dev dependencies? None of these _should_ be needed at runtime and thus would be pruned with the help of the multi-stage dockerfile if they were included as dev dependencies instead.

3. ...unless dev dependencies are being bundled anyways? I noticed that dockerfile doesn't have `ENV NODE_ENV=production` anywhere in the runtime stage and yarn isn't passed any flags to tell it not to bundle dev dependencies when it builds, and I believe @theAkito mentioned as much already in their PR. If dev dependencies are likely being included in the final image where they don't have the benefit of being compressed, that would be the bulk of the image size I imagine (I don't actually have an environment set up to double check, sorry).

4. Finally, I think that all of the [suggestions made by winston0410](https://github.com/linkwarden/linkwarden/pull/637#issuecomment-2215326635) are reasonable, but would add that [linkedom](https://github.com/WebReflection/linkedom) could be a much lighter weight alternative to the largest dependency, jsdom.

Thanks for bearing with me as I poked around a little bit. I'm not particularly experienced with much of this tech stack so please forgive any ignorance.

**Comment by seang96** [comment]
Utilizing this project, [docker-repack](https://github.com/orf/docker-repack), may be able to help reduce the image size further without crazy modifications?

**Comment by daniel31x13** [comment]
Done: https://github.com/linkwarden/linkwarden/releases/tag/v2.8.0
