### ISSUE TITLE
[Linkwarden in unreachable but container is up]

### ISSUE THREAD

**Issue by SamarthGhante** [linkwarden/linkwarden#644]
Description: I have hosted linkwarden on my cloud server using docker; I have setup a nginx proxy for it, the application endpoint randomly just stops responding (doesn't open at all; just keep loading).

I have to manually restart the container to make it work again, but again at any time it becomes dead (application, but the container is still up).

**Comment by daniel31x13** [comment]
Can you provide more details? 

> just keep loading

Like when adding a link?

It might be a faulty link that's causing this, you need to use PM2 to auto-restart it when something fails...

**Comment by SamarthGhante** [comment]
> Can you provide more details?

 Its Quite Random, no fix steps to reproduce the same! :(

> Like when adding a link?

Yeah mostly after adding a link through the extension.
> It might be a faulty link that's causing this, you need to use PM2 to auto-restart it when something fails...

After Reinstalling from stracth (Fresh Install) It seems to be fixed. (BTW I was using arm64 docker images.)
