### ISSUE TITLE
Client Side Exception when accessing a non-public collection

### ISSUE THREAD

**Issue by Energetic6877** [linkwarden/linkwarden#646]
**Describe the bug**
When accessing a collection via the exposed link (like `https://example.org/public/collections/4`) a client side exception in NextJS can occur which is not caught anywhere. This happens when the collection is not saved after making it public.

**To Reproduce**
1. Create a new collection
2. Go to Share & Collaborate and make the collection public
3. Forget to save
4. Access the provided link

**Expected behavior**
Proper handling of the 400 error and the subsequent errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/0bf2bded-f410-4893-ab77-bdb95d473b7d)
![image](https://github.com/user-attachments/assets/14218a31-a854-4038-bb36-ec2c73d72d11)

**Desktop (please complete the following information):**
 - OS: Linux Pop Os (also happened to my boss using Apple)
 - Browser: Firefox 127.0, Chromium 125.0.6422.112

**Comment by daniel31x13** [comment]
This will be fixed soon

**Comment by daniel31x13** [comment]
Closing since it's already fixed.
