### ISSUE TITLE
Cannot add users to collection

### ISSUE THREAD

**Issue by Energetic6877** [linkwarden/linkwarden#647]
**Describe the bug**
When writing any text into the member field it does not send any request and instead shows an error in the console.

Also, as a side note, I am pretty sure it would fail anyway, as we use Google SSO and the username of all our users is null.  

**To Reproduce**
1. Create a new collection
2. Go to Share & Collaborate
3. Write something into the member field and press the button next to it
4. See the console log

**Expected behavior**
Being able to add members using the share feature

**Screenshots**
![image](https://github.com/user-attachments/assets/7bcea263-4ffe-4781-8965-d1392c98f159)

**Desktop (please complete the following information):**
 - OS: Linux Pop OS
 - Browser: Firefox 127.0

**Comment by daniel31x13** [comment]
This issue is most likely fixed in the new version since users can now modify their settings when using SSO.
Lmk if the problem persists.
