### ISSUE TITLE
Bulk editing from search page

### ISSUE THREAD

**Issue by ispjstfu** [linkwarden/linkwarden#652]
I have just started using this tool and I really like it but for my initial sorting where everything is mess, I would love a feature where I could search for "color", look it over, click the pen and then bulk/batch edit all of the relevant results to move them into a collection. Currently the pen does not show up when searching, only when in other views like "All links".

My workaround is searching with the browser which works okay but not ideal.

**Comment by daniel31x13** [comment]
Hey sorry for the late response, this was already implemented in the latest release!
