### ISSUE TITLE
Some images do not display correctly after uploading

### ISSUE THREAD

**Issue by lilacpixel** [linkwarden/linkwarden#657]
**Describe the bug**
When uploading images in version 2.6.0, some images will appear to upload correctly, but the thumbnail will never display on the front end. Instead, the card for that image will show the "loading" graphic indefinitely.

**To Reproduce**
1. Upload an affected image, such as [this one](https://github.com/user-attachments/assets/167bf2b5-9eac-4829-ae04-3389870069ec).
3. Wait for upload to complete.
4. Check the dashboard to verify that the image does not display.

**Expected behavior**
All uploaded images should display a matching thumbnail on the card for that image.

**Desktop:**
 - macOS 14.5
 - Firefox 128.0
 - Version 2.6.0

**Additional context**
There are no errors in either the Docker logs or the web console.

Thanks for taking a look!

**Comment by daniel31x13** [comment]
Strange, this is working for me:
<img width="637" alt="image" src="https://github.com/user-attachments/assets/46946e69-5448-4d55-984d-9f935a165111">

**Comment by lilacpixel** [comment]
It looks like the image was added as a link in your screenshot, but I'm seeing the behavior when uploading images directly--you can see the "loading" effect is still present instead of the thumbnail on this card.

![Screenshot 2024-07-22 at 12 16 41 PM](https://github.com/user-attachments/assets/b5ca2dbb-2663-4e24-9d5a-3a58fe5d2e03)

I did notice that one error appears in the web console on first load, though it disappears on subsequent refreshes for some reason.

```
Error: Loading initial props cancelled
    _getData NextJS
main-772348ed454bbb86.js:1:60894
```

Is there an environment variable or another setting I can toggle to get more verbose logging? I'm not sure where to go from here, since the server mostly seems to think that everything is smooth sailing…

**Comment by daniel31x13** [comment]
Hey I found the issue, it's because you need to increase the `PREVIEW_MAX_BUFFER` in the environment variables. The unit is MB.

So something like this should do the job:
```
PREVIEW_MAX_BUFFER=10
```
