### ISSUE TITLE
v2.6: missing link to pdf preserved format

### ISSUE THREAD

**Issue by mdlaat** [linkwarden/linkwarden#659]
Since update to v2.6 i am missing links to some preserved formats of links saved in earlier versions.

If I go to the context menu of a saved link, and click on 'preserved formats' I am not seeing a previous generated pdf which I saw in earlier versions. I do p.e. see a format 'Readable'. That link lead to xxxx?format=3. If I then, in y browser, manually change that link to xxxx?format=2 I see the previous saved pdf version. However, the link to that pdf version is missing in the overview of preserved formats.

I can 'Refresh Preseved Formats' after which all available formats are shown again, but this is 1) a lot of work for a lot of links and 2) follows that link today and not when I saved that link.

**Comment by daniel31x13** [comment]
Just found out what's the problem, you'll need to run a script right after I push the changes and everything will go back to normal (and yes, your data is safe). Sorry for the inconvenience...

**Comment by daniel31x13** [comment]
Fixed in [v2.6.1](https://github.com/linkwarden/linkwarden/releases/tag/v2.6.1).
