### ISSUE TITLE
A more compact UI

### ISSUE THREAD

**Issue by jcolinger3** [linkwarden/linkwarden#664]
I'm sorry all contributors... maybe I'm not understanding Linkwarden.  I don't find it very usable in terms of the UI.

On a 21.5" iMac with native resolution (1920x1080) and 100% normal zoom in browser with Linkwarden 2.6, I see eight bookmarks on the entire screen in "small icon view", eleven in the new view, and seven in the horizontal list view.

I don't find the UI usable at all.  I want to see more bookmarks to make the access to links/info faster.
Seems almost easier to just create a Google Doc formatted to my liking and share it with myself (and others) rather than use Linkwarden with eight links on the entire screen.

Is there any plan to address UI tweaks?  Is there a file that controls the elements that I can try to tweak?

**Comment by Kahz3l** [comment]
Then you should use something like linkace.

**Comment by jcolinger3** [comment]
Thanks, but the LinkAce - Is Private - Yes or No is lacking the Sharing feature that Linkwarden has that is very compelling.

**Comment by daniel31x13** [comment]
@jcolinger3 hey sorry for the late reply, could you do me a favour and do a quick personal survey on two questions:
1. In your opinion how many links should be visible on a 1980x1080 display?
2. Should there be multiple links in each line?

Also it’d be a bonus if you can share like a mockup of what you have in mind.

Trying to create a compact view and needed suggestions…

**Comment by jcolinger3** [comment]
For the text list view.  I'd prefer a multi-column display (either 2 or 3 columns w wrap), though others might not.

**Comment by daniel31x13** [comment]
WIP :)

<img width="551" alt="image" src="https://github.com/user-attachments/assets/d7611683-4bb0-4953-8078-39206cadfa75">

**Comment by linuxd3v** [comment]
omg came here to request the same feature.      

Need more compact layout - most of my bookmarks are for internal tooling, so linkwarden being on remote server won't be able to fetch those screenshots anyways.  

Basically my ideal layout would completely bare and utilitarian, just a link name:        
https://raw.githubusercontent.com/pawelmalak/flame/master/.github/home.png  

^ so  I could see as many bookmarks as possible to fit there      :pray:

**Comment by daniel31x13** [comment]
[Done](https://github.com/linkwarden/linkwarden/releases/tag/v2.8.0) :)
