### ISSUE TITLE
How do you even login?

### ISSUE THREAD

**Issue by feld** [linkwarden/linkwarden#673]
I've tried v2.5.3 and v2.6.0 -- you sign up for an account and then there's no login form on the page????

**Comment by feld** [comment]
oh gosh, do NOT copy `.env.sample` to `.env`. The blank ENVs break the application. Only set the values in `.env` that you really need.

**Comment by Trevo525** [comment]
I'm not sure by reading your last comment. Did you fix it or not? 

If you haven't fixed it, are you using docker, compose, or other?

**Comment by daniel31x13** [comment]
> The blank ENVs break the application.

Oh so that's where all those issues were coming from. 🤦
Been receiving many similar issues and didn't know how to reproduce it.
@feld big thanks for pointing this out! Just pushed a change where it fixes this...
