### ISSUE TITLE
Bug in editing link in collection collection

### ISSUE THREAD

**Issue by ilourt** [linkwarden/linkwarden#695]
**Describe the bug**
I have a shared collection on which I am admin and not owner. In this collection I can not edit links (nor name, description, ...).

**To Reproduce**
1. Add a link to a shared collection
2. Click on `edit link` as admin user (not owner)
3. Update a field
4. Save
5. Everything seems ok but when you try to edit link again there is an error
6. The link has not been updated

**Expected behavior**
The link must be have been updated and there must not been some errors

**Screenshots**
<img width="1618" alt="SCR-20240808-oavj" src="https://github.com/user-attachments/assets/f7a67c05-8437-40ca-a412-770b0d709b94">

**Desktop (please complete the following information):**
 - OS: Mac OS 14.6
 - Browser: Brave
 - Version 1.68.134

**Comment by Nicolab** [comment]
Same here

**Comment by daniel31x13** [comment]
Does this issue persist in v2.7.0?

**Comment by ilourt** [comment]
@daniel31x13 everything works fine with last version.

Thanks for your work :)

**Comment by Nicolab** [comment]
Everything works, thank you @daniel31x13 😉
