### ISSUE TITLE
Healthcheck endpoint?

### ISSUE THREAD

**Issue by zodac** [linkwarden/linkwarden#696]
**Is your question related to a problem or code? Please describe.**
Is there any healthcheck/status/info endpoint for the system, that doesn't require authentication?

**Describe what you've tried to solve this question**
I checked the [API documentation](https://docs.linkwarden.app/api/overview), but didn't see one. Potentially I could use one of the existing APIs as a healthcheck (if they return an empty list the at least the system is online), but I think they all require the user to be authenticated.

**Additional context**
I'd like to use [Uptime Kuma](https://github.com/louislam/uptime-kuma) for monitoring, and Authentik for authentication on Linkwarden, so a public healthcheck endpoint would be useful for this case.

**Comment by daniel31x13** [comment]
Perhaps you can use the [`/api/v1/logins`](https://cloud.linkwarden.app/api/v1/logins) route? That doesn't require any authentication and it is used to get the available login methods.
