### ISSUE TITLE
Trailing slash is removed from saved links

### ISSUE THREAD

**Issue by Jburso** [linkwarden/linkwarden#697]
**Describe the bug**
Saving a link with a trailing slash causes the slash to be removed. This can cause the saved link to break.

**To Reproduce**
Click "Add New Link"
Create a link to a webpage that requires a trailing slash, e.g. https://cs.lmu.edu/~ray/notes/gasexamples/
Attempt to open the now-broken link in Linkwarden

<img width="441" alt="image" src="https://github.com/user-attachments/assets/3289992e-ef3a-4390-9648-4247d83f8cfe">

**Expected behavior**
Trailing slashes should not be removed from saved links.

**Comment by daniel31x13** [comment]
Thanks for pointing this out, I'll be fixing it soon.

**Comment by daniel31x13** [comment]
Pushed the fix to the `dev` branch, will be merging it soon:
https://github.com/linkwarden/linkwarden/commit/8758976f8d1d5b96ed8367c431fe8b5be782843d
