### ISSUE TITLE
How to use extension or app with selfhosted instance?

### ISSUE THREAD

**Issue by slrgt** [linkwarden/linkwarden#700]
Hi, I installed Linkwarden locally using docker and want to use the browser extension for firefox and the ios app but since I don't have a domain attached to it i'm not sure what to place in the section it asks for a domain. I want to use the extension on the same computer im running linkwarden and the iphone app on the same wifi

**Comment by daniel31x13** [comment]
Use your computer's local ip address as the domain. 
e.g. if the ip address of the computer you're hosting Linkwarden on is `10.10.1.2`, use `https://10.10.1.2` (or if you're not using ssl, `http://10.10.1.2`) as the domain for the extension/mobile app.
