### ISSUE TITLE
[BUG] Copy to Clipboard button not working

### ISSUE THREAD

**Issue by deffcolony** [linkwarden/linkwarden#702]
**Describe the bug**
The Copy to Clipboard button does not copy the access-token into clipboard the console says:

`Uncaught TypeError: navigator.clipboard is undefined`

`access-tokens-be43b94f2e616854.js:1:11674 /_next/static/chunks/pages/settings/access-tokens-be43b94f2e616854.js`

**To Reproduce**
1. Navigate to: settings --> access-tokens
2. Click on New Access Token
3. Click Copy to Clipboard (which does not copy to clipboard)

**Expected behavior**
That the Copy to Clipboard copies the access-token to clipboard

**Screenshots**

https://github.com/user-attachments/assets/15f4ab0d-8460-43c9-b0f2-d4b18de0801b

![image](https://github.com/user-attachments/assets/92f2d5be-d695-4e24-ad96-8f147d0d9213)

**Desktop (please complete the following information):**
 - Docker
 - Floorp browser 11.16.0 (64-bit)
 - Linkwarden v2.6.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by daniel31x13** [comment]
You need to host Linkwarden on HTTPS instead of HTTP, this is because the [`navigator.clipboard`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) property needs to be executed over a secure context.
