### ISSUE TITLE
Property 'id' does not exist on type 'AccountSettings'

### ISSUE THREAD

**Issue by elmarsto** [linkwarden/linkwarden#73]
![image](https://github.com/linkwarden/linkwarden/assets/315987/be6c71bf-d922-4605-92ca-5b0bbe98e155)

**Comment by daniel31x13** [comment]
Hey there, I’ve haven’t pointed the docs in the readme yet but if you want an early access, [here it is](https://docs.linkwarden.app/getting-started/self-hosting).

**Comment by elmarsto** [comment]
I followed the instructions at https://docs.linkwarden.app/getting-started/self-hosting. The error remains:

![image](https://github.com/linkwarden/linkwarden/assets/315987/f7d68308-0805-4694-acea-e47c95b07854)


Notes:

 - I switched from `npm` to `yarn` as per the instructions
 - I verified that postgresql is set up to allow local logins (passwordless)
 - I created an .env file to the specification indicated
 - The error message is the same as before

**Comment by daniel31x13** [comment]
Did you run `yarn prisma migrate deploy`?

**Comment by daniel31x13** [comment]
Also make sure you pull the repo again, just pushed some changes and improvements/bug fixes.

**Comment by elmarsto** [comment]
Whoops, I must have missed `yarn prisma migrate deploy`. Thank you~

**Comment by elmarsto** [comment]
AWARENESS: this is not a bug on linkwarden, but `yarn prisma migrate deploy` fails on NixOS because prisma does not compile on nixos and precompiled engines are unavailable. 
![image](https://github.com/linkwarden/linkwarden/assets/315987/f63fb8e0-a7ba-43bd-aa1d-88c9fc48150e)

**Comment by daniel31x13** [comment]
@elmarsto hey, I know it's late but just wanted to mention the error is resolved and the problem wasn't NixOS.

You need to run `yarn prisma generate` right before you run `yarn build`.

Sorry for late response.
