### ISSUE TITLE
Names of the links added in Linkwarden 2.5 to visible in 2.7

### ISSUE THREAD

**Issue by Lorak-mmk** [linkwarden/linkwarden#738]
**Describe the bug**
After updating from 2.5 to 2.7 nearly all of the names of the links disappeared from dashboards.
I think in 2.5 title of the page was fetched and put in description field, and the description field was shown as the name if the name field was empty. Now in 2.7 it looks like description field is never shown in the list, breaking all the links added in previous version.

**To Reproduce**
1. Install Linkwarden 2.5
2. Add some links
3. Update to 2.7
4. Links don't display names, only the domain.

**Expected behavior**
I expected to still see some name of the link.

**Screenshots**
![image](https://github.com/user-attachments/assets/c053d527-53de-4ff8-92a2-8fcade985679)
First 3 links are added on 2.7 - as you can see the names are displayed. The rest were added on 2.5 and have no names.

**Desktop (please complete the following information):**
Client: Firefox 129 on Fedora 39
Server: Fedora 39, Linkwarden running using Docker.

**Additional context**
I had ~400 links added in 2.5 - not sure if it matters.

**Comment by daniel31x13** [comment]
This should answer your question: https://github.com/linkwarden/linkwarden/releases/tag/v2.6.1

Basically you need to run this script: https://github.com/linkwarden/linkwarden/blob/main/scripts/migration/v2.6.1/index.js

**Comment by Lorak-mmk** [comment]
It looks like the script fixed most of the links, the rest I'll fix manually.
I should have been reading all release notes, sorry :(
Thanks for the help and great software!
