### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by elmarsto** [linkwarden/linkwarden#75]
Currently building fails on NixOS because of Prisma does not compile under NixOS and there are not precompiled nixos binaries offered:

![image](https://github.com/linkwarden/linkwarden/assets/315987/70b8d1e8-9ad6-4028-af26-6a079cf52b49)

There are various mitigations that are known for this (although I am just coming to them fresh and don't really yet understand them):

https://github.com/pimeys/nix-prisma-example/blob/main/flake.nix

https://github.com/steinerkelvin/alfred/commit/3f84b6194164e6260fa76c28d82cfe4251f57ba0

https://github.com/prisma/prisma/issues/3026

Someone (possibly myself) should get this building on NixOS and submit a PR consisting of a `flake.nix`, etc.

**Comment by daniel31x13** [comment]
Currently our primary focus is on Mac/Linux/Windows, but I’ll leave this issue open for now just to see if anyone can handle it…

**Comment by elmarsto** [comment]
NixOS is a Linux distro.

**Comment by daniel31x13** [comment]
Edited… my bad. :P

**Comment by daniel31x13** [comment]
Please note that the main reason is because there’s a todo list I’ve got to finish soon, and I just can’t add up tasks, at least not until the previous tasks are done.

**Comment by elmarsto** [comment]
I'll take this one on. I'm a NextJS developer and a NixOS user and I've got the time. 

For my own future reference, see NixOS packages `prisma-engine` and `nodePackages.prisma`

**Comment by daniel31x13** [comment]
Sounds good, thank you.

**Comment by daniel31x13** [comment]
Gonna close this for now, if you managed to fix this by yourself, awesome! otherwise I'll be getting to it later...

**Comment by daniel31x13** [comment]
Just wanted to point out that this issue is fixed, the problem wasn't the OS, you just need to run `yarn prisma generate` before building the app.

Sorry for the late response.

**Comment by ccalhoun1999** [comment]
> I'll take this one on. I'm a NextJS and NixOS user and I've got the time.
> 
> For my own future reference, see NixOS packages `prisma-engine` and `nodePackages.prisma`
@elmarsto 
Sorry to necro this, but did you ever get anything going?

**Comment by elmarsto** [comment]
Afraid not!

**Comment by GoogleBot42** [comment]
@elmarsto  I'd look at this PR since it supposedly has linkwardnen working there. I'll be trying it out pretty soon. https://github.com/NixOS/nixpkgs/pull/347353

Edit: Yup seems like linkwarden is working for me on NixOS.
