### ISSUE TITLE
Open bookmark in new card in the background with middle mouse button

### ISSUE THREAD

**Issue by em411** [linkwarden/linkwarden#750]
**Is your feature request related to a problem?**
I'm used to opening multiple links in the background using the middle mouse button, which by default in Chromium opens the link in a new card in the background. I'm always frustrated when it switches to scroll mode in Linkwarden and forces me to use ctrl + left mouse button instead.

**Describe the solution you'd like to see**.
Middleclick should open bookmark in new card in background.

**Describe alternatives you've considered.**
None, it's the default behavior in Chromium browsers.

**Comment by daniel31x13** [comment]
I believe middle clicking the link URLs should achieve what you're looking for:

<img width="425" alt="image" src="https://github.com/user-attachments/assets/5712d9b4-364d-4831-8aa2-91b70ee62961">

**Comment by em411** [comment]
I would never have guessed that, but it works. Thanks a lot :)
