### ISSUE TITLE
Cloud Flare "Human Verification"

### ISSUE THREAD

**Issue by patienttruth** [linkwarden/linkwarden#751]
**Describe the bug**
I was trying to backup a set of instructions for servicing a vehicle. 

**To Reproduce**
1. Try to backup - https://www.blauparts.com/blog/ford-f350-rear-differential-fluid-gear-oil-change-diy-dana-80.html#ford-f-350-rear-differential-fluid-change-info

**Expected behavior**
Normal Linkwarden functionality - creat PDF backup of page

**Screenshots**
![Screenshot_20240902-072801_1.png](https://github.com/user-attachments/assets/6254695f-9759-44f4-98ed-a69d62be8ca9)

**Desktop (please complete the following information):**
 - OS: 

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Graphene OS
 - Browser Firefox
 - Version 129

**Additional context**
Version 2.6.2

This may be more of a feature request than a bug, as I know there's only so much Linkwarden can do. If it were possible to initiate a manual verification process to circumvent this barrier that would be sweet, seems like it might be complicated though.

**Comment by huyz** [comment]
See https://github.com/linkwarden/linkwarden/issues/389

**Comment by patienttruth** [comment]
> See https://github.com/linkwarden/linkwarden/issues/389

Thanks. Admittedly I forgot to search "closed" issues.
