### ISSUE TITLE
Fresh Install on Ubuntu 24.01 LTS spams terminal 

### ISSUE THREAD

**Issue by mrbill430** [linkwarden/linkwarden#776]
**Describe the bug**
after bringing up the container for the first time I get a continuous repeating output of the following (and never return to a terminal prompt)

[1] Starting the link processing task
linkwarden-1  | [1] prisma:query SELECT "public"."Link"."id", "public"."Link"."name", "public"."Link"."type", "public"."Link"."description", "public"."Link"."collectionId", "public"."Link"."url", "public"."Link"."textContent", "public"."Link"."preview", "public"."Link"."image", "public"."Link"."pdf", "public"."Link"."readable", "public"."Link"."monolith", "public"."Link"."lastPreserved", "public"."Link"."importDate", "public"."Link"."createdAt", "public"."Link"."updatedAt" FROM "public"."Link" WHERE ("public"."Link"."url" IS NOT NULL AND ("public"."Link"."image" IS NULL OR "public"."Link"."image" = $1 OR "public"."Link"."pdf" IS NULL OR "public"."Link"."pdf" = $2 OR "public"."Link"."readable" IS NULL OR "public"."Link"."readable" = $3 OR "public"."Link"."monolith" IS NULL OR "public"."Link"."monolith" = $4)) ORDER BY "public"."Link"."id" ASC LIMIT $5 OFFSET $6

and it repeats

**To Reproduce**
Spun up a fresh VM of Ubuntu 24.04.1 LTS (proxmox), updated all packages. installed docker per here:
https://docs.docker.com/engine/install/ubuntu/
installed linkwarden per here:
https://docs.linkwarden.app/self-hosting/installation
ran command sudo docker compose up

**Expected behavior**
container to be downloaded, started, and be returned to the command prompt

**Comment by mrbill430** [comment]
solved my own problem...
instructions here work:
https://idroot.us/install-linkwarden-ubuntu-24-04/

looks like the instructions on the linkwarden age leave out installing another package:
sudo apt install git nodejs npm postgresql

and adding these entries into the env file
POSTGRES_DB=linkwarden
POSTGRES_USER=linkwardenuser

**Comment by daniel31x13** [comment]
Gonna mark this issue as solved, please open a new issue if there’s anything else.
