### ISSUE TITLE
Why is there a bookmark limit for self-hosted

### ISSUE THREAD

**Issue by Antebios** [linkwarden/linkwarden#777]
I am self-hosting Linkwarden and imported my bookmarks (~15,000).  The import was successful, but when I attempt to add another bookmark I get this error message that I have reached my limit:

![image](https://github.com/user-attachments/assets/7aa9678d-18af-4f3d-a430-02b66a4c165e)

> Each user can only have a maximum of 30000 Links.

Why?  If I am self-hosting then shouldn't I have as many as I can hold?

**Comment by Antebios** [comment]
Limit is configured via Helm Chart.  Issue is closed.

**Comment by theAkito** [comment]
> Limit is configured via Helm Chart. Issue is closed.

Which Helm Chart? How? Which value is to be configured? [There is no appropriate environment variable documented](https://docs.linkwarden.app/self-hosting/environment-variables).

A while ago, I created my own Helm Chart for Linkwarden, because there was no appropriate one available.

**Comment by theAkito** [comment]
Ah, found the environment variables, which aren't documented anywhere, except in this comment right now...


https://github.com/linkwarden/linkwarden/blob/dbd096ab76edca485f4e03b9c8c772fc3bab964e/.env.sample#L18

**Comment by Antebios** [comment]
I apologize, but closed the issue without documenting the resolution.  Thanks for doing that for me.
