### ISSUE TITLE
Add support for custom featured image/thumbnails to links

### ISSUE THREAD

**Issue by MirazMac** [linkwarden/linkwarden#783]
**Is your feature request related to a problem? Please describe.**
Many websites don't provide a featured image, just the opengraph image of their homepage. In many cases, the featured image does not express the proper context of the saved link. Sometimes they are low res or broken. Featured image is an important visual cue for finding a saved link when scanning the links. And it bothers me that I can't customize that aspect of my collection.

**Describe the solution you'd like**
It would be nice if there is an optional upload field along with an input field in the "Create New Link" and "Edit Link" screens that lets us either upload a custom featured image or specify a direct link for it. It could be under "More Options" so it's not much of a distraction to anyone who doesn't want to use it. Thanks a lot for the awesome app btw!
Something like this:
![image](https://github.com/user-attachments/assets/e7e08e7b-bf8d-4089-a2e7-0d8c50f42c75)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by EssangMichael40** [comment]
Hello. Please I have been trying to reach out to you but it has not been possible. It's about a script I bought. I have been having difficulties.

**Comment by MirazMac** [comment]
> Hello. Please I have been trying to reach out to you but it has not been possible. It's about a script I bought. I have been having difficulties.

I already replied your mail. Provide the purchase code in the email or simply use Envato's comment section to comment, don't stalk me around the internet, wth.

**Comment by daniel31x13** [comment]
This feature will be released in the next version and there’s already an open issue regarding this.
