### ISSUE TITLE
Administration Page - How access ?

### ISSUE THREAD

**Issue by FabienNaslin** [linkwarden/linkwarden#785]
hello, I've noticed that since version 2.6 we've been able to have an administration portal for users. But I can't see how to access it. Do you have a procedure for this?

Thank you

**Comment by daniel31x13** [comment]
Hey sorry for the delay, you need to click on your profile located at the top right and then "Server Administration":
![image](https://github.com/user-attachments/assets/9a102268-18b7-42c5-a406-5f4ab2465748)

Note that this option is only available for the first user which signs up on the platform by default.

**Comment by molnarti** [comment]
the current implementation of this is a bit flaky. it looks like the admin role is determined by the userId, therefore the user with id 1 is the admin. When i was setting up Linkwarden initially, first i created a local user, but then a new OIDC user and deleted the original one. So my user ended up having id 9. So regain the admin rights, i had to change the user id in the database. Luckily it looks like the change of the id got somehow reflected in all the other records related to that user such as links or even access tokens
