### ISSUE TITLE
User registration in selfhosted 

### ISSUE THREAD

**Issue by JanMrlth** [linkwarden/linkwarden#790]
**Describe the bug**

**To Reproduce**
I installed  the latest docker-compose. 
When I configure smtp in the .env and want to register a new user I get an error message, that I have to fill out all the fields.

When I first started the container without the smtp setup it was all fine. I was not able to set an admin user with the env NEXT_PUBLIC_ADMIN= becasue that expects an email? I had no chance to add an Email anywhere. 
When I then added the SMPT settings in the env. I could not login anymore. 

When I clicked on 'send password' it has no email to send it to, because I never entered an email for the account anywhere. 

**Expected behavior**
I need a more specific error message here? I guess I should also enter an email? 

**Screenshots**

![grafik](https://github.com/user-attachments/assets/f82ff47e-6840-4a00-88c2-1d2d55a389b3)

**Desktop (please complete the following information):**
-debian / docker

**Comment by daniel31x13** [comment]
To enable the smtp settings, you’ll need to take the manual installation route. This is because the docker image was built without the smtp settings being defined.

**Comment by JanMrlth** [comment]
Thank you for the Info! I can live without smtp. But then I cannot define an admin?

**Comment by mdlaat** [comment]
Would be nice to  have smtp in non manual installation docker version

**Comment by daniel31x13** [comment]
@JanMrlth `NEXT_PUBLIC_ADMIN` is by default the first user that signs up (1), and if you want to set it to another user you need to set `NEXT_PUBLIC_ADMIN` to the id (not email) of the user in the database.

@mdlaat that's a limitation of NextJS, see https://github.com/vercel/next.js/discussions/17641.
There _are_ hacky ways but it's just not efficient.
