### ISSUE TITLE
How to get links with a particular tag using the API

### ISSUE THREAD

**Issue by ttscoff** [linkwarden/linkwarden#803]
**Is your question related to a problem or code? Please describe.**

I would like to use the API to get the most recent links containing a particular tag (or possibly AND tag combination). The documentation specifies `/api/v1/links?PARAMS` but no list of available `PARAMS` seems to be available.

**Describe what you've tried to solve this question**

I've tried `?tag=TAG` and `?tags=TAG` but neither seem to have an effect.

Is this possible?

**Comment by RyanGreenup** [comment]
Looking at the source code, I think the enum is [types.global.LinkRequestQuery](https://github.com/linkwarden/linkwarden/blob/a71f42af6eb103a439996549a230e083c881dbdb/types/global.ts#L84):


```typescript

export type LinkRequestQuery = {
  sort: Sort;
  cursor?: number;
  collectionId?: number;
  tagId?: number;
  pinnedOnly?: boolean;
  searchQueryString?: string;
  searchByName?: boolean;
  searchByUrl?: boolean;
  searchByDescription?: boolean;
  searchByTextContent?: boolean;
  searchByTags?: boolean;
};
```

So putting that together:

- List all tags
    - `/api/v1/tags`
        - Use that to get a tagID
- List links with a tag
    - `api/v1/links?tagId=40`
- Sort links by most recent
    - `/api/v1/links?tagId=40`

**Comment by ttscoff** [comment]
That helps, thanks.
