### ISSUE TITLE
When I move a folder on the left "Collections" section to reorder them in the order I want them to be, once page is refreshed, they all go back to their default locations

### ISSUE THREAD

**Issue by voron69-bit** [linkwarden/linkwarden#821]
**Describe the bug**
When I move a folder on the left "Collections" section to reorder them in the order I want them to be, once page is refreshed, they all go back to their default locations
**To Reproduce**
1. Move a folder to another location in the heirarchy
2. Refresh page
3. Folder is back to the previous location, I.e not where you want it.

**Expected behavior**
When  I drag a folder to a different location, I expect it to stay there forever.

**Screenshots**
Needs to be done, screenshots won't help.

**Desktop (please complete the following information):**
Doesn't matter
Issue exists all over browser, apps versions of the program.

**Comment by voron69-bit** [comment]
Is anyone still working on this project or is it dead?

**Comment by daniel31x13** [comment]
> Is anyone still working on this project or is it dead?

100% Alive :)
I just don't have the time to go through each issue one by one.

Regarding your issue, I can't seem to reproduce it.
By any chance are you trying to reorder a sub-collection inside another collection? Because that's not supported yet, reordering only works on the root-level of the collection hierarchy.

**Comment by voron69-bit** [comment]
> > Is anyone still working on this project or is it dead?
> 
> 100% Alive :) I just don't have the time to go through each issue one by one.
> 
> Regarding your issue, I can't seem to reproduce it. By any chance are you trying to reorder a sub-collection inside another collection? Because that's not supported yet, reordering only works on the root-level of the collection hierarchy.

That's great! Cause this program is exactly what i want,  I just need to organize. 

Here is a quick video. I imported my bookmarks from an html file. 

https://streamable.com/oc80cu

**Comment by linuxd3v** [comment]
I was going to report the same issue that I thought was a bug, but this comment clarifies it:  
   
> >  By any chance are you trying to reorder a sub-collection inside another collection? Because that's not supported yet, reordering only works on the root-level of the collection hierarchy.  

yeah that's what I was trying to do - reorder subcollections. 
  
I use floccus to then sync bookmars to all the browsers, and after it syncs "folders" are just not where I want them to be. 
the feature where subcollections could be reorder would be much appreciated :pray:

**Comment by linuxd3v** [comment]
@daniel31x13 I can also reproduce the issue @voron69-bit is seeing.  
Top level collections are not reorderable.  Reverting back to original order for me.  
also I couldnt catch it on video - but I think application crashed for me once when I tried reordering .

https://github.com/user-attachments/assets/403c70ee-5e2c-47df-a3c4-75d3a58b0e32

**Comment by voron69-bit** [comment]
That's exactly right.  I'm ok if folders within folders aren't working for reorder,  I can work around that.  But ordering the folders in the root should be possible.

**Comment by daniel31x13** [comment]
Hmm, seems like it only happens on fresh accounts. Tried it on my existing account and it wasn't reproducible, but when I created a fresh account locally I had to play around with it for a bit to get it working properly...

Anyway, gonna fix it. Thanks for pointing it out!

Also @linuxd3v I'll be adding sub-collection reordering as well...

**Comment by voron69-bit** [comment]
Awesome news! Can't wait! This is going to change my life!

**Comment by voron69-bit** [comment]
@daniel31x13 Is there a fix I can implement now to get this to work? Or do you expect a fix "soon"? Cheers!

**Comment by daniel31x13** [comment]
@voron69-bit Like you're looking for the fix itself? [It's already pushed to the dev branch.](https://github.com/linkwarden/linkwarden/commit/836360f99d55f75026afe9f5f1d0a67b7e8a0745#diff-36a469d79d5ae5758868c284678b45d7d43f9239e7f07dd07376a75414a0345c)

But anyway I'd suggest you to wait for the upcoming release which comes with tons of new juicy features :)

**Comment by voron69-bit** [comment]
@daniel31x13 updated to the latest 2.8.1 and this still isn't fixed.

**Comment by voron69-bit** [comment]
Updated to 2.8.3 thinking the fix was in, still doesn't work. Moving folders in any view snaps back to where they were previously.

**Comment by voron69-bit** [comment]
@daniel31x13  ???

**Comment by daniel31x13** [comment]
Can't seem to reproduce this issue, can you verify your instance version from the settings page?

<img width="350" alt="image" src="https://github.com/user-attachments/assets/8f1feb21-f625-4672-aab7-47bd783ed8f1">

**Comment by voron69-bit** [comment]
![image](https://github.com/user-attachments/assets/3a68c315-a9ab-48e8-b6f4-da4a75adc5fc)

**Comment by voron69-bit** [comment]
I'm available to do any troubleshooting I can to help you, I really need this sorted.

**Comment by daniel31x13** [comment]
I think the reason to that is because of the previous misconfiguration of the `collectionOrder` field in the `User` table.

You'll need to reset it back to `[]`.

Or of you don't have any data on your instance, just purge the volumes...

**Comment by voron69-bit** [comment]
> I think the reason to that is because of the previous misconfiguration of the `collectionOrder` field in the `User` table.
> 
> You'll need to reset it back to `[]`.
> 
> Or of you don't have any data on your instance, just purge the volumes...

I have stuff in here, but I can just redo it all if you think that a fresh install will work?

**Comment by daniel31x13** [comment]
Yes, a fresh install should do the job.
You could even test by creating another instance without deleting your current one.

**Comment by voron69-bit** [comment]
THAT WORKED!!!! Closing this out! Thank You!
