### ISSUE TITLE
Fix Bookmark Import

### ISSUE THREAD

**Issue by Fuckingnameless** [linkwarden/linkwarden#826]
how long should it take to import a 22mb file with 2400 links? it's taking hours here

its a backup json from linkwarden itself

**Comment by daniel31x13** [comment]
Few more mins max, it encountered an error. That shouldn’t take too long.

**Comment by daniel31x13** [comment]
Have a look at your logs on the server, might help.

**Comment by daniel31x13** [comment]
> nope, haven't seen it documented anywhere
> 
> the logs don't say anything meaningful

Set the following variable in your `.env` file:
```
IMPORT_LIMIT=30
```
