### ISSUE TITLE
Paste pop-up button disappears

### ISSUE THREAD

**Issue by WinstonSmith73** [linkwarden/linkwarden#828]
**Describe the bug**
Paste button disappears before I can paste link (mobile view - self-hosted)

**To Reproduce**
1. Copy link
2. Load LinkWarden mobile page
3. Tap Plus button
4. Tap "New Link"
5. Tap-and-hold to get Paste button

**Expected behavior**
Use Paste button to paste link

**Resulting behavior**
Paste button appears momentarily then disappears before I can tap it

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 14 (CalyxOS)
 - Browser: Brave, Chromium
 - Version: Brave 1.71.123, Chromium 129.0.6668.81

**Additional context**

Works in Firefox beta - Chrome issue?

**Comment by daniel31x13** [comment]
Does this error persist in v2.8.3?

**Comment by WinstonSmith73** [comment]
It appears to be fixed!
