### ISSUE TITLE
Preserved readable version by default instead of raw link

### ISSUE THREAD

**Issue by QuAzI** [linkwarden/linkwarden#842]
Is there any option to use preserved version by default on click by article, or at least to show this option in quick access?
Other formats are optional as they often look not optimal for content reading by default, same way as source with strange design/banners : https://demo.linkwarden.app/preserved/82?format=1

**Comment by daniel31x13** [comment]
You mean like choose what happens when you click a link? You can already personalize that in the settings.

**Comment by QuAzI** [comment]
Thanks a lot, found it
![image](https://github.com/user-attachments/assets/0a95913f-0b67-4b96-b677-53c3893694ea)
