### ISSUE TITLE
Docker ghcr.io/linkwarden/linkwarden:latest is still pointing to v2.7.1

### ISSUE THREAD

**Issue by arran4** [linkwarden/linkwarden#844]
**Describe the bug**

Docker image on github container registry is 2 versions behind it's v.2.7.1 not v.2.8.1 (or v.2.8.0)

**Comment by Aetherinox** [comment]
Thought I was going crazy. I saw the developer reply to a issue about Linkwarden now having the ability to set custom banners, so I updated, and it wasn't there.

I'm still on 2.7.1

![yjBwYqdi2g](https://github.com/user-attachments/assets/951cb3eb-d25d-4b9f-a33c-711d34debca4)

**Comment by vordenken** [comment]
Yes thanks for opening, thought something in my setup is broken because redownloading the docker image still results in version 2.7.1 :)
You can see it here: https://github.com/linkwarden/linkwarden/pkgs/container/linkwarden

**Comment by Aetherinox** [comment]
Yeah, it appears his last build workflow failed

```
$ next build --ignore-engines
#27 4.115 Unknown or unexpected option: --ignore-engines
#27 4.149 error Command failed with exit code 1.
#27 4.150 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#27 ERROR: process "/bin/sh -c yarn prisma generate &&     yarn build --ignore-engines" did not complete successfully: exit code: 1
```

**Comment by superdong69** [comment]
Same thing is happening to me as well. Using :latest I'm getting 2.7.1. Appears as though a new update was put in to latest as well, so 2.8.0 isn't even accessible, let alone todays update of 2.8.1.

**Comment by voron69-bit** [comment]
Is there a way we can fix this ourselves to get the new updates? Or do we have to wait for @daniel31x13. ?

**Comment by Aetherinox** [comment]
@voron69-bit You'd need to `git clone` this repo to a local folder and create your own image. The repo includes the `Dockerfile` which is the instructions on what the docker image should contain.

```
docker build -t linkwarden .
```

**Comment by daniel31x13** [comment]
There have been some problems with building the image.
For now you need to build the image yourself or wait for the image to be published. 🔜

Thank you for your patience!

**Comment by daniel31x13** [comment]
It's live: https://github.com/linkwarden/linkwarden/pkgs/container/linkwarden

**Comment by Aetherinox** [comment]
Appreciate it.
