### ISSUE TITLE
Saving changes on account settings not possible due to "please enter a valid email address" error

### ISSUE THREAD

**Issue by tom666-debug** [linkwarden/linkwarden#851]
Saving changes on account settings page not possible due to "please enter a valid email address" error
I am facing this issue since I have upgraded to version 2.8.1 today. For me this is reproducible also on fresh installation.

**To Reproduce**
1. Go to 'settings.'
2. Click on 'save changes'
3. See error (screenshot)

**Expected behavior**
Changes will be saved - I dont even know where to enter a "valid email address"

**Screenshots**
![Screenshot 2024-11-14 082407](https://github.com/user-attachments/assets/513dbc93-140b-4485-85f0-a2e7d0865530)

**Comment by Green-Kite** [comment]
Same thing here.

**Comment by stanthewizzard** [comment]
same here

**Comment by daniel31x13** [comment]
The docker image was built without the smtp settings defined. To make use of the smtp variables, you'll need to build the image yourself or take the manual installation.

**Comment by stanthewizzard** [comment]
so if you use the docker image you can't change the settings ?

**Comment by stanthewizzard** [comment]
In my case I need the docker installation and I'm unable to build the docker image.
Why remove such an important settings ?
It make the service unusable

**Comment by Green-Kite** [comment]
@daniel31x13 will the settings be in the next release?

Really sad to see my contribution unusable for me...

**Comment by tom666-debug** [comment]
btw ... building your own image doesn't fix the issue, at least for me.

**Comment by stanthewizzard** [comment]
for the moment reverted to 2.7.1
I can change the settings with that version

**Comment by daniel31x13** [comment]
> so if you use the docker image you can't change the settings ?

No, if you assign the smtp in your environment variables you can't use the docker image properly.

That's a limitation of NextJS, please see https://github.com/linkwarden/linkwarden/issues/225#issuecomment-1762781340
They also have an issue regarding this in their repo: https://github.com/vercel/next.js/discussions/17641

> for the moment reverted to 2.7.1
I can change the settings with that version

You can but the frontend shows nothing related to emails, how are you going to login?

**Comment by tom666-debug** [comment]
> You can but the frontend shows nothing related to emails, how are you going to login?

I dont get it, sorry. Can you please explain a bit more in detail?
In my understanding there a 3 parameters I can set for an user account:
1: Display Name
2: Username
3: Password

To log on I must use "Username" and "Password".

**Comment by stanthewizzard** [comment]
> > You can but the frontend shows nothing related to emails, how are you going to login?
> 
> I dont get it, sorry. Can you please explain a bit more in detail? In my understanding there a 3 parameters I can set for an user account: 1: Display Name 2: Username 3: Password
> 
> To log on I must use "Username" and "Password".

that's my case yes

**Comment by stanthewizzard** [comment]
> @stanthewizzard the smtp settings are mainly for account recovery when you forget the password, what’s the point of having it when you have access to the whole database?

I don't have smtp setting in .env
This is a bug

**Comment by stanthewizzard** [comment]
Better
With a clean docker intall (no data no pgdata)
no smtp settings
when you are log using username and password if you want to change a settings you got "please enter a valid email adress"

**Comment by tom666-debug** [comment]
> I don't have smtp setting in .env

Same here. I dont need email functionality at all. 
All I want to do is change settings for a certain user ... currently not possible with version 2.8.1 (see my screenshot above)

**Comment by stanthewizzard** [comment]
THANK YOU (backup just in case lol)

**Comment by Green-Kite** [comment]
Hi @daniel31x13 
I waited patiently and then pulled again as soon as the job went through. I now have version 2.8.2 in Docker and still get an error when saving:
![Bild](https://github.com/user-attachments/assets/e2f27380-ce4a-4bd0-9021-0708d1cc21c0)

**Comment by stanthewizzard** [comment]
> Issue is still there ... pretty annoying :-/ ![image](https://private-user-images.githubusercontent.com/78903224/386288416-2c9550ce-da4a-4d3e-8a7e-b19c7bc63c8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDMxMjEsIm5iZiI6MTczMTYwMjgyMSwicGF0aCI6Ii83ODkwMzIyNC8zODYyODg0MTYtMmM5NTUwY2UtZGE0YS00ZDNlLThhN2UtYjE5YzdiYzYzYzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE2NDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNWQxYzA3NDU0MmMzNWUyMmEwZGExYjgxZTM4ZThhNWNlMDFmZjU1MWIxZWM1MTUwMWFjZjYwMGUwNTQ5MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OLuKYK7ugMOoV4E8q2kR3O8y2P7dqWI0S1F1i29vIIw)

I'm not the only one :/

**Comment by s7thamon** [comment]
> Issue is still there ... pretty annoying :-/)

Same issue here, trying to update the password on a user and getting that error

**Comment by stanthewizzard** [comment]
Bug is squashed. Thank you

**Comment by tom666-debug** [comment]
I can confirm that the issue is gone with v2.8.3 - Thank you daniel31x13
