### ISSUE TITLE
Open all links

### ISSUE THREAD

**Issue by marc9025** [linkwarden/linkwarden#853]
Hello,
If I use the new function open all links, then only the first link in the collection opens.
![Screenshot 2024-11-14 093709](https://github.com/user-attachments/assets/affa78ef-a69e-4dc5-a464-60e131282745)

**Comment by daniel31x13** [comment]
You'll need to allow popups from that domain inside your browser.

**Comment by marc9025** [comment]
many thanks for the quick response.
Worked great
