### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by quiet2754** [linkwarden/linkwarden#860]
Hello,

I am using Linkwarden installed into a VM.
I need to migrate to a new installation on a new VM.

I didn't find any documentation on how to migrate all the content (accounts, contents...) from the old VM to the new one.
Do you have any documentation please ?

Best regards

**Comment by stanthewizzard** [comment]
Just export one user and import.
If you have more than one user. 
PG import

**Comment by Aetherinox** [comment]
This is more of a PostgreSQL question rather than Linkwarden. There are numerous guides online on how to export your PostgreSQL database and then re-import it to another machine.

To take care of all PostgreSQL databases, you can just use `dumpall`

```
pg_dumpall -U linkwarden > linkwarden_db.sql
```

`-U` being the username of the database.

**Comment by stanthewizzard** [comment]
you should try if you use docker
inside the compose for the pg container

```
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dump:/opt/dump
```

docker exec -u root -t -i name_of_db_cointainer /bin/bash -c "mkdir /opt/dump"

docker exec -u root -t -i name_of_db_cointainer /bin/bash -c 'pg_dumpall -U postgres > /opt/dump/linkwarden_db.sql'

or if no container at all
`pg_dumpall -U postgres > /where_you_want/linkwarden_db.sql`

**Comment by quiet2754** [comment]
Thank you !
Nothing "easy to use" but not complex 👍
