### ISSUE TITLE
Import / export loose timestamp

### ISSUE THREAD

**Issue by stanthewizzard** [linkwarden/linkwarden#861]
Hello

When you export a user and the import it you loose the timestamp of the bookmarks.

Could you make the export with creation date ?

Thanks

**Comment by daniel31x13** [comment]
Next version 🔜

https://github.com/linkwarden/linkwarden/commit/b1a55785b561332b64f76b12ea9b33c57e714ef0

**Comment by stanthewizzard** [comment]
PERFECT
Thanks
