### ISSUE TITLE
CPU hitting 100% while docker is running

### ISSUE THREAD

**Issue by voron69-bit** [linkwarden/linkwarden#868]
**Describe the bug**
With Linkwarden docker running on Unraid server, CPU goes from 5% with it stopped, to 100% running.

**To Reproduce**
Start Linkwarden docker

**Expected behavior**
Shouldn't be using near that much CPU. Have all caching options turned off in user prefs.
![image](https://github.com/user-attachments/assets/34cc8e2d-8099-4b82-bf87-67b75ec00488)

**Screenshots**
![image](https://github.com/user-attachments/assets/bc38f59e-f7fa-4679-b3a5-8e2bb5fb21b1)
![image](https://github.com/user-attachments/assets/5a232ae1-1efc-433c-b01f-68b62ea457a2)

I don't need any of the backing up of pages, snapshots, etc. So I'm not sure why chrome is being spawned in my unraid all over the place killing my CPU. I just want the application doing simple bookmark synching etc.

**Comment by daniel31x13** [comment]
That shouldn't be happening, might be due to the first batch of links before you unchecked all the "formats to save webpages".

Is it still happening?

**Comment by voron69-bit** [comment]
It is, and I noticed it happening in the previous installation, but wanted to fix one issue first. This installation, I unchecked those options PRIOR to importing my HTML file of saved bookmarks. It renders the entire server useless, so I had to end the docker container.
Current state with the Linkwarden docker stopped:
![image](https://github.com/user-attachments/assets/92c8b4a8-1259-419d-88ec-751e3f0f431c)
![image](https://github.com/user-attachments/assets/7243a8d8-1f3b-4aa0-a0e8-c60d6270e517)

**Comment by voron69-bit** [comment]
As soon as I restart it, chrome instances spawn like mad and bring the server to its knees.

**Comment by voron69-bit** [comment]
Is there a way I ca BLOCK chrome from running in this docker instance?

**Comment by voron69-bit** [comment]
@daniel31x13 

Brother, you've got a big problem with this application.
I just completely removed Linkwarden from Unraid. I deleted the database from my postgres server and created a new one. Complete from fresh install.
Installed the community app, started it. Perfect. 5% cpu. Went to URL, created user. Still, perfect.
Went to preferences and unchecked ALL settings. Uploaded my bookmark html file, and IMMEDIATELY I get this:
![image](https://github.com/user-attachments/assets/b0f5ac52-aefc-49ee-92a2-b4c758a4578c)
And my docker logs are spammed with:


[1] Error processing link https://redacted URL.com for user 1: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
[1] Call log:
[1]   - navigating to "img/og-image.jpg", waiting until "load"
[1]
[1]     at handleArchivePreview (/data/lib/api/preservationScheme/handleArchivePreview.ts:26:38)
[1]     at /data/async /data/lib/api/archiveHandler.ts:132:13
[1]     at async archiveHandler (/data/lib/api/archiveHandler.ts:67:5)
[1]     at async archiveLink (/data/scripts/worker.ts:112:7)
[1]     at async processBatch (/data/scripts/worker.ts:135:3)
[1]     at async init (/data/scripts/worker.ts:148:7) {
[1]   name: 'Error'

So even though I've told it DON'T scan the bookmarks, it's still doing it.

**Comment by daniel31x13** [comment]
Hmm, that shouldn't be happening.

Anyway I added an option to disable preservation in this commit: https://github.com/linkwarden/linkwarden/commit/5303d63e4bec6b446d096c5068ccfb343e644d94

Will be ready for the next release soon.

**Comment by superdong69** [comment]
Any idea when this fix will go live @daniel31x13 ?

**Comment by voron69-bit** [comment]
Sorry to be a pain Daniel, any eta on when this fix makes it to current build? I'd love to start using it.

**Comment by daniel31x13** [comment]
Just released a minor version. The image will be ready in the next ~2 hours...

**Comment by voron69-bit** [comment]
That's awesome @daniel31x13 Thank you so much! How do I use this new feature? I've updated it, but don't see any new option in the UI?

**Comment by daniel31x13** [comment]
@voron69-bit You'll need to add the following line to your environment variables:

```
DISABLE_PRESERVATION=true
```

**Comment by voron69-bit** [comment]
THANK YOU SO MUCH @daniel31x13 !!!! It works perfectly! I can't wait to get it how I want it and begin truly utilizing it! Amazing job!

**Comment by Antergosgeek** [comment]
Did this solve the issue for you? I may have to remove the container and start from Scratch, having the exact same issue. Hope adding the environment variable will solve the issue.

**Comment by tmeuze** [comment]
> [@voron69-bit](https://github.com/voron69-bit) You'll need to add the following line to your environment variables:
> 
> ```
> DISABLE_PRESERVATION=true
> ```

@daniel31x13 

Hi, this resolved an issue for me wherein Playwright was just obliterating my CPU, after utilizing [Starwarden](https://github.com/rtuszik/starwarden) to bookmark all of my GH stars. 

But could we get a little explainer on what exactly this variable is doing? Is it disabling the Chromium archiving features entirely? I do hope the [variables documentation](https://docs.linkwarden.app/self-hosting/environment-variables) gets updated to include this description. 

Thank you! Loving LW.

**Comment by daniel31x13** [comment]
@tmeuze 
> Is it disabling the Chromium archiving features entirely?

Hey, yeah that's what it does :)
