### ISSUE TITLE
Browser Extension Error: Required [type]

### ISSUE THREAD

**Issue by dilom** [linkwarden/linkwarden#873]
**Describe the bug**
Trying to create a link from the Browser extension, I get Error: Required [type] when clicking Save. The extension connects to the server and shows the categories,tags, etc.

**Additional context**
I am a new user and I am self hosting without docker. This started happening after moving to version 2.8. I was not sure what would be the proper way to update the system, so I downloaded to a new folder, installed and connected to the old database, copying the .env file and data folders from the old installation. In Linkwarden everything seems to work fine. The browser extension however gives the error.

**Comment by daniel31x13** [comment]
This is already fixed in the latest version v2.8.3.

you just need to pull the latest image.

**Comment by nuovo10** [comment]
Hello dilom

I need help installing linkwarden without docker, can you help me by indicating the installation steps?.
Regards

**Comment by dilom** [comment]
Hi, I followed the steps in the documentation :
https://docs.linkwarden.app/self-hosting/installation
and scroll down to Manual Install
