### ISSUE TITLE
the provided database credentials for `postgres` are not valid.

### ISSUE THREAD

**Issue by misterhsp** [linkwarden/linkwarden#883]
I have followed these instructions.
https://docs.linkwarden.app/self-hosting/installation (docker). But  Authentication always failed.

linkwarden_1  | Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `postgres` are not valid.

https://docs.linkwarden.app/self-hosting/installation

**Comment by hhampush** [comment]
Do you have any special characters set in your POSTGRES_PASSWORD variable?
I had the same problem when I had an exclamation mark in my passphrase, but works fine with normal characters and numbers.

**Comment by misterhsp** [comment]
Indeed, it is. I also have an exclamation mark in it.

Many thanks for the tip.




Am 23.11.24 um 10:00 schrieb Hampus Hessel:
