### ISSUE TITLE
Add possibilty to hide / disable login form to only let SSO one usable

### ISSUE THREAD

**Issue by hugosxm** [linkwarden/linkwarden#887]
**Is your feature request related to a problem? Please describe.**
We want to use linkwarden with zitadel SSO, it works but we would like to hide the "traditional" login form so all user are "forced" to use zitadel to avoid confusion

**Describe the solution you'd like**
new  env variable like NEXT_PUBLIC_DISABLE_LOGIN_FORM=true

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by HackHerz** [comment]
That already works for me? My env file contains the following two lines which should take care of that

```
NEXT_PUBLIC_DISABLE_REGISTRATION=true
NEXT_PUBLIC_CREDENTIALS_ENABLED=false
```
<img width="605" alt="Bildschirmfoto 2024-11-25 um 12 56 29" src="https://github.com/user-attachments/assets/8c43054e-7f2e-485a-a8e8-9f734857c6df">

**Comment by hugosxm** [comment]
Yes just figured this out and I was going to write it here... Thanks !
