### ISSUE TITLE
sqlite as db

### ISSUE THREAD

**Issue by Code-Slave** [linkwarden/linkwarden#94]
**Is your feature request related to a problem? Please describe.**
for personal use does pg provide anything that sqlite cannot? I try and get sqlite support from every self hosted app I can as pg is overkill 99% of the time

**Describe the solution you'd like**
Support for sqllite

I currently use linkding in sqllite for my family and have no issues. this apps looks great and Id like to use it due to the archiving.

**Comment by daniel31x13** [comment]
Swapping SQLite for Postgres shouldn't be much of a problem, I'll add this to the project to-do.

**Comment by crkos** [comment]
Hello i'd like to work on this, but i saw that more support for pg is being done, adding support for SQLite will add some changes to the database and some logic in the application, so i don't know if you really want to change from postgresql or change to SQLite in the future, definitly it will reduce some complication with working with a external instance of a db, as to just working with a file

**Comment by daniel31x13** [comment]
Linkwarden now supports SQLite, you just need to change [This Line](https://github.com/linkwarden/linkwarden/blob/89427f16f5752405ddcdbae7e147621dc9a3f1e0/prisma/schema.prisma#L6) from `postgresql` to `sqlite` and use the correct `DATABASE_URL` while taking the [Manual Installation](https://docs.linkwarden.app/getting-started/self-hosting#manual-installation).

Also there is one drawback from using SQLite, things are case-sensitive when you search for a Link.
The reason for this is Prisma (currently) doesn't support querying the database using the `mode: 'insensitive'` option for SQLite.

Gotta update the docs later...

**Comment by Code-Slave** [comment]
awesome thanks

**Comment by Code-Slave** [comment]
Ideally the db type would be an env in the compose. will make running with docker much harder

**Comment by Mat-DB** [comment]
I came across this github repo and it looks really nice!
I just do not want to install manually and would like to use SQLite because postgresql is overkill for me.

So my question, is SQLite already supported using docker-compose?

Thanks!

**Comment by lockheed** [comment]
Another thums up. Is the "env" route to SQLite possible yet?

**Comment by akhy** [comment]
> Linkwarden now supports SQLite, you just need to change [This Line](https://github.com/linkwarden/linkwarden/blob/89427f16f5752405ddcdbae7e147621dc9a3f1e0/prisma/schema.prisma#L6) from `postgresql` to `sqlite` and use the correct `DATABASE_URL` while taking the [Manual Installation](https://docs.linkwarden.app/getting-started/self-hosting#manual-installation).
> 
> Gotta update the docs later...

Tried this on latest Docker image (trying to patch the image) but apparently the code is designed for Postgres only

```
Error: Prisma schema validation - (get-dmmf wasm)
Error code: P1012
error: Field "collectionOrder" in model "User" can't be a list. The current connector does not support lists of primitive types.
  -->  prisma/schema.prisma:47
   |
46 |   collectionsJoined       UsersAndCollections[]
47 |   collectionOrder         Int[]                 @default([])
48 |   whitelistedUsers        WhitelistedUser[]
   |
error: Field "aiPredefinedTags" in model "User" can't be a list. The current connector does not support lists of primitive types.
  -->  prisma/schema.prisma:53
   |
52 |   aiTaggingMethod         AiTaggingMethod       @default(DISABLED)
53 |   aiPredefinedTags        String[]              @default([])
54 |   dashboardRecentLinks    Boolean               @default(true)
   |
error: Error validating: You defined the enum `AiTaggingMethod`. But the current connector does not support enums.
  -->  prisma/schema.prisma:67
   |
66 |
67 | enum AiTaggingMethod {
68 |   DISABLED
69 |   GENERATE
70 |   PREDEFINED
71 | }
   |
error: Error validating: You defined the enum `LinksRouteTo`. But the current connector does not support enums.
  -->  prisma/schema.prisma:73
   |
72 |
73 | enum LinksRouteTo {
74 |   ORIGINAL
75 |   PDF
76 |   READABLE
77 |   MONOLITH
78 |   SCREENSHOT
79 |   DETAILS
80 | }
```
