### ISSUE TITLE
🐳 Docker Support

### ISSUE THREAD

**Issue by daniel31x13** [linkwarden/linkwarden#97]

**Comment by bijeebuss** [comment]
I would like to work on basic docker support

**Comment by daniel31x13** [comment]
Just a follow up on what's happening in this [PR](https://github.com/linkwarden/linkwarden/pull/106).

We'll be grateful if anyone could help.

**Comment by daniel31x13** [comment]
Note to outsiders: We're 95% there (thanks to @bijeebuss).

**Comment by daniel31x13** [comment]
Merged the PR and now we have Docker Support!

**Comment by daniel31x13** [comment]
@keunes You asked for it! https://docs.linkwarden.app/getting-started/self-hosting#docker-

We're adding some more features and releasing this in the next release. (v1.1.0)

**Comment by bijeebuss** [comment]
> Would it be possible to get this designed to fully install via docker-compose? That is to say, having the images hosted/updated regularly on docker hub (it's possible to [sync](https://docs.docker.com/docker-hub/builds/link-source/) github and docker hub btw) so that setting up a docker instance would be nearly as quick as copying a compose file into a portainer stack? Without this functionality its a very manual process to sync builds since there's no automated way to sync a github fork without some scripting.

Something like this is definitely possible and not too much effort. We would just need to create a github action that builds the image and pushes it to docker hub on a release. @daniel31x13 would need to create a docker hub account for linkwarden. I could create a PR that tests it with my personal docker hub account

**Comment by daniel31x13** [comment]
@bijeebuss that really helps if you create the action file, thanks!
I’ve already created the docker hub account, just haven’t looked forward into the GH action workflow.
