### ISSUE TITLE
🌒 Dark mode

### ISSUE THREAD

**Issue by daniel31x13** [linkwarden/linkwarden#98]

**Comment by g1sbi** [comment]
Hi! I'd like to contribute to this.

**Comment by daniel31x13** [comment]
@g1sbi Sure thing, thanks!

Just one thing, I'll be pushing some changes in a few minutes to the dev branch, after that, use the "dev" branch as the starting point.

Also a couple of notes:
- I just took a look at your [project](https://thock.pro) (looks great btw!) and this is exactly how it should be.
- The toggle should be up in the navbar right *between* the "New Link" button and the profile photo.

Let me know if you had any other questions.

Thanks again!

**Comment by daniel31x13** [comment]
@g1sbi No problem! I just updated the "dev" branch, you can now start.

**Comment by daniel31x13** [comment]
Closing this issue, it'll be released in the next version.
